### ISSUE TITLE
Global option --exclude not supported in command-specific options for command core-rsync.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1155]
I've `drushrc.php` file which I've simplified to only:

    <?php
    $command_specific['rsync']        = array('exclude' => '*.gz');

But still I'm getting the following error when running below command:

    $ drush rsync @remote.src @remote.dst -v // Add -c drushrc.php to load drushrc.php manually.
    Global option --exclude not supported in command-specific options for command core-rsync due to a limitation in strict option handling.

The error happens even before evaluating remote names or doing any rsync. The weird part is that this error happens on empty folder (just drushrc.php) on Linux, but it doesn't happen on empty folder on OSX, however does happen when run in bootstrapped environment on OSX (having exact the same lastest version of drush).

Parameter `exclude` for rsync  should be correct based on the [example.aliases.drushrc.php](https://github.com/drush-ops/drush/blob/6f5f957117aab31ecf3f3552a343962d1d34ed71/examples/example.aliases.drushrc.php#L280).

I'm using drush 7.0-dev, tested on PHP 5.4 & 5.5
Could be related to: [ssh-option command-specific parameter in alias file is ignored for rsync](https://github.com/drush-ops/drush/issues/868), but I'm not sure.

I'm missing something?

**Comment by greg-1-anderson** [comment]
I will look at it when I have a chance. There is a question whether the error  you quote is correct, or the 'command-specific' documentation in example.aliases.drushrc.php is correct.  It would be helpful if you attempted to reproduce on Drush 6 and Drush 5, and report the results.

**Comment by kylethebaker** [comment]
I'm running into the issue on version 8.1.13 after upgrading from 5.10.0. Exclude was working on 5.10.0 but I'm receiving `Global option --exclude not supported in command-specific options for command core-rsync due to a limitation in strict option handling.` on 8.1.13. My drushrc.php has the following: 
```
$options["command-specific"]["rsync"] = [
  "no-perms" => true,
  "no-group" => true,
  "no-owner" => true,
  "include-paths" => "sites/:sites/default/:sites/default/files/***",
  "exclude" => '"*"',
];
```
Exclude is the only option that the message says is not supported in my case. I can provide `--exclude` directly as an argument to the `drush rsync` command and it works as expected, but it doesn't work when specified in command-specific. 

The message is being thrown from `drush_command_set_command_specific()` in `includes/command.inc`. 

It seems that in versions after 5.x , 'exclude' was added as a global option with the description: "_A list of files and directory paths to exclude from consideration when searching for drush commandfiles._" This is in the function `drush_get_global_options()` in `includes/drush.inc`.

The actual commit is here: b1e30829 (at the bottom)

I think the only thing needed in order to fix this is to add a 'context' key to `$options['exclude']` in `drush_get_global_options()`. That might be a naive solution though as I'm not familiar with what contexts actually do, but according to `drush_command_set_command_specific` it appears that if a context key is present then the global option will be unset and the command-specific option will be used instead.

I'll try this and see if anything breaks.

**Comment by kylethebaker** [comment]
I think this may just be a documentation error. Drush has `include-paths` and `exclude-paths` that can be used to achieve the same thing as rsync's `--include` and `--exclude`. By using those options you will avoid any collisions with drush's global options.

`example.aliases.drushrc.php` should be updated to use `exclude-paths` instead of `exclude`.

**Comment by weitzman** [comment]
That section of aliases file is about paths for `rsync` itself, not `drush
rsync`. The help for `drush rsync` already lists exclude-paths
