### ISSUE TITLE
Update all sites at once (not in multi-site installation)

### ISSUE THREAD

**Issue by Kumkum29** [drush-ops/drush#1176]
Hello,

I have several sites on a server.
Here the scheme of the repertories :

- drush
- vhosts
  - site 1
  - site 2
  - site 3
  - site 4...

Is there a command for update a module or the drupal core of the all sites in the repertory "vhosts"?

Thanks for your replies.

**Comment by greg-1-anderson** [comment]
If you have aliases for all of your sites:

drush @site1,@site2,$site3 pm-update

Please also read the docs, particularly https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.aliases.drushrc.php

Hopefully, your server is a test or stage server; you don't want to mass-update all of your live sites, because sometimes new code can break your site.  Testing is the most important part of any upgrade operation.
