### ISSUE TITLE
drush 6 ssh from Windows local to Linux remote using aliases

### ISSUE THREAD

**Issue by koppieesq** [drush-ops/drush#118]
I'm having trouble writing drush aliases that work well in a Windows local environment and Linux remote environment.  Depending on the configuration, I can either do remote commands or SSH, but not both.

This is Drush 6.

If I include the root setting, eg. 'root' => '/var/www', then drush ssh tries to run with an additional command: "cd /var/www && bash".  This should work fine, but I get this:

``` bash
Connection to [redacted].com closed.
'bash'' is not recognized as an internal or external command,
operable program or batch file.
An error 1 occurred while running the command `ssh -o PasswordAuthentication=no -t              [error]
[redacted]@[redacted].com 'cd /var/www && bash'`
```

When I run the same command manually it works fine.  I'm assuming the problem is because my local environment is Windows.  When I add 'os' => 'Windows', I can ssh just fine, but other remote commands stop working, like drush @alias status or drush @alias cc all.

I tried adding this:

```
    'command-specific' => array (
      'ssh' => array (
        'os' => 'Windows',
      ),
    ),
```

But I just get this:

``` bash
'--os' is not recognized as an internal or external command,
operable program or batch file.
An error 1 occurred while running the command `ssh -o PasswordAuthentication=no                 [error]

jkoplowicz@sfoconnect.com 'cd /sfo/www/sfoconnect && --os=Windows'`
```

SSH also works fine if I remove the root definition, ie. 'root' => '/var/www', but then the other remote commands don't work.

Here are suggestions that won't work:
- Switch local environment to Linux or use a VM: Thanks, but that's not an option.  This support request is to get Drush working in Windows.
- Use Drush 5: Thanks, but "the new version doesn't work" isn't satisfying either.  If this requires a patch, I will try to make one.
- Add environment variables in Windows: I did.  It didn't help.  I double checked them.

I wish I could check the d.org issues, but they're no longer available.  Bummer.

Any help?

**Comment by Joth** [comment]
Any progress on this issue? It still seems present on version 6.5.0.

$ drush @alias ssh
Connection to site.example.com closed.

The above snippet is from Cygwin on Windows 7.

**Comment by greg-1-anderson** [comment]
There is very little support for Drush on Windows.  Most folks use a VM, and run Drupal + Drush in a virtual Linux environment.

In order to make progress on native Windows support, we need one or more consistent contributors to submit and test PRs to fix Windows problems.  We haven't really had anyone pick up the torch to do that.

**Comment by koppieesq** [comment]
Yeah.  I'm the original OP and my solution was to install Linux on my workstation.  Much, much better environment if you're doing any serious development in a LAMP stack.  It's sort of a chicken and egg problem; few people do LAMP development on Windows because the tools suck, and the tools suck because few people do LAMP development on Windows.

For me, the solution was to remove the problem.

**Comment by mstrelan** [comment]
This is still an issue in Drush 8. Trying to debug this I have found the following.

As OP mentioned, setting 'os' => 'Windows' allows shell-aliases to work but breaks commands like drush status.

Changing _drush_escapeshellarg_linux() to wrap the args in double quotes instead of single quotes fixes the problem in Windows for shell-aliases and normal commands. I have not tested this in Linux.

I wonder if the issue is that drush_shell_proc_build() checks what the remote OS is, but should in fact be checking what the local OS is?
