### ISSUE TITLE
Drush is converting Cygwin paths unnecessarily. If Cygwin PHP is being used, paths *should not* be converted.

### ISSUE THREAD

**Issue by anandpathaksharma** [drush-ops/drush#1226]
## Summary
I've found an issue related to this on Stack Exchange > Drupal Answers: [Cygwin Drush throws error in Drupal folders](http://drupal.stackexchange.com/questions/143707/cygwin-drush-throws-error-in-drupal-folders).

## Background
My setup includes Cygwin's PHP port for better integration - the Cygwin PHP executable understands Cygwin paths (unix style) and *doesn't need path conversion*.

I've found the helper function that is causing this problem. My Drush version is 6.5.0...

### Code
Here's the code (file: PATH_TO_DRUSH\includes\environment.inc:194):
````
/**
 * Converts a Windows path (dir1\dir2\dir3) into a Unix path (dir1/dir2/dir3).
 * Also converts a cygwin "drive emulation" path (/cygdrive/c/dir1) into a
 * proper drive path, still with Unix slashes (c:/dir1).
 */
function _drush_convert_path($path) {
  $path = str_replace('\\','/', $path);
  $path = preg_replace('/^\/cygdrive\/([A-Za-z])(.*)$/', '\1:\2', $path);

  return $path;
}
````

## Proposed Solution
I don't have the time right now to provide a solution. I envision it would entail updating the function above to detect the location of the PHP executable in use. Maybe we could set or access a Global variable that indicates the path style that the executing PHP requires. If the PHP executable is Cygwin or Msys/MingW and understands Unix style paths, leave return the path as is. If the PHP executable was compiled natively for Windows and requires Windows style paths, then move forward with the conversion.

## Immediate Workaround
For those users who find themselves in my shoes, please open up the file and comment out the lines of code that perform the string/preg replacing... or wrap them in an appropriate condition.

### Code
````
/**
 * Converts a Windows path (dir1\dir2\dir3) into a Unix path (dir1/dir2/dir3).
 * Also converts a cygwin "drive emulation" path (/cygdrive/c/dir1) into a
 * proper drive path, still with Unix slashes (c:/dir1).
 */
function _drush_convert_path($path) {
  //$path = str_replace('\\','/', $path);
  //$path = preg_replace('/^\/cygdrive\/([A-Za-z])(.*)$/', '\1:\2', $path);

  return $path;
}
````

**Comment by greg-1-anderson** [comment]
It would be nice if someone was available to work on this.  `drush_is_cygwin(_drush_get_os())` would probably be helpful here.  Needs testing.

**Comment by diddledan** [comment]
this seems to fix it for me:

    function _drush_convert_path($path) {
      $path = str_replace('\\','/', $path);
      if (drush_is_windows(_drush_get_os()) && !drush_is_cygwin(_drush_get_os())) {
        $path = preg_replace('/^\/cygdrive\/([A-Za-z])(.*)$/', '\1:\2', $path);
      }
    
      return $path;
    }

I'll try to remember to pop back later to turn it into a proper patch/pull-request

**Comment by xymox12** [comment]
This was driving me nuts until I found this patch. @diddledan - I have done a quick test using cygwin's php and a window's php - both work as expected once the patch was applied. Thanks.

An outlying case where this might fail is when someone modifies the fstab to use another prefix other than cygdrive in cygwin, along with windows php. This would not be the fault of your logic, however, but rather the preg_replace assuming cygdrive was the prefix used - which is probably another issue to be raised if it ever is a problem for someone. I am simply noting this here in case someone who has modified cygwin's default drive prefix comes here and thinks your patch is not working.

**Comment by mlochd** [comment]
A related problem... (some background) I had a problem with my aliases for long time when I used
 **drush rsync @dev @prod**  (where dev was in referring to  'root' => 'C:\Users\me\sites')
it would return
rsync: change_dir "/cygdrive/C/Users/me/..." failed: Bad file number (9)...
but the command 
**drush sql-sync @dev @prod**
worked fine until it reached the backing up part using the command rsync to back up the sql file, and it returned the same (except with the sql file)
**rsync: change_dir "/cygdrive/C/Users/me/...sql" failed: Bad file number (9)...**
I got rsync to work by changing the alias setting of @dev in aliases.drushrc.php to   'root' => '/c/Users/me/Desktop/sites'
but, then the command
**drush sql-sync @dev @prod**
didn't work, since it could find directory "/c/Users/me/Desktop/sites"
and it couldn't back up the site anyways

So I looked for a permanent solution...I found by removing **cygdrive/** from filesystem.inc both finally worked.  It seems like my drush was picking up a cygwin environment for rsync and a mingw env. for sql-sync.

**Comment by weitzman** [comment]
We cleaned up path handling a bit on master branch. This *might* be fixed. Would be great if someone could try again with master on both local and remote side and report back status. I'll work with them to fix any remaining issues.

**Comment by weitzman** [comment]
In general, the direction is to get rid of all special handling of cygwin and mingw in Drush. We wont do path conversion. We are cleaning up paths with https://github.com/webmozart/path-util
