### ISSUE TITLE
Can't execute command after drush ssh login?

### ISSUE THREAD

**Issue by glassdimly** [drush-ops/drush#1310]
This works fine from the cli
`ssh user@example.com -i ~/.ssh/user -t 'su;'`

That is, I'm sshing in and then executing a command to switch users, the user being root.

However when I specify in my alias:
`'ssh-options' => '-i ~/.ssh/user -t "su;"',`

And then I check that alias from the cli, I get:

`$ drush @myalias status
ssh: Could not resolve hostname su;: nodename nor servname provided, or not known
$`

Hmm. I have researched and I feel this syntax is correct, similar the the ProxyCommand in this post: https://www.acquia.com/blog/drush-experts-technique . 

Am I doing something wrong or is this a bug?

**Comment by glassdimly** [comment]
Apologies, this is a bit obtuse, above.

Here is a verbose output of the command.

`drush @exampleprod status -v
Loaded alias @exampleprod from file /Users/myuser/.drush/exampleprod.alias.drushrc.php                                                                                       [notice]
Begin redispatch via drush_invoke_process().                                                                                                                                 [notice]
Calling proc_open(ssh -i ~/.ssh/exampleadmin -t "su;" exampleadmin@direct.examplemagazine.org 'COLUMNS=181 drush  --verbose --root=/web/examplemagazine.org/www/ --uri=http://default  core-status 2>&1' 2>&1);
ssh: Could not resolve hostname su;: nodename nor servname provided, or not known
End redispatch via drush_invoke_process().                                                                                                                                   [notice]
Marks-MBP:example.myuser myuser$ `

**Comment by greg-1-anderson** [comment]
Drush does not support adding a call to 'su' in sh-options.

You can do this:

`drush @site ssh su`

However, you cannot cause Drush to use 'su' for all remote commands.  Calling ProxyCommand via -o, like in the blog post you quote above, is supported, so if there is a way to use ProxyCommand to switch users, then you could use that.  I don't know  that that is possible, though.

The "drush" way to do it is to just set the remote-user to the user you want to run commands as.  If you (a) don't want to allow root logins, and (b) want to run all Drush commands as root (rather than making an admin user, like 'www-admin', with appropriate privileges), then you are in sort of a narrow special use case.

You might want to try using '%drush-script' in your path aliases to point to an executable that uses su or sudo to switch to the root user, and then calls through to 'drush'.  That could probably be made to work.
