### ISSUE TITLE
How to use hook_sql_sync_sanitize()?

### ISSUE THREAD

**Issue by pjcdawkins** [drush-ops/drush#1357]
From `hook_sql_sync_sanitize()`, it seems it's not possible to check whether a database table exists, or even whether a module is installed. Or is it?

See this issue for TFA Basic: https://www.drupal.org/node/2449121

And OAuth2 Server has the same problem: http://cgit.drupalcode.org/oauth2_server/tree/oauth2_server.drush.inc

**Comment by greg-1-anderson** [comment]
The reason this does not work as written is that the sanitize function is called with no bootstrap.  Usually, you could get around this by bootstrapping Drupal via `drush_bootstrap_max()`; however, in the case of sanitize, the correct Drupal site is not necessarily selected, and might even be remote. 

You have a couple of choices here.

1) Use ```drop table if exists `prefix_tablename`;```

2) Get a list of the available tables, and test to see if the target table exists.
```
$values = drush_invoke_process($site, "sqlq", array("show tables;"), array(), array("integrate" => FALSE));
$tables = explode("\n", $values['output']);
```

The first option is simple, but not very desirable, as you'd have to re-create the table again.  Regrettably, `truncate table if exists ...` does not seem to be supported.

I think that the second option is preferable.  It will work regardless of whether $site is local or remote, because drush_invoke_process() will make a remote call if it needs to.

In either event, you need to handle table prefixes manually, if you want to support them.
