### ISSUE TITLE
Add a 'make-composer' command

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#1388]
The [Composer Manager](https://www.drupal.org/project/composer_manager) module does an interesting job of consolidating the `composer.json`files from all enabled modules and running `composer install`to generate a platform-wide `autoload.php`. Unfortunately, it requires a site installed on the platform, and so doesn't work headless, or integrated into a `drush make`-based workflow.

It'd be interesting to add a command that can parse a Drush makefile, and check for `composer.json` files, and essentially do what `composer_manager` does.

We could also add a `--composer-install` option to `drush make` that would invoke `make-composer` in a post hook. This'd allow an option to be added to a makefile to trigger this new behaviour.

**Comment by mradcliffe** [comment]
It is possible to run Composer Manager without a site install. See my [.travis.yml](https://github.com/mradcliffe/xero/blob/8.x-1.x/.travis.yml#L22) for it in the wild. Note that I needed to remove vendor completely because composer update runs into Github API limits when it's just updating as opposed to getting everything in a fresh install ([#1314](https://github.com/composer/composer/issues/1314)).

This probably could be documented better, but the following is possible, which I've done to run my phpunit tests on my local environment without a full LAMP environment. Hopefully this will continue to work. :-)
```bash
./modules/composer_manager/scripts/init.sh
cd core
composer drupal-update
```

+1 for a feature like this native to drush though.

**Comment by ergonlogic** [comment]
My understanding is that init.sh only works for Drupal 8 sites. We'd want something that works with Drupal 7 to ease the transition towards composer-based builds, and probably eventually deprecating Drush Make.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
