### ISSUE TITLE
Bring l10n_update commands in Drush core

### ISSUE THREAD

**Issue by penyaskito** [drush-ops/drush#139]
From https://drupal.org/node/2045977:

l10n_update functionality is in Drupal core: [#1191488: META: Integrate l10n_update functionality in core](http://drupal.org/node/1191488). We need to adapt and incorporate their drush commands.

http://drupalcode.org/project/l10n_update.git/blob/refs/heads/7.x-1.x:/l10n_update.drush.inc

**Comment by goba** [comment]
Is there an up to date issue on this one? What is the Drupal 8 translation update support status?

**Comment by goba** [comment]
Is there an up to date issue on this one? What is the Drupal 8 translation update support status?

**Comment by penyaskito** [comment]
Nothing that I'm aware of. There is https://github.com/dawehner/drush_language though

**Comment by goba** [comment]
Yeah for Drupal 8 this would be core features to support, which is why I asked ;) I have a post at http://hojtsy.hu/blog/2013-jul-23/drupal-8-multilingual-tidbits-9-deployment-friendly-automated-downloads which refers to this issue for people to follow. If there is a better place to follow for D8 locale support, I would love to link to that.

**Comment by gabooh** [comment]
Would love this issue to be reopened, locale commands in drush would be very useful.
Related forum post about why it could be useful : https://www.drupal.org/node/2715369

**Comment by tstoeckler** [comment]
Wow, I wasn't aware this issue even existed. Since #1817 (and #1818 resp.) we have `drush locale-check` and `drush locale-update` commands in Drush core. I use these regularly as part of a multilingual deployment workflow. Looking at http://cgit.drupalcode.org/l10n_update/tree/l10n_update.drush.inc what is missing is a `drush locale-status` command to bring this is inline with the D7 `l10n_update` module. I would be happy to review and merge a PR that adds that, not sure if I will get to it myself.

**Comment by gabooh** [comment]
@tstoeckler what is missing is a way to import po files. AFAIK I can't do that with `drush locale-check` and `drush locale-update`.
I've used drush_language mentionned above which worked perfectly.
Having this in drush core would make sense.

**Comment by tstoeckler** [comment]
Well you can in the sense that you can put PO files in the sites translation directory and then `drush locale-update` will find and import them. But you are right that there is no dedicated command to impor a single PO file explicitly. AFAICT that was not part of the D7 `l10n_update` Drush commands, either though, so I'm not sure that that is relevant to this issue.

I do think we should have commands to im- and export PO files in Drush core as that is functionality provided by the Drupal core `locale` module, even in Drupal 7. I even left a `@todo` to that effect in the code: https://github.com/drush-ops/drush/blob/master/commands/core/locale.d8.drush.inc#L37
Please open a separate issue for that, though.

**Comment by gabooh** [comment]
Using the core `locale-update' feature is not straightforward. I've just figured it out. I've detailed that in this drupal forum post (https://www.drupal.org/node/2715369). It's just missing documentation in the end, works fine.

I've created https://github.com/drush-ops/drush/issues/2164 anyway.
Thank you for your help.
