### ISSUE TITLE
drush vget does not output objects in its default (YAML) format

### ISSUE THREAD

**Issue by pfrenssen** [drush-ops/drush#1417]
When a variable contains an object it is not output using the YAML formatter. Instead the user is told the variable contains NULL:

```
$value = (object) array('test' => TRUE);
variable_set('my_variable', $value);
```

```
$ drush vget my_variable
my_variable: null
```

Since the YAML formatter is the default this is perhaps a major bug.

**Comment by weitzman** [comment]
The Symphony YAML dumper does not support dumping of resources or objects. The Doxygen for \Symfony\Component\Yaml\Dumper::dump says`* @param bool  $exceptionOnInvalidType true if an exception must be thrown on invalid types (a PHP resource or object), false otherwise`. We could enable that Exception to make this limitation more clear.

We could change the default output formatter to JSON but 'm not sure that this would round trip successfully with your example. Try --format=json and see if that meets your needs better. --format=var_export would round trip successfully if you are working in php.
