### ISSUE TITLE
Drush 8.x: simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:72

### ISSUE THREAD

**Issue by diqidoq** [drush-ops/drush#1437]
Latest Drush 8.x with PHP 5.6.7 (Debian Jessie, Apache2, fresh Drupal 7 minimal install) causes 

    simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:72
    Failed to get available update data from https://updates.drupal.org/release-history/YOURMODULE/7.x

suddently in the last days when trying to fetch modules like with drush dl. No way out. XML files testing from Drupal.org are ok. Connection seems not officially 100% secure (user reports) but this issue seems not to be connected with this one. Testing with Drush 7.x and php 5.4 DOES NOT cause this. Required php modules are fine.

**Comment by weitzman** [comment]
See end of #894. Leaving this open for others to stumble on rather than file dupes.

**Comment by diqidoq** [comment]
thx josh! awesome, fast and helpful decision and referencing to the point. I will try with phpbrew to switch php version and will report back if it helps.

**Comment by jonhattan** [comment]
A workaround is to disable certificate checks in wget. For that, just put `check_certificate=off` in `$HOME/.wgetrc`

**Comment by diqidoq** [comment]
While this should no be recommended for production server enviroments with data sensitive structure I would take that as a very helpful advice for testing and development enviroment situations, which are the most anyway when you install modules randomly. Many many thanks for the fast replies @jonhattan @weitzman

**Comment by glassdimly** [comment]
Seeing this bug as "simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:42". Confirming that check_certificate=off in $HOME/.wgetrc works as a workaround. 

However, as per the [other ticket](https://github.com/drush-ops/drush/issues/894), I thought that because updates.drupal.org had installed a TLS cert we'd no longer be seeing this error. Hmm.

**Comment by el22or** [comment]
Here is command for newbies: `echo "check_certificate=off" > ~/.wgetrc`, and also confirm this workaround works.

**Comment by weitzman** [comment]
No longer happenning, AFAIK. Please post in #894 if still having problems.

**Comment by nmeegama** [comment]
check_certificate=off worked for me. Thanks

**Comment by Jones-L** [comment]
Got this error using drush dl drupal (drush 9.0, drupal 8), because I forgot to install xml extension: 
apt-get install php7.0-xml
fixed it.
(Posting in case someone else made my mistake in 2016.)

**Comment by joejoseph00** [comment]
using drush 7.4.0 I had the same problem,
the solution was to follow instructions in #894

**Comment by CodeJourneymen** [comment]
Drush 8.1.7
PHP 5.6.16
Mac Sierra 10.12.3 (ie no wget)
(running on Postgres 9.4.5)

Had this problem for a long time. It went away for a while, now its back again. I updated nothing.

`$ drush rl
simplexml_load_file(): I/O warning : failed to load external entity  [warning]
"" Project.php:74
Failed to get available update data from                             [error]
https://updates.drupal.org/release-history/drupal/7.x
No valid projects given.`

and 

`$ drush up drupal
Update information last refreshed: Never
 Name    Installed Version  Proposed version  Message                     
 drupal  Unknown            Unknown           Specified project not found `


If I try `curl https://updates.drupal.org/release-history/drupal/7.x`
I get
`$ curl https://updates.drupal.org/release-history/drupal/7.x
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
`
So something is off with the Drupal SSL cert for the updates?

To fix this locally I added a ~/.curlrc file with just `insecure` in it.
Not a good fix, but gets me working.

**Comment by lifenstein** [comment]
If you're using Acquia Dev Desktop or anything else which uses msys, the wget config file is at `msys/etc/wgetrc`. If you haven't before, you'll of course have to create it. For DevDesktop, the msys folder is inside `C:\Program Files (x86)\DevDesktop\common\` if the location is default. Just need to add `check_certificate=off` to wgetrc (not `wgetrc.txt`!) and save.

**Comment by geerlingguy** [comment]
I just wanted to post one more gotcha in this issue—in my case I was running inside a Drupal VM docker container instance, and after some more debugging noticed that DNS wasn't resolving.

Without DNS working, I got:

```
root@749e8aa709c4:/var/www/drupalvm# drush dl drupal
simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:74                        [warning]
Failed to get available update data from https://updates.drupal.org/release-history/drupal/8.x               [error]
Could not download requested project(s).                                                                     [error]
```

But once I added the following in my Docker Compose file, it worked:

```yaml
    dns:
      - 8.8.8.8
      - 8.8.4.4
```

(This was added in the Drupal VM container configuration.)

**Comment by joejoseph00** [comment]
Ya this issue is probably only affecting the windozers and macintapplers.  A better solution is to use a sane distribution of Linux like the latest Ubuntu LTS or Mint based on LTS.

**Comment by alphex** [comment]
Weird observation on this one.

In Drupal 8.3.7

"drush dl _module name_" won't work in the doc root.

but if I run the same command in the /modules directory, it works fine.

**Comment by pmagunia** [comment]
You will also get this error if Port 443 (outbound) is closed on your server's firewall. Opening port 443 resolved the issue for me.

**Comment by Ambient-Impact** [comment]
If someone else who's starting getting this error when using Acquia Dev Desktop, here's what I found after two days of pulling my hair out: the ```wget``` version that Dev Desktop includes as part of the ```msys``` package is really out of date, at version 1.12.x. Replacing that ```wget.exe``` with a more recent one (in my case, 1.19.4) fixed it and Drush now works again! Using the ```--debug``` flag on Drush and also on wget.exe were incredibly helpful in solving this.
