### ISSUE TITLE
Add user-list command

### ISSUE THREAD

**Issue by fadehelix** [drush-ops/drush#149]
There was discussion about this issue at drupal.org: 
https://drupal.org/node/1199080

**Comment by dankegel** [comment]
FWIW, I tried patching this into drush 5.10.0, but it complains:

WD php: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check  [error]
the manual that corresponds to your MySQL server version for the right syntax to use near '%d)' at line 1: SELECT
users_roles.rid AS rid
FROM 
{users_roles} users_roles
WHERE  (uid = %d) ; Array
(
    [0] => 1
)
 in drush_db_select() (line 94 of /usr/share/php/drush/includes/dbtng.inc).

**Comment by jbickar** [comment]
See https://www.drupal.org/sandbox/jbickar/2493771.

Quite raw at the moment, but should work for Drupal 6 and 7.

**Comment by kenorb** [comment]
Alternative solution:

    drush uinf $(drush sqlq "SELECT GROUP_CONCAT(name) FROM users")

**Comment by bbrowntimeinc** [comment]
I also get the MYSQL error mentioned by @dankegel when trying to apply this patch to drush 5.9

WD php: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL[error]
server version for the right syntax to use near '%d)' at line 1: SELECT users_roles.rid AS rid
FROM 
{users_roles} users_roles
WHERE  (uid = %d) ; Array
(
    [0] => 1
)
 in drush_db_select() (line 94 of /usr/share/pear/drush/includes/dbtng.inc).
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;%d)&#039; at line 1: SELECT users_roles.rid AS rid
FROM 
{users_roles} users_roles
WHERE  (uid = %d) ; Array
(
    [0] => 1
)
 in drush_db_select() (line 94 of /usr/share/pear/drush/includes/dbtng.inc).
Drush command terminated abnormally due to an unrecoverable error.
