### ISSUE TITLE
Provide better info when The external command could not be executed due to an application error.

### ISSUE THREAD

**Issue by greggles** [drush-ops/drush#1560]
I was debugging a drush site/command combination that was getting the infamous error:

"The external command could not be executed due to an application error."

Which is not so useful.

What I found was that several people are able to debug this problem by using either --verbose or --debug. 

Eventually I ended up going into backend.inc and printing out the ```$proc``` which helped me see that the problem in the ```$proc['output']``` was a fatal error in requiring a file.

So...
1. The error message could be amended to suggest using --debug or --verbose to help diagnose the problem.
2. If someone has used --debug when invoking the command AND this error is about to be set, it seems worthwhile to log the ```$proc['output']```

**Comment by greg-1-anderson** [comment]
Generally, when this error message appears, Drush does not have much additional info to go on, and `$proc['output']` should, I think, already be printed.  Adding advice to run again with --debug sounds reasonable, though.

**Comment by greggles** [comment]
The error I hit is caught and displayed in newer versions of drush.

**Comment by danlobo02** [comment]
I had this error. The first thing I noticed it was caused by a memory error. After some investigation i found that passing:

$backend_options = ['invoke-multiple' => '1']; through to drush_invoke_process() when calling a migration script resolved the issue for me. I do not understand why this is necessary but managed to reduce my memory consumption by a factor of 8. Strangely the same was true when passing though as a default of 4.
