### ISSUE TITLE
drush_sql_register_post_sync_op() query with braces enclosing table does not work

### ISSUE THREAD

**Issue by AohRveTPV** [drush-ops/drush#1582]
Works when using `drush sql-sanitize`:
`drush_sql_register_post_sync_op('password_policy_history', dt('Delete all Password Policy history table entries'), "DELETE FROM password_policy_history;");`

Does not work:
`drush_sql_register_post_sync_op('password_policy_history', dt('Delete all Password Policy history table entries'), "DELETE FROM {password_policy_history};");`

The former, though, presumably does not work for sites using table prefixes.  So there seems to be no single way to write the query that works for all configurations.

Using Drush Git master latest.

This issue arose from this issue:
https://www.drupal.org/node/2555053

**Comment by mstrelan** [comment]
sql_drush_sql_sync_sanitize() includes checks to determine if the table name should be wrapped in braces. For me this seems to wrap the table names regardless because my db prefix is apparently an array and therefore not empty. Regardless of whether or not it should be wrapped, ultimately the query is written to a temporary file and read directly by mysql, so if there are braces they will throw an error. Braces should be replaced by the actual prefix.

**Comment by weitzman** [comment]
Drush sql-sanitize replaces braces when the --db-prefix option is provided.

**Comment by AohRveTPV** [comment]
> Drush  sql-sanitize replaces braces when the --db-prefix option is provided.

But it errors when --db-prefix is not provided and braces are used in the query.  So it seems to be impossible to write a query for sql_drush_sql_sync_sanitize() that works for both sites using and not using database prefixes.

**Comment by weitzman** [comment]
Oh crap. That does look like awkward. Today, you have to write your sanitize hook like Drush core does it in sql_drush_sql_sync_sanitize():
```
if (drush_get_option('db-prefix') || !empty($databases['default']['default']['prefix'])) {
    $wrap_table_name = TRUE;
  }
  else {
    $wrap_table_name = FALSE;
  }
```
Or more tersely:
```
$wrap_table_name = drush_get_option('db-prefix') || !empty($databases['default']['default']['prefix'])`. 
```

Then you add braces based on $wrap_table_name.

Ping @bjeavons since this went in with fdffc6519c9d6e3f02c7f85ba733a8c635680cbf. 

I'm not sure why we don't unconditionally to the prefix replacement. This is such a useless part of Drupal that I hesitate to spend much time making it better. It could easily cause more harm than help.

**Comment by weitzman** [comment]
I updated the example in https://github.com/drush-ops/drush/blob/master/drush.api.php#L282 to show current table wrapping best practice.
