### ISSUE TITLE
Update from drupal 8 beta 16 to Rc1 using drush gives error

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [drush-ops/drush#1676]
I use drush 8.0.0 rc1 to upgrade drupal ( drush up drupal)
The upgrade is performed, but at the end I get an error.
 Drush Version   :  8.0.0-rc1

Post updating views                                                  [ok]
Cache rebuild complete.                                              [ok]
Finished performing updates.                                         [ok]
PHP Fatal error:  Class 'Symfony\Component\HttpFoundation\Response' not found in /home/hn/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php on line 133
PHP Stack trace:
PHP   1. {main}() /home/hn/.composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /home/hn/.composer/vendor/drush/drush/drush.php:11
PHP   3. Drush\Boot\DrupalBoot8->terminate() /home/hn/.composer/vendor/drush/drush/drush.php:79
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'Symfony\Component\HttpFoundation\Response' not found in
/home/hn/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php,
line 133
[hn@drupaldevel default]$ drush --version
 Drush Version   :  8.0.0-rc1

**Comment by kordianbruck** [comment]
+1: Same thing happens to me. Any ideas?

**Comment by greg-1-anderson** [comment]
Although I have not traced through this all, I think that what is happening is:

1. pm-updatecode bootstraps Drupal
2. The Composer autoloader caches all of the filesystem locations of all of the available classes
3. Drupal is updated, and the cached locations become unavailable
4. Drush tries to call the completion routines at the end of the command, and the failure occurs because the file containing Symfony\Component\HttpFoundation\Response no longer exists.

I think that the solution here is to make pm-updatecode be a DRUSH_BOOTSTRAP_NONE command, and have it use drush_backend_invoke() to fetch the information it needs about available updates via the pm-updatestatus command.  That way, the bootstrap + teardown will all happen before any Drupal code changes.

**Comment by weitzman** [comment]
pm-updatestatus is already done within a drush_invoke_process(). I can see benefit by making updatecode into a NONE but eventually we do have to bootstrap Drupal and can run into errors. So I'm still a bit hazy on the real problem here and the proposed solution.

**Comment by greg-1-anderson** [comment]
I made a proof-of-concept PR that basically works, but still needs some more work.
