### ISSUE TITLE
Bundle the make file(s) with the build

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/drush#1698]
I have come across many projects that were deployed via drush make, with the repository in question long gone. The make files in most cases are no longer available in this situation.

Proposed resolution: bundle the make file(s) with the build. This could be toggle-able, but I'd recommend defaulting to on. (Any files ending in `.make` are already blocked by Drupal's `.htaccess` file.)

Thoughts?

**Comment by weitzman** [comment]
Seems sensible to me. Dunno if we automatically include a make.lock as well? That would be in line with Composer.

**Comment by ergonlogic** [comment]
I've had a long-standing feature request for this in Aegir. I'm happy to tackle it here in core.

So, where do we figure the makefile(s) should go? In `sites/all/drush`?

I'm definitely in favour of including a lockfile, but we'd want to make sure it isn't accessible.

**Comment by ergonlogic** [comment]
The only real challenge I see here is when the makefile used has includes. In that case, in order for the bundled makefile to be of any use, we'd have to bundle the includes too. These would have to have the same file hierarchy as the original as well, unless we want to start altering the source makefiles.

Without altering the source files, I don't know how reliable this'd be. Consider this (real-world) example:

    core = 7.x
    api = 2
    
    includes[] = ../includes/core.make
    includes[] = ../includes/modules.make

On the other hand, one of the main reasons to create a lockfile is specifically to overcome this complication, by compiling all the source makefiles into a single consolidated one. Since this part is a no-brainer, I'm going to start there.

**Comment by ergonlogic** [comment]
I've added a `--bundle-lockfile` option, that does exactly what it says. I also added `allow-additional-options` to `make-lock`, so that the generated makefile will respect options passed into `make`, such as filtering with `--projects`.

I'm open to trying to bundle source makefiles too, but we'd need to figure out how to handle includes, as discussed above. Personally, though, I don't see too much benefit, considering we can bundle the lockfile now. So I'd be satisfied with closing this issue, as is.
