### ISSUE TITLE
pm-updatelock for Composer built sites

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#1701]
Within 1-2 years, I expect most Drupal 8 sites to [use a Composer workflow](https://github.com/drupal-composer/drupal-project) for building the codebase.  In order to update modules, the flow here is:

1. Determine modules with newer releases
-----------------
The two ways to do this are ``composer update --lock` and `drush pm-updatestatus`. Drupal releases have the idea of security versus non-security which is really important. I expect that folks will use pm-updatestatus for a long time

2. composer update module1,module2
------------------
This command updates your composer.lock file so that future builds get updated modules.

3. Commit the composer.lock file.
-----------------
This is a straightforward `git` operation

Proposal
---------------
A new pm-updatelock command runs pm-updatestatus internally and then builds the corresponding `composer module1,module2` command. It can stop there or optionally execute the command and even more optionally commit the lock file. The optional running of `composer update` and `git commit` are analogous to the optional `git add`, `git commit`, `git push` operations at end of config-export.

**Comment by weitzman** [comment]
As always, @webflo is two steps of everyone. Behold https://github.com/webflo/drupal-security-advisories which is a Composer dependency you add to your project's composer.json. That repo has an  automatically updating composer.json which lists insecure module releases (e.g. [D7](https://github.com/webflo/drupal-security-advisories/blob/7.x/composer.json), [D8](https://github.com/webflo/drupal-security-advisories/blob/8.0.x/composer.json) as conflicts. All you have to do is build your project every day in a CI tool, and you will get a build fail notification when one of your modules goes insecure. 

So in the long run, I do think Drush gets out of the code management business for D8+.

**Comment by greg-1-anderson** [comment]
@webflo's tool is awesome, but... I need to test it again before I comment in depth, but I am wondering if it does the right thing if you (a) take care to manage your composer.lock file correctly, and (b) have a module with a minor security vulnerability that does not affect you.  The main problem I had with this technique was that the error messages were hard to diagnose.  I think that this is the future, but in the present, it might be useful to have a tool like you describe, that reports the security vulnerabilities and allows you to move forward, updating the modules you need to.

There are times you just don't want to touch the live site -- and there are times you have to.

**Comment by weitzman** [comment]
Perhaps there is a way to alter/remove a particular conflict specification in the event that there is a Sec vulnerability which does not affect you?

**Comment by greg-1-anderson** [comment]
So, the shortcoming of this tool is that its final output is merely a list of project names with insecure versions blacklisted. There is a marvelous simplicity in this that is very compelling, but, if you want to ignore a constraint, you need to clone and edit the file.

Hm, now that I think about it, though, perhaps if you updated your root composer.json file, and put a conflicting, laxer restriction on a blacklisted project you did not want to update, your rule might take precedence over the one in drupal-security-advisories.  I'll give it a try.

**Comment by greg-1-anderson** [comment]
Actually, it would be a a bad idea to alter a conflict by adding a static entry to your root composer.json file.

Consider the following scenario (unrealistic version numbers used on purpose):

1. Your project requires `drupal/example: 1.*`, which pulls in example/example 1.0.
2. A security advisory is issued, and `drupal/example: 1.1` is released.
3. `conflict: { "drupal/example": "< 1.1" }` is added to the security-advisories project.
4. You decide that the security advisory does not affect your project, and mark it okay to use.
5. Another security advisory comes out, and `conflict: { "drupal/example": "< 1.2" }` is added to the security-advisories project.

Currently, there is nothing that you can do to implement `4`, and `5` is the reason for this.  If you were able to say that "drupal/example: 1.0 is okay for my project", then you would be in danger of missing the advisory that you need to go to version 1.2, which might be necessary for you.  This is why a 'conflict' directive in your root composer.json file is in addition to, not instead of, any other conflict directives found in any of your dependencies.

If someone were to implement an `allow-conflict` directive, it would have to be versioned.  So, for example, you could hypothetically say `allow-conflict { "drupal/example": "1.1" }`, which would mean that Composer should use "drupal/example": "1.1" instead of "drupal/example": "1.0" when evaluating `conflict` directives.  That way, if a `conflict: { "drupal/example": "< 1.2" }` did come along, it would correctly flag your project as being in conflict.

I don't know offhand if it would be possible to implement `allow-conflict` in a composer extension, or if it would require modification of Composer core.  It would be nice if `allow-conflict` allowed additional metadata, so folks could put in a comment explaining why the conflict should be ignored.  For that matter, it would be even better of the conflict directive allowed such a comment, so that the security advisories tools could include URLs and other helpful pointers that are emitted when a conflict occurs.

Despite these shortcomings, I still believe that  https://github.com/webflo/drupal-security-advisories is the future, and we should not try to solve these problems in Drush.

**Comment by weitzman** [comment]
How about a [replace](http://www.darwinbiler.com/how-does-the-replace-property-work-in-composer/), so that your example-1.0 is recognized as example-1.1 in the eyes of Composer? Even if that required a fork of example, I think this could be acceptable.

If thats not good, I dont think the scenario you describe is that problematic. A Drush .lock file is also a permanent 'ignore this project', and folks have not complained.

**Comment by greg-1-anderson** [comment]
The problem with `replace` is that it can only be used to add replacements for "this project".  So, for example, to attempt to replace `drupal/dynamic_entity_reference: 8.1.0-beta1` with 8.1.0-beta2 in your project, you would have to redefine the drupal/dynamic_entity_reference project.  Something like this is close (add to the `repositories` section):
```
        {
            "type": "package",
            "package": {
                "name": "drupal/dynamic_entity_reference",
                "type": "drupal-module",
                "version": "8.1.0-beta1",
                "source": {
                    "url": "http://git.drupal.org/project/dynamic_entity_reference",
                    "type": "git",
                    "reference": "8.1.0-beta1"
                },
                "replace": {
                    "drupal/dynamic_entity_reference": "8.1.0-beta2"
                }
            }
        }
 ```
Unfortunately, this does not work; drupal/dynamic_entity_reference 8.1.0-beta1 is still rejected by the conflict in drupal security advisories.

I also tried unabashedly lying to Composer, to see if I could convince it to bring in a certain library as 'beta2' when it was really 'beta1'.  This did not work.

However, a different sort of lie worked very well:
```
        {
            "type": "package",
            "package": {
                "name": "my-fork/dynamic_entity_reference",
                "type": "drupal-module",
                "version": "8.1.0-beta1",
                "source": {
                    "url": "http://git.drupal.org/project/dynamic_entity_reference",
                    "type": "git",
                    "reference": "8.x-1.x"
                }
            }
        }

 ```
Here, I am telling Composer that there is an entirely new project called my-fork/dynamic_entity_reference. Composer believes that this an entirely different project than drupal/dynamic_entity_reference, even though they draw their source code from exactly the same repository. Because Composer thinks they are different projects, it does not complain at all when I require my-fork/dynamic_entity_reference: 8.1.0-beta1.

This workaround is a little obtuse, and also shares the property of a Drush .lock file that you mention above -- you will not be warned of future security advisories that come out after you have locked your project.  However, given that it is fairly unusual to deliberately ignore security updates, perhaps this is acceptable, and we can consider the situation "solved" for now.

Maybe a couple of utility commands to create and remove these forks might be helpful; however, I do not think these would be Drush commands in any event.

**Comment by greg-1-anderson** [comment]
As an aside, I should also mention that it is no longer necessary to explicitly update your Drupal 8 "scaffolding" files (e.g. .htaccess) after a composer/update, as drupal-composer/drupal-project will do this step on its own, once https://github.com/drupal-composer/drupal-project/pull/77 is merged. So, that's less update management for Drush to have to worry about.

**Comment by greg-1-anderson** [comment]
Another note about opt-ing out of drupal-security-advisories vs. the Drush --lock function is that in the later case, pm-updatestatus continues to advise you of the availability of security releases, whereas in the former case, if you create a new name for a project in order to continue to use a version that is flagged insecure, the messages are completely silenced.

Folks could always use https://github.com/webflo/drupal-security-advisories for security and use pm-updatestatus for generating reports.

**Comment by weitzman** [comment]
IMO the "worked very well" approach is acceptable. I'm going to close this issue. Of course anyone is welcome to write pm-updatelock if they wish. If you do that, please share the link here.

**Comment by weitzman** [comment]
I documented the 'worked very well' example to https://github.com/drupal-composer/drupal-security-advisories/pull/1. Should get merged soon.

**Comment by greg-1-anderson** [comment]
Great. Also, I don't think I've referenced https://github.com/drupal-composer/drupal-project/pull/85 here yet; this PR adds drupal-security-advisories to drupal-project by default.
