### ISSUE TITLE
drush dl --default-major option is ignored when running in Drupal root

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1735]
I'm running those commands in order to download the latest Coder module:

    $ drush -y dl --default-major=8 coder --destination=~/.drush
	Install location ~/.drush/coder already exists. Do you want to overwrite it? (y/n): y
	Project coder (7.x-1.2) downloaded to ~/.drush/coder.                                
	Project coder contains 3 modules: coder_upgrade, coder_review, coder.
    $ drush -y dl coder-8 --destination=~/.drush
    (some as above)

It doesn't work (as shown above) when I'm running inside Drupal 7 root directory, however it works when I run outside.

Please note that Coder 8.x-2.x should work fine in order to check for Drupal 7 code.

Is it expected behaviour that this option is ignored when there is different Drupal core version is present in the current directory? If so, it's not expected/predictable which version would be downloaded depending on in which directory I am currently.

**Comment by greg-1-anderson** [comment]
Yes, this is expected behavior. Once Drush has decided the major Drupal version, it will not allow you to switch to some different major version e.g. for the pm commands.

The workaround here is to tell Drush to not bootstrap the current Drupal site:

`drush @none -y dl --default-major=8 coder --destination=~/.drush`

**Comment by kenorb** [comment]
Seems `@none` does the trick.
