### ISSUE TITLE
Keep .htaccess directives block when running drush update [enhancement]

### ISSUE THREAD

**Issue by superbiche** [drush-ops/drush#1761]
As drush update rewrites entirely the .htaccess - and while this seems normal and secure - we have to manually backup the production .htaccess in the upgraded core directory.

It could be great if, for example, we could write custom .htaccess directives wrapped around begin and end comments, and tell Drush to read these, temporarily store these, write down the new, updated .htaccess, then write back the custom directives.

Whilst this could be a security issue if, for example, someone writes directives that are contradictory with Drupal's ones, we could consider everyone is responsible enough to check the .htaccess after the upgrade process, to ensure everything is OK.
This could save great amounts of time for those who don't have an automated deployment system.

I can make a PR if this enhancement seems interesting.

**Comment by greg-1-anderson** [comment]
This comes up periodically. The bigger problem than contradictory directives is the chance that pm-updatecode might overwrite necessary additions to .htaccess that were supposed to be part of the upgrade.

The best way to deal with this is to assume that pm-updatecode will always overwrite .htaccess. If you have your own custom directives, then you should use a post-pm-updatecode hook to re-apply them.  Ideally, your directives should only be appended or prepended to the existing .htaccess file, so that you can be confident that the edit operation, at least, will always work correctly.  You should, of course, always test to make sure that your additions do not cause problems after the upgrade.

**Comment by jonhattan** [comment]
See [examples/pm_update.drush.inc](https://github.com/drush-ops/drush/blob/master/examples/pm_update.drush.inc) for an example of recovering a file from the backup after pm-update. In a similar way you can implement your proposal in a custom code, even contribute a drush extension :)
