### ISSUE TITLE
Adapt archive-dump and archive-restore for Composer built sites

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#1779]
archive-dump currently packages the drupal code, uploaded files, and sql dump into a tarball. this is useful when moving your site to new provider or archiving for backup. archive-restore untars that right into a docroot dir.

Sites built with http://github.com/drupal-composer/drupal-project have additional useful files above docroot. Namely, vendor, scripts, composer.json, and composer.lock. Should these be in the tarball as well? If so, do we hard code to this list of files/dirs? Should archive-restore now untar to one directory higher to make room for these files (if present).

Thoughts? /cc @webflo @bojanz @greg-1-anderson

**Comment by greg-1-anderson** [comment]
Hm, the hard part is finding the composer.json.  This file is usually above the docroot, sometimes is in the docroot, but can be anywhere.  Also, the presence of a composer.json does not necessarily mean that composer was used to build the site (e.g. Drupal 8).

My suggestion would be for archive-dump to only go into composer mode on request. We could add a --composer flag to account for this. The heuristic might be something like this:

1. If the user specified --composer=path/to/composer.json, always use that.
2. If the user specified --composer, then prefer ../composer.json over ./composer.json, and report which was selected.
3. If --composer is specified and no obvious composer.json file is found, then fail.

If composer.json is above the docroot, then we do not necessarily know what should be included, and what should not.  If there is a .gitignore next to the composer.json, then we can presume that anything in the .gitignore should be excluded, and everything else should be taken. If there is no .gitignore, then I suppose we take everything.

I think that by default, we should take the vendor directory, since folks usually expect that archive-dump produces a usable archive; we might want a separate option to exclude it, though. Would it be an error (or perhaps just a warning) if there is no composer.lock?  Usually you'd want one of these in your archives.
 
Archive restore could prompt the user if there is a composer.json present, but no vendor directory. We'd have to parse the composer.json after extraction to figure out where the vendor dir should be. We could have an option to force `composer install` on restore.  I don't think that archive restore needs to do anything else on unpack; it's up to the user to figure out where the docroot is.

**Comment by webflo** [comment]
Instead using different heuristics we could add some config parameters (--include/--exclude) and add proper default configuration to the composer project template.

**Comment by user58258** [comment]
Is there any plan for this being addressed anytime soon?

Drupal sites with out a common-sense backup & restore procedure are not something that I'll put into production & dare to depend on.

Especially with Composer install & update being the way of Drupal from now on IIUC, that procedure can be
(1) module based (n/a for Composer+D8)
(2) Drush based (n/a for Composer+D8)
(3) DIY (??here for Composer+D8)
Just trying to get a sense for what's happening on this -- since November of last year.

**Comment by weitzman** [comment]
Happy to review PRs. The maintainers are not actively working on this.

I think the urgency is low. SItes using Composer are generally using version control for code, and DB backup for data. archive-dump isn't really "common sense backup and restore" IMO.

**Comment by user58258** [comment]
Okay thanks for getting back.  Frustrating for us to not have a documented backup & restore procedure.

Anyway, just curious , what's changed since you said

> archive-dump currently packages the drupal code, uploaded files, and sql dump into a tarball. this is useful when moving your site to new provider or archiving for backup. archive-restore untars that right into a docroot dir.

?

**Comment by brantwynn** [comment]
The way I am working around this right now is to do a drush site-archive, then immediately extract it into an empty directory. I then manually copy the vendor folder into the newly extracted directory and follow that up by re-archiving everything and replacing the original tarball. Not ideal but it should be scriptable on your end...

**Comment by nalipaz** [comment]
Food for thought, but perhaps this should also consider other possible directories/files outside of the root. In D8 it is good practice to move the config directory outside of the public html even.

I think their may be too many factors to account for everyone's circumstances and I would think it might be best to push it onto the users to maintain a list of additional directories that might be needed during archive-dump. Drush could provide a flag for additional directories/files and even allow declaring these in the drush alias to ease usage. That is the approach that has my vote.

**Comment by weitzman** [comment]
I think that makes sense. I'm pretty sure we'd have to record what we did so that archive-restore could put the puzzle back together again.

**Comment by weitzman** [comment]
Unfortunately noone has stepped up to code this. I'm considering dropping archive commands from Drush 9 due to lack of apparent demand. I suppose folks have moved on.

**Comment by weitzman** [comment]
I've removed archive commands from master branch. Anyone wishing to work on this is encouraged to post here and I'll reopen the issue.

**Comment by alisonjo2786** [comment]
Oh I'm so sad :( don't blame you one bit, but I'm sad haha. 

The one thing I'll say is, it makes me want to commit my composer-created files to my repo, instead of leaving them out... I'm not positive or anything, but, that's where I'm feeling atm.  But anyway, just expressing bummed-out-ness (with an acknowledgement that I don't foresee helping fix the issue).

**Comment by brantwynn** [comment]
Might be a good idea to add a warning to 8.x and refer to this issue that the command will soon be deprecated in Drush 9?

**Comment by alisonjo2786** [comment]
+1 Good idea!

**Comment by weitzman** [comment]
We actually have `Drush::bootstrapManager->getComposerRoot()` now. So its possible to tar up the whole composer project. Someone needs to get motivated enough to do it.

**Comment by frederickjh** [comment]
Sorry to see archive-dump go, however I guess this is a good point to consider what is a good backup strategy for a composer base Drupal 8 installation.

**Comment by achikas** [comment]
drush8.x ard/arr works for me in a D8 composer environment. i use it in my docroot for fast backup and restore, as i did for years with D7.
are there strategies a folder level higher to trigger a file and db dump from composer?

**Comment by greg-1-anderson** [comment]
This was [mentioned above](https://github.com/drush-ops/drush/issues/1779#issuecomment-323447041). I don't think that method exists in Drush 8, though (but I didn't check).

**Comment by frederickjh** [comment]
With PHP task runners like Robo it is relatively easy to roll your own backup solution. My RoboFile.php for composer based install Drush 9 backups is only 67 lines. mostly because I wanted backup filenames that give me all the information about what got backed up.

**Comment by greg-1-anderson** [comment]
@frederickjh Nice script. Did you know that you can set Robo configuration values with a `robo.yml` file? See [Robo Configuration](https://robo.li/getting-started/#configuration) in the getting started guide.

I'll also point out that Drush commands essentially are Robo scripts, so the above example is a good start for an archive dump command. Some of the variables would need to be taken from the bootstrapped site, and you'd be good to go.

n.b. There's no taskDrushStack in Drush, regrettably.

**Comment by greg-1-anderson** [comment]
See also https://robo.li/tasks/Archive/

**Comment by frederickjh** [comment]
> n.b. There's no taskDrushStack in Drush, regrettably.

See [boedah/robo-drush](https://github.com/boedah/robo-drush) as that is where taskDrushStack comes from.

**Comment by greg-1-anderson** [comment]
Thx @frederickjh, I am aware of that project; I was just pointing out that it's not part of Drush at the moment.

**Comment by Ambient-Impact** [comment]
In case this helps anyone, I wrote [my own replacement for ```archive-dump```](https://github.com/Ambient-Impact/drupal-modules/blob/8.x-1.x/ambientimpact_core/src/Commands/AmbientImpactCommands.php), inspired by the RoboFile by @frederickjh and with some additional functionality mixed in to delete older back-ups. That file also contains other commands and is a work-in-progress, but that seems to work for me on Linux. At some point I'll probably try and implement a restore command similar to ```archive-restore```.

**Comment by fiasco** [comment]
Unless composer has an alternative, I think this capability is rather important for our Drupal ecosystem to remain free and fluid. Platforms like Acquia and Pantheon can support import and export of standards making it easier for their customers and prospects to move as they see fit.

Without a standard approach to shipping entire sites, it makes it more difficult for site owners to move sites without technical assistance.
