### ISSUE TITLE
Error upon drush site-install

### ISSUE THREAD

**Issue by amitaibu** [drush-ops/drush#1801]
I've updated Drush to latest 8-dev, but on `drush si` I'm getting the [following error](https://gist.github.com/amitaibu/e006d27e7b3e1ac90ab2). This happens in two different Mac computers.

**Comment by weitzman** [comment]
Thanks for the report.

1. Drush thinks that your .phar represents rc3 not 8-dev. I see this because the cache string it is using is at one point is 8.0.0-rc3-alias-path--85a349cae867db9b545d44d3c8f626e8. I just fixed the perms on files.drush.org/drush-unstable.phar so it is downloadable again.
1. Your log suggests that the only table that Drush tries to wipe during pre_site_install is cache_container. Is that table still present or was Drush successful in deleting it? I am guessing that Drush was unsuccesssful for some reason and then Drupal throws an install exception because it requires an empty DB. In this case run the DROP table user as same mysql user that Drush uses and see if the table drops for you.

Feel free to chat me in freenode's #drush to debug this. Or we can work here.

**Comment by amitaibu** [comment]
Hi @weitzman !

I have re-checked on my 2nd computer, and confirmed it's 8.x-dev. Here's the [log](https://gist.github.com/amitaibu/61c034abb7180d4f04da)

**Comment by weitzman** [comment]
That log suggests a problem in install_display_requirements(). I suspect
that you are not meeting some a filesystem requirement. You could put a
debug
around  /Library/WebServer/Documents/d8_dev/core/includes/install.core.inc:2173
and see what the value of $requirements is. There is an exception there in
the log.

**Comment by amitaibu** [comment]
> That log suggests a problem in install_display_requirements()

Here's what I see when installing manually:

![requirements_review__](https://cloud.githubusercontent.com/assets/125707/11345969/ecbac9a2-9222-11e5-9242-32c7c482cd63.jpg)

> You could put a debug around ...

Yeah, I've actually done it, but it didn't show much ;):

```bash
drush si -y
You are about to DROP all tables in your 'd8_dev' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                  [ok]
Array
(
    [0] => File system: 

Array
)
exception 'Drupal\Core\Installer\Exception\InstallerException' with message 'File system:   
```

**Comment by weitzman** [comment]
I can't tell if this is a problem in Drush, or in Drupal, or in your installation.

**Comment by amitaibu** [comment]
Yeah, since it happened on two computers I thought (=hoped) it was a more generic problem. I guess I'll have to debug ;)

**Comment by amitaibu** [comment]
I was able to work around the problem by manually `rm sites/default/files && mkdir sites/default/files` - seems there files inside that folder that the non-sudo user didn't have access to.

**Comment by weitzman** [comment]
drush doesn't write there, but drupal does and will save files as whatever user is running the drush command.
