### ISSUE TITLE
Consistent behavior/error if missing settings.php

### ISSUE THREAD

**Issue by bensheldon** [drush-ops/drush#1845]
When trying to run most Drush commands and a `settings.php` file does not exist, Drush prints out a helpful error message:

`"Could not find a Drupal settings.php file at !file."`

https://github.com/drush-ops/drush/blob/3657fa99a9c47e4684786ccac71270b2db27615e/lib/Drush/Boot/DrupalBoot.php#L395

But when performing `drush cc`, a different (and arguably less helpful) error message is printed:

`"No Drupal site found, only 'drush' cache was cleared."`

https://github.com/drush-ops/drush/blob/3657fa99a9c47e4684786ccac71270b2db27615e/commands/core/cache.drush.inc#L146

I think it would improve the Drush experience to have consistent behavior in these circumstances.

**Comment by greg-1-anderson** [comment]
Perhaps we should make `drush cc` enforce a minimum bootstrap unless it is explicitly a `drush cc drush`.  That would make the error message consistent.  A lot of people have been confused by the `only 'drush cache was cleared.` message.  A few times I've personally been bit by not reading, since this message is not an error, it's not always noticeable that the cache did not actually clear if the site you were intending to operate on was not in fact selected.

**Comment by greg-1-anderson** [comment]
Hm, would this be considered an API change, or could we slip it in as a "bug fix"?  Hopefully scripts don't rely on `drush cc` being a `drush cc drush`, but there is that small chance of breakage if they do.  This would have to be a 9.x change if that was a concern.

**Comment by greg-1-anderson** [comment]
I tried a quick fix, like this:
```
index b95f1d7..ee3b7eb 100644
--- a/commands/core/cache.drush.inc
+++ b/commands/core/cache.drush.inc
@@ -140,14 +140,16 @@ function drush_cache_command_clear($type = NULL) {
       return drush_user_abort();
     }
   }
+  // Require a full bootstrap unless we are just clearing the Drush cache.
+  // This will give more consistent error messages when a site cannot be found.
+  if ($type != 'drush') {
+    if (!drush_bootstrap(DRUSH_BOOTSTRAP_DRUPAL_FULL)) {
+      return FALSE;
+    }
+  }
   // Do it.
   drush_op($types[$type]);
-  if ($type == 'all' && !drush_has_boostrapped(DRUSH_BOOTSTRAP_DRUPAL_FULL)) {
-    drush_log(dt("No Drupal site found, only 'drush' cache was cleared."), LogLevel::WARNING);
-  }
-  else {
-    drush_log(dt("'!name' cache was cleared.", array('!name' => $type)), LogLevel::SUCCESS);
-  }
+  drush_log(dt("'!name' cache was cleared.", array('!name' => $type)), LogLevel::SUCCESS);
 }
```
Unfortunately, even though the `drush_bootstrap()` did, in fact, cause the above-mentioned bootstrap error line to run (`return drush_bootstrap_error('DRUPAL_SITE_SETTINGS_NOT_FOUND', dt("Could not find a Drupal settings.php file at !file.",
         array('!file' => $conf_file)));`), bootstrap errors are not reported in this circumstance, and instead, Drush says `Drush command terminated abnormally due to an unrecoverable error.`.

So, we'd have to make `drush cc drush` a separate command, or fix handling of bootstrap errors after command dispatch in order to proceed here.

**Comment by weitzman** [comment]
In your example code I think you could do

```
if ($type != 'drush' && !drush_has_boostrapped(DRUSH_BOOTSTRAP_DRUPAL_FULL)) {
  return drush_set_error(...);
}
```

**Comment by greg-1-anderson** [comment]
Yes, probably; that's a good idea. I don't have time to look at it now, but there's probably a function we could call here that would collect and report the exact bootstrap errors.

**Comment by greg-1-anderson** [comment]
Should have done this in 2015; I don't think that we'll be changing Drush 8 bootstrapping at this point though.
