### ISSUE TITLE
drush sql-sync fails with --structure-tables-list

### ISSUE THREAD

**Issue by krlucas** [drush-ops/drush#1858]
Recently upgraded my local global drush to drush 8. Now this command fails 

drush sql-sync -y @XXXX.test @XXXX.local --structure-tables-list='cache,cache_*,history,sessions,watchdog'

> rsync: --structure-tables-list=cache,cache_*,history,sessions,watchdog: unknown option
> rsync error: syntax or usage error (code 1) at /SourceCache/rsync/rsync-45/rsync/main.c(1333) [client=2.6.9]

The remote alias points to Acquia Cloud FWIW.

The same command still works with drush 7.

**Comment by weitzman** [comment]
I did a quick test and I am also seeing the --structure-tables-option show up at the end of the rsync call (see below) which is invalid when using strict commands like core-rsync. I introduced the problem in #1803. Looks like there is no way when using drush_invoke_process() to encourage Drush to put options before the command arguments instead of after. ping @greg-1-anderson .

I'm going to implement a different solution in the meanwhile.

`
Simulating backend invoke: /usr/local/bin/php /Users/moshe.weitzman/c/h/drush/drush.php --php=/usr/local/bin/php  --backend=2 --verbose --strict=0 --yes --root=/Users/moshe.weitzman/htd/d7 --uri=http://mm/d7  core-rsync '@buytaert.test:/home/buytaert/drush-backups/buytaertstg/20151214185739/buytaertstg_20151214_185740.sql.gz' '@self:/Users/moshe.weitzman/tmp/buytaertstg_20151214_185740.sql.gz'   --structure-tables-list='cache,cache_*,history,sessions,watchdog' --remove-source-files --exclude-paths=css:js:ctools:tmp 2>&1
`

**Comment by greg-1-anderson** [comment]
backend_invoke makes some attempt to order options, but I think the rule it uses is something like "global options before the command, command-specific options go after the command."  This should be updated to all recognized options before the command, everything else after the command for commands with strict option handling.
