### ISSUE TITLE
PHP_INI not being read

### ISSUE THREAD

**Issue by cisaksen** [drush-ops/drush#1859]
drush 8.0.1 doesn't seem to see the PHP_INI variable. I have confirmed that it is visible and set to our correct location. /etc/php5/fpm/php.ini

drush 8.0.1 will not see php.ini in any location other than /etc/php5/cli/php.ini I even tried to set the PHP_INI in the /home/drushuser/.drush/drush.bashrc file, that didn't work either.

To work around this I just copied the one in fpm to cli. If I didn't do this the PHP configuration was blank when you run drush status.

**Comment by weitzman** [comment]
This is by design if you use the Phar installation method (the default). We no longer run the drush finder in this setup so its too late to change php's ini configuration.

1.  The workaround you mention seems reasonable in your case. A symlink would work too if you the ini files to be identical always.
1. A different to call drush.phar (or drush) like so: `php -d foo=bar drush.phar --php-options=foo=bar`. [This is documented in a bullet in the install docs](http://docs.drush.org/en/master/install/).
