### ISSUE TITLE
DrushBatchContext brakes batch processes if batch operation callback uses typehint for $context

### ISSUE THREAD

**Issue by tikaszvince** [drush-ops/drush#1930]
From Drupal 8.0.2 [`locale_translation_batch_status_check`](
http://cgit.drupalcode.org/drupal/tree/core/modules/locale/locale.batch.inc?h=8.0.2#n39) uses typehint for `$context` param.

Drush 8.0.2 passes a [`DrushBatchContext`](https://github.com/drush-ops/drush/blob/8.0.2/commands/core/drupal/batch.inc#L150) instance as `$context` param.

Even if `DrushBatchContext` extends `ArrayObject` the `array` typehint causes a fatal error:
`Argument 4 passed to locale_translation_batch_status_check() must be of the type array, object given locale.batch.inc:39`

**Comment by mortenson** [comment]
Seeing the same thing on my side.

**Comment by tstoeckler** [comment]
I'm seeing this as well with the relatively new `drush locale-check`. Since I was sure that this had worked at some point I bisected this down to a0e1f70c4e5b1c897f2952624da93c07f1098ca7. So maybe an error was being thrown the whole time and weirdly it was being silenced and now is being exposed. Anyway, would be cool if someone could verify that when doing `git checkout a0e1f70c4e5b1c897f2952624da93c07f1098ca7^` it works and with a `git checkout a0e1f70c4e5b1c897f2952624da93c07f1098ca7` it doesn't.

I grok neither that commit nor the DrushBatchContext ATM so I can't be of any more help.

**Comment by greg-1-anderson** [comment]
I think this should be fixed in [drush language](https://www.drupal.org/project/drush_language).

Either that, and give up and remove the above-mentioned PR -- which is really the more correct way to deal with recoverable errors.  Unless folks are used to writing code in an environment that ignores these, and Drush keeps breaking as a result.

**Comment by mortenson** [comment]
I don't use the Drush Language Commands and still ran into this error, so fixing it there would not help me.

**Comment by greg-1-anderson** [comment]
@mortenson This issue is informing you that there is an actual coding error in some other software that you are running -- it is not a problem with Drush. The issue revolves around the tension between type-checking, and the question of whether PHP should be ran in a mode that catches type errors, or silently ignores them.  The previous decision was that Drush should enforce problems with mismatched types, and software with this problem should be fixed.

In the long run, type checking will help find and prevent bugs in PHP code. Pragmatically speaking, though, end users probably do not care as much about technical correctness so much as they desire their software to just work as they expect it to, and as it used to do. At the moment, I am in favor of fixing problems rather than removing the check, but we'll see how much trouble that causes folks.

I'm not sure that php7 allows you to run in this mode, though, so removing this check might simply be delaying the inevitable.

**Comment by mortenson** [comment]
I thought the original issue summary made it clear that this was a Drush error, not a problem with "other software" that I'm running. 

In Drupal core typehints aren't always used for the `$context` parameter, but are in locale_translation_batch_status_check, locale_translate_batch_import, locale_translate_batch_import, locale_config_batch_refresh_name, and _node_mass_update_batch_process. So if I understand correctly passing DrushBatchContext to any of these would result in the same error.

**Comment by greg-1-anderson** [comment]
@mortenson Are you saying that Drupal core cannot run with typehints? What about php7?

**Comment by mortenson** [comment]
I'm not suggesting we revert the commit mentioned in this issue, sorry if that was implied somewhere. Based on reading the original issue summary, it sounds like we're passing `DrushBatchContext` as the `$context` parameter to batch callbacks. For batch callbacks that use typehinting and expect `array &$context`, errors will be thrown when using Drush to execute those batches.

**Comment by greg-1-anderson** [comment]
Oh, so the point of the OP is that we should wrap DrushBatchContext in an `array`?  Sorry, I misunderstood that before.

**Comment by tikaszvince** [comment]
I do not understand why PHP7 mentioned before. While [Drupal requirements](https://www.drupal.org/requirements) says it needs PHP 5.5.9 and [Drush docs](http://docs.drush.org/en/master/install/#drupal-compatibility) says Drush needs PHP 5.4.5+ (!) it should work at least PHP 5.4.5 version.

Until these PHP versions says `DrushBatchContext` is not passing the type hint check when a function argument has to be an `array` (as the [`locale_translation_batch_status_check`](http://cgit.drupalcode.org/drupal/tree/core/modules/locale/locale.batch.inc?h=8.0.2#n39) does) `_drush_batch_worker` should pass an `array` and not an extended `ArrayObject`.

After Drush 8 [contains](https://github.com/drush-ops/drush/pull/1818) `locale-check` and `local-update` commands which commands call `locale_translation_batch_status_check` Drupal core functions, I do not think the [drush language](https://www.drupal.org/project/drush_language) project has any task to fix this error.

At this point I do not think wrapping `DrushBatchContext` instance into a new `array()` can solve this error. I think the correct solution here is replacing `DrushBatchContext` with a traditional array.

Alternative solution should be changing Drupal core and remove `array` type hint from the previously mentioned functions, but I think in this relation Drush has to adapt to Drupal core.

**Comment by greg-1-anderson** [comment]
@tikaszvince I misunderstood the original report, but I understand now. You are correct that wrapping DrushBatchContext in an array does not help, or at least is no better than just getting rid of the object entirely and using an ordinary array.  However, if we do that, then Drush loses the ability to monitor the batch process.

Is there a supported way for Drush to do this (receive callbacks through the execution of the batch job) in Drupal 8?  Suggestions here welcome.

**Comment by tstoeckler** [comment]
Opened https://www.drupal.org/node/2664290 in Drupal core for this. Of course I cannot foresee how that will be received, but I think that would be easiest if upstream would just remove the typehints.

**Comment by jonhattan** [comment]
Yo! here's the culprit of DrushBatchContext. It doesn't seem Drupal 8's batch API has significant changes over previous versions. So no, there's no way to propagate the message back in any sort of callback.

If php supported the  overloading of `=` operator, we could implement a _StringObject_ class and use it for the `message` key in a regular `$context` array, but it is not possible in php.

Our options are:
 1. wait for https://www.drupal.org/node/2664290 
 2. remove DrushBatchContext
 3. Add a switch to `drush_error_handler()` to ignore `E_RECOVERABLE_ERROR` (i.e. `drush_get_context('IGNORE_E_RECOVERABLE_ERROR')`)
 4. In the long term, add an event to batch API to notify when a new message is available, probably for Drupal 9

**Comment by tstoeckler** [comment]
So the upstream issue has already been committed to 8.2 and 8.1 in the meantime. I've rerolled it for 8.0 and hope it will get in there too. (Could use a review, BTW)

**Comment by tstoeckler** [comment]
Has been committed to 8.0 by now. So as soon as the next 8.0 release comes out this problem should magically go away...
