### ISSUE TITLE
Possible PHP 5.5 minimum requirement

### ISSUE THREAD

**Issue by roseanngabon** [drush-ops/drush#1946]
I want to install drush to my Godaddy Linux shared hosting. I've carefully follow instruction here https://ph.godaddy.com/help/how-to-install-drush-on-cpanel-shared-hosting-12396 but there is an error message when I tried to do  `php composer.phar install`. 
This is the error message:
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
```
Problem 1
- Installation request for symfony/console v3.0.1 -> satisfiable by symfony/console[v3.0.1].
- symfony/console v3.0.1 requires php >=5.5.9 -> your PHP version (5.4.16) or value of "config.platform.php" in composer.json does not satisfy that requirement.
Problem 2
- symfony/console v3.0.1 requires php >=5.5.9 -> your PHP version (5.4.16) or value of "config.platform.php" in composer.json does not satisfy that requirement.
- psy/psysh v0.6.1 requires symfony/console ~2.3.10|^2.4.2|~3.0 -> satisfiable by symfony/console[v3.0.1].
- Installation request for psy/psysh v0.6.1 -> satisfiable by psy/psysh[v0.6.1].
```
I tried to uninstall, reinstalled, use this method http://drupal.stackexchange.com/questions/105828/undefined-error-0-or-unable-to-load-autoload-php-drush-now-requires-composer... but It still won't work. Please help

**Comment by weitzman** [comment]
The best fix is for you to use PHP 5.5 or higher instead of PHP 5.4 which is very old. This may or may not help you at the command line - https://www.godaddy.com/help/view-or-change-your-php-version-3937

I will say that out current Drush branch is supposed to work with 5.4 but perhaps we need to lock a dependency in order to make that happen. I'm not sure if Composer tries to pull down packages that do not exceed your current version of PHP.
