### ISSUE TITLE
multiple drush commands in a windows batch file

### ISSUE THREAD

**Issue by DocDJ** [drush-ops/drush#2205]
I apologize in advance if this is not the right place for this posting. If it isn't, please let me know where it belongs.
I wrote a simple Windows file that individually enables Drupal 8 modules (because (a) I needed to find out which ones were failing and (b) the Drupal Extend panel was failing if I tried to enable more than 1 at a time). When I run the batch file, it performs the 1st drush command it finds, then exits. Is there a way to get it to continue and process the next drush command? There is no code of any kind in the batch file other than the drush commands. I do NOT care that the performance will be very slow. I only expect to have to do it when re-building my system (which is happening about 5 times a day while migrating to Drupal 8.)

**Comment by isangil** [comment]
yup, i see this problem too.

In Linux this is not an issue, a (bash) script can call drush as much as it needs and move on, but there is some return code or something in windows that forces the (cmd) script to end. 

I know its been a year + since original post.

**Comment by isangil** [comment]
just googled it some more.  found this and tested successfully. https://stackoverflow.com/questions/7320074/batch-file-stops-running-after-the-first-command

basically, what you have to do is instead of invoking drush in your script as 

drush 

invoke it as 

call drush

then you can have multiple drush commands within one script.
