### ISSUE TITLE
Can not install - proc_open(): fork failed

### ISSUE THREAD

**Issue by eduoda** [drush-ops/drush#2217]
I tried to install following this: http://docs.drush.org/en/master/install/

When I run `php drush core-status` several processes were started, they can be seen with ps:
PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
12512  1.0  0.0 316948 14624 pts/0    S+   05:27   0:00 php drush core-status
12514  1.0  0.0 316948 14608 pts/0    S+   05:27   0:00 php /.../drush core-status
...
12544  1.0  0.0 316884 13692 pts/0    R+   05:27   0:00 php /.../drush core-status

After a few seconds I got:
Warning: proc_open(): fork failed - Resource temporarily unavailable in phar:///.../drush/includes/startup.inc on line 370
Warning: proc_get_status() expects parameter 1 to be resource, boolean given in phar:///.../drush/includes/startup.inc on line 371
Warning: proc_close() expects parameter 1 to be resource, boolean given in phar:///.../drush/includes/startup.inc on line 372

I've tried with several php versions, including: PHP 7.0.7 and  PHP 5.6.22

**Comment by adam-devapp** [comment]
Same. Are you using a control panel system, jailed shell, suhosin?

**Comment by dylantack** [comment]
I can reproduce this with Drush 8.1.3, on MacOS 10.11.5 (PHP 5.5.34), and also very similar behavior on CentOS 6.6 (PHP 5.5.35).  I don't have any jails ore anything else I'd consider unusual in the environment.  Drush is creating a "fork bomb", creating hundreds of copies of itself.

git-bisect points to https://github.com/drush-ops/drush/commit/66b2eef5d213e460daf4e07149c11519b6fffe99 as the origin of the bug.

FWIW, the latest version that's free of the bug is 8.0.2, so if you can use that version that might be an option.

![drush_fork_bomb](https://cloud.githubusercontent.com/assets/106996/17041599/e8c71e08-4f5b-11e6-9ce2-b3c908f848e1.png)

**Comment by dylantack** [comment]
Here's an XDebug trace:
[drush_phar_trace.txt](https://github.com/drush-ops/drush/files/377414/drush_phar_trace.txt)

**Comment by theodorosploumis** [comment]
I would like to add here a strange solution I found. 
I had the same issue only when **drush** phar was not inside a folder. When added it into a folder it worked. I am not sure to say what changed while being inside a folder.

**Comment by dylantack** [comment]
Interesting – the fork bomb seems to only occur when the current working directory is the same as the drush phar executable.

**Comment by eduoda** [comment]
@theodorosploumis and @dylantack same here. Everything goes fine if I run drush from another directory.

**Comment by florianbeer** [comment]
I experience the same problem. As soon as I move `drush` to `/usr/local/bin` I can execute the code from anywhere except that directory.

System is Debian 8.4 Jessie with PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07)
Drush versions affected 8.0.3 - 8.1.3

**Comment by weitzman** [comment]
This was just fixed in b093e33. Will be released soon for 8.x and 9.x
