### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by a1exus** [drush-ops/drush#2268]
I'm getting following error while trying to update drush:

```
$ drush version
 Drush Version   :  9.0-dev 

$ composer global update
Changed current directory to /home/alexus/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drush/drush dev-master requires codegyre/robo ~1.0.0-beta1 -> satisfiable by codegyre/robo[1.0.0-beta1] but these conflict with your requirements or minimum-stability.
    - drush/drush dev-master requires codegyre/robo ~1.0.0-beta1 -> satisfiable by codegyre/robo[1.0.0-beta1] but these conflict with your requirements or minimum-stability.
    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].

$ 
```

Please advise.

**Comment by greg-1-anderson** [comment]
I recommend against using Composer to install the dev version of Drush, because the dev version of Drush sometimes uses dev versions of other components.  It is possible to make this work, but it requires more advanced Composer use, and I don't think that we want to support that here.

Instead, install the stable version of Drush (see related issue #2272), or, if you really do want the dev version of Drush, then either use the phar, or run `git clone` followed by `composer install`.

**Comment by greg-1-anderson** [comment]
This has been resolved.
