### ISSUE TITLE
Allow removing a module's content entities prior to module uninstallation

### ISSUE THREAD

**Issue by powpow12** [drush-ops/drush#2334]
This is a follow up to the core fix in 8.2.  [Allow removing a module's content entities prior to module uninstallation](https://www.drupal.org/node/2688945)

Basically, if you try to uninstall a module via drush, (`drush pmu module_name`), and the module has content created it will fail ungracefully.  

![screen shot 2016-09-01 at 3 58 39 pm](https://cloud.githubusercontent.com/assets/3721535/18184163/bb2c9894-7065-11e6-9b40-ddbd0891bf62.png)

screenshot provided by drupal user: jrockowitz.

**Comment by weitzman** [comment]
We don't currently support creating or deleting content. Those are pre-requisites. All in all, I dont think core Drush needs to handle this (edge) case. Note that devel-generate in devel module provides basic delete-all functionality.

Thanks for the screenshot. I think the error message is clean. Its long, because you have backtrace or xdebug enabled.
