### ISSUE TITLE
Support utf8mb4 on drush site-install

### ISSUE THREAD

**Issue by nvaken** [drush-ops/drush#2352]
Since Drupal 7.50 it's possible to [setup Drupal with UTF8MB4 support](https://www.drupal.org/node/2754539). 

I would love to see support for UTF8MB4 installs. Would it be possible to add a `--utf8mb4` flag to make sure the site is being installed with the right settings? 
## Example command

```
drush site-install --db-url=mysql://root:pass@localhost:port/dbname --utf8mb4=true
```
### Test the database service settings (out of scope?)

Possibly out of scope, but a nice additional step might be to check if the database is set up properly to allow UTF8MB4. In that case, Drush should check for the following MySQL settings:

```
[mysqld]
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=true
```
### Settings.php

I think the only thing on site installation is that it will need to setup the correct settings for the database in `settings.php`:

```
$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => 'databasename',
  'username' => 'username',
  'password' => 'password',
  'host' => 'localhost',
  'charset' => 'utf8mb4',     // Add these automatically
  'collation' => 'utf8mb4_general_ci',     // Add these automatically
);
```
### Setup database with default utf8mb4_general_ci collation

Make sure the database has the correct collation selected as default.

```
ALTER DATABASE database_name CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
```

**Comment by weitzman** [comment]
Whats needed is for someone to research what parameters should be added when we call install_drupal() such Drupal writes the proper collation and charset when it appends to settings.php. One a quick glance, I dont see a way to pass that to install_drupal() yet.

**Comment by gitressa** [comment]
It would be really awesome to be able to define another collation as well, like utf8mb4_danish_ci.

**Comment by ahwebd** [comment]
Would be very helpful to specify the desired character set and collation when creating the db,

as a temporary solution I'm hacking file "drush/lib/Drush/Sql/Sqlmysql.php", I changed line 88:

`    $sql[] = sprintf('CREATE DATABASE %s /*!40100 DEFAULT CHARACTER SET utf8 */;', $dbname);
`

`    $sql[] = sprintf('CREATE DATABASE %s /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;', $dbname);
`

**Comment by rwalkerands** [comment]
The simple patch by @ahwebd works. Any chance to get it incorporated?

**Comment by rwalkerands** [comment]
I acknowledge that the patch/pull request doesn't alter what goes into `settings.php`. I don't have the Drupal internals or drush expertise to figure that out. (This is as far as I got: working backwards from the end, it seems that the database config is appended to `settings.php` by `core/lib/Drupal/Core/Installer/Form/SiteSettingsForm.php` `submitForm()`. The form is instantiated/specified as `'install_settings_form'`, and the values for that form are populated by drush's `SiteInstallCommands.php`. So it may be sufficient to enhance drush's `SqlBase.php` so that the desired key/value pairs end up in the return value of `getDbSpec()`.)


But those who need something now (i.e., such as myself) can use composer-patches with the pull request:

```
    "extra": {
        "patches": {
            "drush/drush": {
                "Support utf8mb4 on drush site-install": "https://github.com/drush-ops/drush/pull/4810.patch"
            },
...
```

**Comment by rwalkerands** [comment]
So, I did some further investigation.

Hmm, is it/why is it necessary to add the charset and collation settings to `settings.php`?

But in case it is so, it seems it's necessary for these options to be "known" to the core.

Attempt 1 (just to see if this has any effect at all):

```
diff --git a/msnd4-copy/vendor/drush/drush/src/Sql/SqlBase.php b/msnd4-test-drush-mods/vendor/drush/drush/src/Sql/SqlBase.php
index 48f67b4..29dfce9 100644
--- a/msnd4-copy/vendor/drush/drush/src/Sql/SqlBase.php
+++ b/msnd4-test-drush-mods/vendor/drush/drush/src/Sql/SqlBase.php
@@ -124,7 +124,10 @@ class SqlBase implements ConfigAwareInterface
      */
     public function getDbSpec()
     {
-        return $this->dbSpec;
+        $spec = $this->dbSpec;
+        $spec['charset'] = 'utf8mb4';
+        $spec['collation'] = 'utf8mb4_unicode_ci';
+        return $spec;
     }

     /**
```

It turns out that this does nothing; the charset and collation values don't end up in `settings.php`.

Attempt 2: make the above change, and also this one (to `getFormOptions()`), which defines the charset and collation settings as "advanced options" of the database configuration:
```
diff --git a/msnd4-copy/web/core/lib/Drupal/Core/Database/Driver/mysql/Install/Tasks.php b/msnd4-test-drush-mods/web/core/lib/Drupal/Core/Database/Driver/mysql/Install/Tasks.php
index dfac015..b6713a3 100644
--- a/msnd4-copy/web/core/lib/Drupal/Core/Database/Driver/mysql/Install/Tasks.php
+++ b/msnd4-test-drush-mods/web/core/lib/Drupal/Core/Database/Driver/mysql/Install/Tasks.php
@@ -174,7 +174,24 @@ class Tasks extends InstallTasks {
     if (empty($form['advanced_options']['port']['#default_value'])) {
       $form['advanced_options']['port']['#default_value'] = '3306';
     }
-
+    $form['advanced_options']['charset'] = [
+      '#type' => 'textfield',
+      '#title' => t('Charset'),
+      '#default_value' => '', // 'utf8mb4',
+      '#size' => 45,
+      // Charset names can be 255 characters long.
+      '#maxlength' => 255,
+      // '#required' => FALSE,
+    ];
+    $form['advanced_options']['collation'] = [
+      '#type' => 'textfield',
+      '#title' => t('Collation'),
+      '#default_value' => '', // 'utf8mb4_unicode_ci',
+      '#size' => 45,
+      // Collation names can be 255 characters long.
+      '#maxlength' => 255,
+      // '#required' => FALSE,
+    ];
     return $form;
   }

```

Now the charset and collation values (returned from `getDbSpec()`) end up in `settings.php` as desired.

**Comment by weitzman** [comment]
Sounds like a drupal core patch is needed before drush can improve this. Lets reopen this issue if that core patch ever happens. Until then, edit settings.php outside of drush.
