### ISSUE TITLE
Change site alias files to .yml (YAML) and add alter hook

### ISSUE THREAD

**Issue by TravisCarden** [drush-ops/drush#247]
Is there any way to centrally, dynamically alter defined site aliases? I'm thinking of something along the lines of a ``hook_alias_alter()``. A number of my alias.drushrc.php files are auto-generated by my Drupal hosting provider, and I want to augment them with a few values like "remote-user" and "ssh-options", but I want to avoid losing my changes every time I update them from the host. Is there a good, Drupally way to accomplish that at present?

**Comment by greg-1-anderson** [comment]
I think it would be worthwhile to have the ability to configure alias files from the commandline.  I think, however, that we should [model these commands on git configuration](https://help.github.com/articles/set-up-git/), and use "." instead of "/" for the path separator.  It would also be helpful to support the --global flag, like git, to specify that the Drush global location for aliases should be used instead of ~/.drush.

It would be cool if this were a PR; I think it should go in.

**Comment by weitzman** [comment]
There is a sitealias_alter hook now. 

Lets deprecate this issue in favor of #1609
