### ISSUE TITLE
Drush 8.1.8 is not compatible with Symfony 3.1

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#2474]
See https://www.drupal.org/node/2712647#comment-11805966 which outlines `cache-rebuild` is broken. Change record is https://www.drupal.org/node/2743809

**Comment by anavarre** [comment]
Looks like at least one of the problems is with the implementation of Symfony Console's `hasParameterOption()` - See https://github.com/drush-ops/drush/blob/ad9db2f48e3504d793efc8e8970f7cfa878b05ef/lib/Drush/Command/DrushInputAdapter.php#L61

With Symfony Console 3.1 it expects `hasParameterOption($values, $onlyParams = false);`

**Comment by alexpott** [comment]
So I can get site-install working by upgrading to Symfony console to ~3.1 but I have to bump drush's minimum PHP requirements.

**Comment by alexpott** [comment]
This fixes stuff against Drush 8.x branch... https://github.com/drush-ops/drush/pull/2476

**Comment by alexpott** [comment]
https://github.com/drush-ops/drush/pull/2477 fixes against Drush master

**Comment by weitzman** [comment]
Lets discuss in the PRs

**Comment by BR0kEN-** [comment]
Again (`8.4.0-dev`)?

```
drush  si pp --db-url=mysql://root:root@127.0.0.1:3306/drupal_remo_default --uri=https://remo.dev -y
PHP Fatal error:  Declaration of Drush\Command\DrushInputAdapter::hasParameterOption($values) must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /usr/share/composer/vendor/drush/drush/lib/Drush/Command/DrushInputAdapter.php on line 27
PHP Stack trace:
PHP   1. {main}() /usr/share/composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /usr/share/composer/vendor/drush/drush/drush.php:12
PHP   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /usr/share/composer/vendor/drush/drush/includes/preflight.inc:66
PHP   4. drush_dispatch() /usr/share/composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:67
PHP   5. drush_command() /usr/share/composer/vendor/drush/drush/includes/command.inc:199
PHP   6. _drush_invoke_hooks() /usr/share/composer/vendor/drush/drush/includes/command.inc:231
PHP   7. spl_autoload_call() /usr/share/composer/vendor/drush/drush/includes/command.inc:353
PHP   8. Composer\Autoload\ClassLoader->loadClass() /usr/share/composer/vendor/drush/drush/includes/command.inc:353
PHP   9. Composer\Autoload\includeFile() /usr/share/composer/vendor/composer/ClassLoader.php:322
PHP  10. include() /usr/share/composer/vendor/composer/ClassLoader.php:444
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                               [error]
Error: Declaration of Drush\Command\DrushInputAdapter::hasParameterOption($values) must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values,
$onlyParams = false) in /usr/share/composer/vendor/drush/drush/lib/Drush/Command/DrushInputAdapter.php, line 27
```

Okay, I've installed Drush `9.x`:

```
drush --version
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 2097152) (tried to allocate 12288 bytes) in /usr/share/composer/vendor/drush/drush/includes/backend.inc on line 1293
PHP Stack trace:
PHP   1. {main}() /usr/share/composer/vendor/drush/drush/drush:0
PHP   2. require() /usr/share/composer/vendor/drush/drush/drush:4
PHP   3. drush_main() /usr/share/composer/vendor/drush/drush/drush.php:10
PHP   4. drush_preflight_prepare() /usr/share/composer/vendor/drush/drush/includes/preflight.inc:38
```

Ubuntu 16.04 LTS.

**Comment by BR0kEN-** [comment]
Why Drush 8.1.11 tries to use `/var/www/docroot/vendor/symfony/console/Input/InputInterface.php` instead of `/usr/share/composer/vendor/symfony/console/Input/InputInterface.php`?

**Comment by donquixote** [comment]
I get the same warning in D7 with `drush composer-manager update`.

Scenario:
- Composer 1.5.2 installed in `/usr/local/bin/composer`.
- Global composer libraries in `~/.composer/vendor/`.
- Drush 8.1.15 installed with Composer in `~/.composer/vendor/drush/`.
- Drush's own Composer libraries in `~/.drush/composer/vendor/`.
- Drupal 7 with composer_manager module.
- Drupal-specific composer libraries in `sites/all/vendor/` - but this seems to be irrelevant.

This gives me two versions of symfony/console:
- `~/.composer/vendor/symfony/console/`: version `v3.3.10`.
- `~/.drush/composer/vendor/symfony/console/`: version `v2.7.4`.

Note: My sites/all/vendor currently has no symfony components.

When running `drush composer-manager update`, these two conflicting files are included:
- `~/.drush/composer/vendor/symfony/console/Input/ArgvInput.php`
- `~/.composer/vendor/symfony/console/Input/InputInterface.php`

I was able to fix this with `composer global require "symfony/console=~2.8"`, which downgrades the symfony/console in `~/.composer/vendor/symfony/console/`.

Maybe this specific problem was due to composer_manager.

**Comment by greg-1-anderson** [comment]
Do not use `composer global require` to install Drush. Try [cgr](https://github.com/consolidation/cgr) instead.

**Comment by donquixote** [comment]
> Do not use composer global require to install Drush. Try cgr instead.

Oh wow, first time I hear about it. Thanks!
The docs still say `composer global require`, see http://docs.drush.org/en/8.x/install-alternative/
