### ISSUE TITLE
Improve table wrapping

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2603]
We have unfortunate table wrapping. Examples:

- [ ] drush status (try a bootstrapped site if available)
- [ ] drush help site-install

**Comment by ccharlton** [comment]
And output for `drush`/`drush help` that lists all available commands.

**Comment by weitzman** [comment]
![terminal](https://cloud.githubusercontent.com/assets/7740/25601953/d619c412-2ebd-11e7-8f0b-b2c9484032fe.gif)

My wish for long cells is that they add a new row and the wrapped text starts in the proper cell, not the leftmost cell. The red boxes in this screenshot should be in column 2, not in column 1.

**Comment by weitzman** [comment]
![terminal_ _-bash_ _122x49](https://cloud.githubusercontent.com/assets/7740/25626570/f184c2a4-2f2d-11e7-8acb-c1f13c866465.gif)

**Comment by greg-1-anderson** [comment]
Yes, and the strange thing about the status example ^^ is that there are enough unused characters on each row that the algorithm could have made both columns full-width. This use case, at least, should be easy to fix.

**Comment by ccharlton** [comment]
(This is seriously my current favorite Drush ticket.)

**Comment by greg-1-anderson** [comment]
tl/dnr: Wrapping is hard.

I have a new PR (https://github.com/consolidation/output-formatters/pull/55) that improves wrapping considerably. It fixes the narrow column width in the first column in the `drush status` example, at the expense of reducing the last column to a single character in width (!).

The problem with the current algorithm stems mostly from oddities with the way that PropertyList data types are handled. RowsOfFields seem to be wrapping well, but the wordwrap algorithm is confused about what the headers are in the PropertyList case. They should be `Key` and `Value`, or equivalent (or empty), but instead the entries from the first column are being used as the headers. This is more rational than it sounds -- these items would in fact be the header if the table were laid out horizontally. (PropertyList is essentially a RowsOfFields with a single row, rotated vertically.) There are also problems when the column keys are numeric, as they are in `drush status`. This is probably because various PHP array operations renumber array indexes, which never happens when the keys are strings. Not sure what to do about that -- I don't think I can prohibit numeric column keys. I'll probably have to remap them to strings in the word wrapper.

Oh, and the thing about the output of `drush help` is that it seems that it is not being sent through the word wrapper at all. Not sure why that is.

**Comment by greg-1-anderson** [comment]
Pro tip: `min()` has vastly different effects than `max()` when used in a mathematical context. Use of the correct operator is strongly recommended.

Avoiding unintended index renumbering in php arrays is also very helpful to correct operation of this word wrapping class. See the referenced PR.

**Comment by weitzman** [comment]
Fixed in #2741 and follow-ups
