### ISSUE TITLE
Is there a reason why symfony/var-dumper is locked at ~2.7?

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#2720]
I noticed https://github.com/drush-ops/drush/blob/641b2a13eb51f8badeb47d474a8e21288eeb66b8/composer.json#L41 shows `"symfony/var-dumper": "~2.7",` which can conflict with other requirements when using a global composer.json file.

The question is thus simple: is there any strong reason not to switch to a newer version?

**Comment by Chi-teck** [comment]
I guess it is for the purpose of consistency. Drupal core depends on Symfony 2 components.

https://github.com/hechoendrupal/drupal-console/issues/3249

**Comment by anavarre** [comment]
You're referring to a Drupal Console, but it happens that Drupal Console does support a newer `symfony/var-dumper` because it's not pinned to `~2.7` as it accepts `~2.7|~3.0` 

As to my question, it's also related to https://www.drupal.org/node/2712647 which is going to happen very soon.

**Comment by Chi-teck** [comment]
Right. With some trick the Var dumper can be shared with Drupal console. I supposed you have the same problem because you did not ask about other Symfony components pinned to 2.7 (yaml, console, event-dispatcher, etc).

My understanding is that all Symfony dependencies will be updated right after _#2712647_ get committed.

**Comment by anavarre** [comment]
Looks like #2724 is taking care of this.
