### ISSUE TITLE
sql-sanitize should clear all state objects

### ISSUE THREAD

**Issue by aweingarten** [drush-ops/drush#2798]
h3. Business Requirements
[] As a user I want to prevent state information from being moved between environments per the Drupal core state specs.

> You will never want to deploy it between environments.
You can reset a system, losing all state. Its configuration remains.
So, use State API to store transient information, that is okay to lose after a reset. Think: CSRF tokens, tracking when something non-critical last happened 

See 
https://www.drupal.org/docs/8/api/state-api/overview

h3. Technical Requirements
[] When I run drush sql-sanitize I want to scrub all state information for mysql.

**Comment by weitzman** [comment]
Yeah, that makes sense for most use cases. Should be an easy way to enable/disable it though. If you are testing updatedb how an update will behave against Prod, you might very well want the state system entries (i.e. schema_version) for your testing.

**Comment by Berdir** [comment]
Drive by comment of a very old issue, but this can be closed.

just because state isn't meant to be deployed does not mean it is transient.  it contains a lot of information that is absolutely *crucial* to your site, including system schema versions, entity schema and much more.

that reset comment no longer exists like that in the docs, a drupal site does not function without state. If you have a specific collection or state keys that contains user data, then a) maybe don't use that because especially state isn't meant for that or b) write a custom and specific sanitize plugin.
