### ISSUE TITLE
Shebang scripts not working

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2876]
I cant get shebang scripts to work. I'm ok with dropping this feature. If anyone wants to debug, we ship with one. this should run it - `./drush --script-path=./examples php-script helloworld.script`

**Comment by greg-1-anderson** [comment]
Shebang scripts run like bash scripts:
```
$ ./examples/helloworld.script foo
Hello world!

The arguments to this command were:
  foo

No bootstrapped site.
```

**Comment by greg-1-anderson** [comment]
Shebang scripts are supported by Robo, so it shouldn't be any trouble to continue to support them in #2843.

**Comment by weitzman** [comment]
Yes of course!

However, its still not working for me. Note that `drush` points to my launcher so I have to pass -r. For some reason Drush is not bootstrapping properly. And its not recognizing the shebang. Will debug later.

```
drush/examples/helloworld.script -r /Users/moshe.weitzman/reps/b4 --debug

[error]  The Drush command 'drush/examples/helloworld.script' could not be found. Use 'drush core-status' to verify that Drupal is found and bootstrapped successfully. Look for 'Drupal bootstrap : Successful' in its output. [0.88 sec, 22.49 MB] 
```

**Comment by greg-1-anderson** [comment]
Sounds like the launcher is not passing through the original working directory; I am guessing that Drush 8 behaves the same way. I'm not sure if there are other commands that use this; pm-download is the only one I can think of off the top of my head, and it only needs it when there is no bootstrapped site.

It works if you bootstrap via the cwd rather than via -r:
```
$ ~/local/drupal/drush9/drush/examples/helloworld.script foo
Hello world!

The arguments to this command were:
  foo

The following site is bootstrapped:
$aliases['default'] = array (
  'root' => '/Users/ganderson/local/drupal/sites/couture-costume',
  'uri' => 'http://default',
);
```
This could just be documented as a limitation of shebang scripts; ideally, though, the launcher would pass through the original cwd, just in case it was needed.

**Comment by weitzman** [comment]
We decided to deprecate shebang scripts.
