### ISSUE TITLE
Provide an example of global annotated command

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#2885]
Per the [documentation](http://www.drush.org/en/master/commands/) it should be possible to place custom command under _./drush_ directory inside Drupal root. Unfortunately the documentation does not explain what namespace should be used for command files and where is the right place for _drush.services.yml_ in this case.

**Comment by greg-1-anderson** [comment]
I think the namespace should be `\Drush`. We should have an example global command.

services.yml is something that only happens in the context of a specific Drupal site. At the moment, this is only supported for Drush commands that are part of a Drupal module. The thought is that global annotated commands should only be used for functions that do not require calling in to Drupal APIs or Drupal dependencies -- or having any dependencies at all, other than those you inherit from Drush. The reason for this is that your Drush command should be stored in the Drupal site if it needs dependencies, so that its dependencies will be evaluated with Drupal's at `composer update` time.  The reasoning behind `drush.services.yml` is similar; if we allowed this for global commands, you might potentially be using the same services file across different minor versions of Drupal (8.3.x, 8.4.x, etc), and who knows if that would work or not. I don't think we really want to get into `drush.services.d8.3.x.yml` & c.

**Comment by greg-1-anderson** [comment]
I should mention that the above is just background on my reasoning. This is open for discussion if folks have suitable need, and services that are likely to be stable enough to be more useful than problematic when used from a global context.

**Comment by joachim-n** [comment]
AFAICT it's currently not possible to create custom global commands that use annotation.

The main blocker is https://github.com/drush-ops/drush/issues/2918.

I've made notes on various workarounds -- with varying amounts of hackery involved -- in the README here https://github.com/drupal-code-builder/drupal-code-builder-drush#installation

**Comment by joachim-n** [comment]
> The thought is that global annotated commands should only be used for functions that do not require calling in to Drupal APIs or Drupal dependencies -- or having any dependencies at all, other than those you inherit from Drush. 

I don't agree with that reasoning at all. Commands in the ./drush/ folder are those that don't require a Drupal module, because they provide only a CLI and not a web UI.

Having to add an empty module around a command file is one of the workarounds I was referring to -- and it should be just that, a workaround.

**Comment by weitzman** [comment]
It doesn't matter from an architecture perspective if a user is operating via CLI or web ui. Thats not going be a helpful distinguishing point. 

Greg's statement is built into the architecture of Drush9 at this point. Its not too likely that this changes.

**Comment by joachim-n** [comment]
So you're saying that a command stored in DRUPALROOT/drush can only be a legacy procedural command? And that if I want the benefit of Symfony console in my Drush command, it must be built into a Drupal module?

Sheesh, I purposefully split the Drush command OUT of the Module Builder module, and now I'm going to have to put it back in again!

**Comment by weitzman** [comment]
Not exactly. Nobody should be writing legacy procedural commands for
Drush9. You can write an annotated command from a global position. Its just
that the command cannot use DI. You can, if you want, get Drupal services
from the container and call their methods and so on.

**Comment by weitzman** [comment]
Lets work on docs at #2905. We have more docs now but they are not complete.
