### ISSUE TITLE
Backend adds --verbose when --debug is specified,. It also accumulates them.

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2898]
`drush @foo --debug st` gets tranformed to `drush --debug --verbose` on the ensuing backend call. The addition of --verbose changes log level.

**Comment by greg-1-anderson** [comment]
Another thing I noticed is that if backend invoke calls backend invoke, then --debug and --verbose pile up, so you get `--debug --verbose --debug --verbose`, and so on for each nested level. This is uncommon, but duplicate debug / verbose should be removed.

**Comment by weitzman** [comment]
Please see the OP. Backend is upping og level without reason.

**Comment by weitzman** [comment]
Oh, I see what you mean. The added --verbose has no effect on a Drush9 backend. Closing.

**Comment by greg-1-anderson** [comment]
There are still things to do here. I think that we should support `--verbose` + `--debug` again, in which case the addition will be significant. We should also stop the accumulation of debug and verbose options, even though deeply nested backend calls from backend calls are rare. (I observed that bug due to a bug that caused infinite backend calls.)

**Comment by weitzman** [comment]
backend was replaced.
