### ISSUE TITLE
Ability to run Drush from outside Drupal root directory

### ISSUE THREAD

**Issue by Leksat** [drush-ops/drush#2930]
Hi!

In classic way, Drupal root is the project root. If composer workflow is used, Drupal is installed into a subfolder, say `/web`. For decoupled projects, Drupal root can be located under `/backend/web`.

Would it be possible to somehow make it not required to always go into the subdirectory to run Drush?

One option would be to configure possible Drupal roots. For example, in `~/.drush/drushrc.php`:
`$options['possible_drupal_roots'] = ['.', './web', './backend/web'];`

Or maybe set Drupal root in some special config file located in the project root?

Anything would be helpful :)

**Comment by weitzman** [comment]
It is not possible to specify roots in a drushrc. However, you can use site aliases to specify roots. You can use the site-set command for convenience if typing the alias every time is inconvenient.

Also, drush9 will find drupal for you if you launch from the composer root instead of /web (for example).
