### ISSUE TITLE
Error: Call to undefined method Symfony\Component\HttpKernel\Event\PostResponseEvent::setDispatcher() when pm-updatecode drupal-8.4.0-*

### ISSUE THREAD

**Issue by cilefen** [drush-ops/drush#2933]
See https://www.drupal.org/node/2907224
`
Error: Call to undefined method Symfony\Component\HttpKernel\Event\PostResponseEvent::setDispatcher() in                                [error]
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() (line 94 of
/data/www/testa9.albanyweb.co.uk/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php) #0
/data/www/testa9.albanyweb.co.uk/web/vendor/symfony/http-kernel/HttpKernel.php(88):
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.terminat...',
Object(Symfony\Component\HttpKernel\Event\PostResponseEvent))
#1 /data/www/testa9.albanyweb.co.uk/web/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32):
Symfony\Component\HttpKernel\HttpKernel->terminate(Object(Symfony\Component\HttpFoundation\Request),
Object(Symfony\Component\HttpFoundation\Response))
#2 /data/www/testa9.albanyweb.co.uk/web/core/lib/Drupal/Core/DrupalKernel.php(634):
Stack\StackedHttpKernel->terminate(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpFoundation\Response))
#3 phar:///home/adam/ttt/drush.phar/lib/Drush/Boot/DrupalBoot8.php(198):
Drupal\Core\DrupalKernel->terminate(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpFoundation\Response))
#4 phar:///home/adam/ttt/drush.phar/includes/preflight.inc(75): Drush\Boot\DrupalBoot8->terminate()
#5 phar:///home/adam/ttt/drush.phar/includes/startup.inc(458): drush_main()
#6 phar:///home/adam/ttt/drush.phar/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#7 phar:///home/adam/ttt/drush.phar/drush(114): drush_startup(Array)
#8 /home/adam/ttt/drush.phar(10): require('phar:///home/ad...')
#9 {main}.
`

**Comment by Gixxa** [comment]
I just gut this error:

> Do you wish to run all pending updates? (y/n): y
Performing system_update_8400                                                                             [ok]
Performing system_update_8400                                                                             [ok]
Performing system_update_8400                                                                             [ok]
Performing system_update_8401                                                                             [ok]
Performing system_update_8402                                                                             [ok]
Performing node_update_8400                                                                               [ok]
Performing file_update_8300                                                                               [ok]
Performing system_update_8403                                                                             [ok]
Performing content_translation_update_8400                                                                [ok]
Performing dblog_update_8400                                                                              [ok]
Folgeverarbeitungen nach der Aktualisierung von dblog werden ausgeführt                                  [ok]
Folgeverarbeitungen nach der Aktualisierung von field werden ausgeführt                                  [ok]
Folgeverarbeitungen nach der Aktualisierung von language werden ausgeführt                               [ok]
Folgeverarbeitungen nach der Aktualisierung von node werden ausgeführt                                   [ok]
Folgeverarbeitungen nach der Aktualisierung von system werden ausgeführt                                 [ok]
Folgeverarbeitungen nach der Aktualisierung von system werden ausgeführt                                 [ok]
Folgeverarbeitungen nach der Aktualisierung von views werden ausgeführt                                  [ok]
Cache rebuild complete.                                                                                   [ok]
Finished performing updates.                                                                              [ok]
PHP Fatal error:  Call to undefined method Symfony\Component\HttpKernel\Event\PostResponseEvent::setDispatcher() in /var/www/clients/client1/web34/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 94
Drush command terminated abnormally due to an unrecoverable error.                                        [error]
Error: Call to undefined method Symfony\Component\HttpKernel\Event\PostResponseEvent::setDispatcher() in
/var/www/clients/client1/web34/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php,
line 94

Drush Version is 8.1.14. It looks like the update to 8.4 was done correct as drush status gives me:

> drush status
 Drupal version                  :  8.4.0
.....

Not sure what to make of the "error"

**Comment by greg-1-anderson** [comment]
The problem is that Drupal's API changes out from under pm-updatecode. The error happens after all of the critical work has been done, so while it looks scary, the operation works.

It would be nice if we had someone, or maybe a few someones, who could help maintain the pm-* code and fix up some of these problems.

**Comment by WiertD** [comment]
![bug-drush](https://user-images.githubusercontent.com/9157905/31467988-37ff5e1e-aedc-11e7-8644-0abbb777fa3b.png)
And as a result I can not even disable modules in the GUI anymore. Nor can I use drush. 
Another disappointment working with Drupal 8.

**Comment by cam8001** [comment]
Disabling of modules in Drupal 8 was removed a long time ago after much discussion. You need to _uninstall_ modules instead.

https://www.drupal.org/node/2225029

**Comment by xjm** [comment]
To uninstall modules, `drush pmu modulename` or clicking on the "Uninstall" tab on the module screen. I don't think this has anything to do with the issue reported here.

To my knowledge, the error message is harmless. If anyone has any instance of it interfering with any drush functionality, then please document the steps to reproduce the issue here.

**Comment by flatsiedatsie** [comment]
Updating to Drupal 8.4.2 through drush end is this error, and also a black screen with "The website encountered an unexpected error. Please try again later."

**Comment by greg-1-anderson** [comment]
@flatsiedatsie I presume you upgraded from 8.3.7/earlier? Try upgrading to 8.4.0 first, then upgrade from 8.4.0 to 8.4.2 and see if that works.

**Comment by ecvandenberg** [comment]
Using Drush 8.1.15. I just did a drush up drupal-8.4.0 on a Drupal 8.3.7 version, and got the same error at the end. After this I did a drush up to get the latest Drupal version (8.4.2) and that processed successfully. No errors. The website seems OK. No errors in the status report or logging.
So can we just ignore this error?

**Comment by greg-1-anderson** [comment]
Yes, it is a known issue that you get an error that you can ignore when updating from 8.3.7 to 8.4.0 via `drush pm-update`. Reportedly, going directly to 8.4.2 prints the same error, but in this instance the update does not work. I haven't verified this later problem; it is also possible that @flatsiedatsie is experiencing a problem caused by some contrib module.

**Comment by akupaka** [comment]
Updating Drupal 8.3.7 (default installation plus Bootstrap theme) to Drupal 8.4.2 using Drush 8.1.15 has ended with the same error but site works normal.

**Comment by akupaka** [comment]
By the way, in error log through UI I see that "Location" is "http://default/" though in other logs it usually begins with "http://uws:8010/..." which is actual site location. Don't know whether it is important.

**Comment by jksinton** [comment]
First, I have drush 8.1.15 locally installed in a separate directory (e.g., /home/james/lib) than drupal and drupal is installed in /var/www with a symlink to my home path.

I'm noticing a similar error when attempting to upgrade from 3.3.7 to 3.4.x using drush:
```
Error: Call to undefined method Symfony\Component\DependencyInjection\Reference::isStrict() in /home/james/drupal/modules/devel/webprofiler/src/Compiler/ServicePass.php on line 53 #0 /home/james/drupal/modules/devel/webprofiler/src/Compiler/ServicePass.php(26): Drupal\webprofiler\Compiler\ServicePass->extractData(Object(Drupal\Core\DependencyInjection\ContainerBuilder), Object(Symfony\Component\DependencyInjection\Compiler\ServiceReferenceGraph))
. . . 
```
The site does not come back up, and it outputs ```The website encountered an unexpected error. Please try again later.``` I've also tried going to 8.4.0 first and then to 8.4.2 as suggested above, but that fails as well.

**Comment by naught101** [comment]
Is there a work-around for this?
