### ISSUE TITLE
Discovering pending security updates using Composer (Drush 9)

### ISSUE THREAD

**Issue by mariagwyn** [drush-ops/drush#2947]
`pm-update` commands appear to be removed in Drush 9 in preference for using composer for updates. However, composer does not provide a way to indicate security updates as distinct from bugfix updates for drupal modules.

Will Drush 9 have a command that allows detection of pending security updates? I.e, the equivalent of `drush pm-updatestatus`?

**Comment by greg-1-anderson** [comment]
This is still up in the air. What we need is someone interested in driving progress on the pm-* commands in Drush 9.

**Comment by weitzman** [comment]
I dont think Drush will add that, because you can get very close with just
Composer. Add this as a dependency to your composer project -
https://github.com/drupal-composer/drupal-security-advisories. Then, your
build will break whenever there is a pending security advisory.

This solution is just a start for a service like Acquia RA. More work is
needed to extract the right data for informative alert emails and such.

**Comment by mariagwyn** [comment]
Interesting product Moshe, but it certainly doesn't provide the handy command to check for drupal security advisories. This seems a pretty significant loss for those who use drush to help warn them about the presence of insecure modules running on their site.

**Comment by mariagwyn** [comment]
Will Drush8 pm-updatestatus still work on Drupal8.4+ at all?

**Comment by weitzman** [comment]
It seems to work now, at least with a vanilla drupal. Its so much safer though to have a Drush in your composer project, as opposed to outside.

**Comment by joestewart** [comment]
There is also https://security.sensiolabs.org/
Only has core at this point but soon should have all Drupal security announcements

https://www.drupal.org/node/2461167

**Comment by mariagwyn** [comment]
Moshe, the catch-22 here is that if folks add Drush9 to their project rather than rely on the servers, running Drush8 commands to detect the need for security updates is compromised until we can find another solution.

The sensio tool might be an interesting workaround, if it is reliable.

**Comment by greg-1-anderson** [comment]
Once https://github.com/drush-ops/drush/pull/2843 lands, I think it would be better for Drush 9 users to use the global Drush. Drush8 will always call a site-local Drush9, which blocks use of the pm-* commands and prevents you from running any Drush8 extensions included in your modules. We need a solution to that problem as well.

As for https://github.com/drupal-composer/drupal-security-advisories, I am no longer convinced this is of much utility. Vulnerable components are not added to the list until there is a fixed release available, and the security advisory does nothing for you at `composer install` time -- in only works at `composer update` time, at which point the problem is fixed for you. You don't even get any warning that the update contained security advisories. If you don't pin any component (to prevent it from going to the latest version), I don't think you need drupal-security-advisories in your project at all.

**Comment by greg-1-anderson** [comment]
A command that acts as a front-end to https://security.sensiolabs.org/api would be helpful.

**Comment by joestewart** [comment]
https://packagist.org/packages/sensiolabs/security-checker

**Comment by greg-1-anderson** [comment]
I added a pull request to Daniel Bachhuber's [Composer Lock Updater](https://github.com/danielbachhuber/composer-lock-updater) project: https://github.com/danielbachhuber/composer-lock-updater/pull/5

Here's an example of it in action:

https://github.com/consolidation/Robo/commit/92471425cd4eea6e76d35bd7d942cf207122b3ba

**Comment by weitzman** [comment]
That CLU project looks awesome. We really need to get Drupal advisories incorporated into that project somehow.

**Comment by weitzman** [comment]
Looks like this is coming soon to Drush9 - #3087

**Comment by weitzman** [comment]
Its in.
