### ISSUE TITLE
Drush 9 converts command arguments as command aliases

### ISSUE THREAD

**Issue by FGM** [drush-ops/drush#3054]
When passing arguments named like existing command aliases, they are converted to the full name of the command. 

Example:

* `drush en fr foo` passes `[‘fr’, ‘foo’]` to the  command, 
* `drush en fr en` passes `[‘fr’, ‘pm-enable’]` to the command, expanding the parameter as if it was a command alias

Also happens when using `drush_invoke_process()`:

* `drush_invoke_process('@self', 'language:export:translation', ['fr', $file], $exportOptions)` invokes `exportTranslations()` with `fr`
* `drush_invoke_process('@self', 'language:export:translation', ['en', $file], $exportOptions)` invokes `exportTranslations()` with `pm-enable`

**Comment by greg-1-anderson** [comment]
Ooops.

Drush has a feature in the preflight to convert from old-style flags, e.g. `--ssh-options` to the equivalent new form, e.g. `-Dssh.options`.  The feature was used to convert the command shortcut `en` to `pm-enable`, because Symfony will not disambiguate the `en` shortcut between other commands with similar embedded patterns. Unfortunately, the existing preflight conversion mechanism is indiscriminate about the position of the items it is converting.

We need to either remove this conversion, or enhance it so that it only converts command aliases if they appear in the Drush command position.

**Comment by weitzman** [comment]
Nice debugging.

I dont think we can remove this conversion. The muscle memory for 'en' is large. 

Right now, the only arguments affected by this would be 'en' and 'si'. So, its probably just language modules that would feel the pain. If drush-language not use that literal argument, that would be ideal. Otherwise, a Drush PR which makes us only remap command name would be appreciated. See  https://github.com/drush-ops/drush/blob/a2a4ebd272a00d0424ff2d38fbde6f77c5ce7642/src/Preflight/Preflight.php#L99

**Comment by FGM** [comment]
Also count "fr" in: it's features-revert which is likely to be used quite a bit too. And there are probably many more.

**Comment by weitzman** [comment]
Drush is not remapping fr so there will be no problem. See the array in the
link I posted above.

**Comment by greg-1-anderson** [comment]
Not every two-letter command alias is a problem; Symfony would only have trouble with `fr` if there were a lot of other commands that begin with `fr`. This may or may not be the case.

We currently do not have a mechanism for commands to extend the preflight conversion. There is no way we could support that, as preflight happens very early, and command hooks do not get loaded until much later.

**Comment by greg-1-anderson** [comment]
This still needs to be fixed.
