### ISSUE TITLE
Psysh cannot be used

### ISSUE THREAD

**Issue by claudiu-cristea** [drush-ops/drush#3091]
```bash
$ drush -v
Drush Commandline Tool 9.0.0-beta7
```

When I'm trying:

```bash
$ drush php
```
I'm getting:

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "php" is ambiguous (php:eval, php:script).
```

**Comment by claudiu-cristea** [comment]
I noticed that also other command were not listed (like cset). Then I rebuilt the cache (`drush cr`) and commends reappeared. First I tried `drush cc drush` with no effect. I'm not sure that some commands should rely on site's cache.

**Comment by greg-1-anderson** [comment]
Because of the way that Drush 9 module extensions rely on Drupal for dependency injection, it is an unfortunate necessary side-effect that the site cache will affect their operation. You only need to `cr` once after installation, though, and it should not bother you thereafter.

Regarding the discoverability problem this poses, see https://github.com/drush-ops/drush/issues/3036.

The problem with the `php` shortcut for core:cli (which should certainly be `php:cli`) being confused with `php:eval` and `php:script` is a Symfony limitation (bug). We've already worked around this for some other commands, and could add `php` to the list to fix this.

**Comment by greg-1-anderson** [comment]
It turns out that `core:cli` was not being confused with `php:eval` etc; that message is only printed if `core:cli` is not available, e.g. due to bootstrapping problems.
