### ISSUE TITLE
runserver should be able to serve https

### ISSUE THREAD

**Issue by candrews** [drush-ops/drush#3102]
With the increasing use of https, it would be very helpful if `drush runserver` could start an https server instead of a plain http server is an option indicating as such is provided.

I suggest that an `--https` option be added to the already documented options (https://drushcommands.com/drush-8x/runserver/runserver/).

This change would allow for improved testing (such as if the project requires https for some functionality being tested, ex HTML5 Geolocation).

Originally discovered by https://github.com/acquia/blt/issues/2188

**Comment by greg-1-anderson** [comment]
`drush runserver` is a wrapper around the php built-in webserver, which only supports http connections. In order to provide this functionality, we would need to bundle (or worse, implement) an https-capable web server. This is out of scope for Drush. If you need https for testing, you should install an https-capable web server for the purpose. Circle 2.0 and Travis allow testing with docker containers; this would probably be the best way to go for this particular use case.

**Comment by candrews** [comment]
Instead of directly using PHP's built in web server, could you consider using https://github.com/mpyw/php-hyper-builtin-server instead? That supports all that PHP's built in supports but also HTTPS.

**Comment by greg-1-anderson** [comment]
I think it's out of scope for Drush to bundle a webserver. @weitzman can reopen if he disagrees.

A better workaround would be for test suites that need https to install a separate webserver.

**Comment by weitzman** [comment]
I agree. We have had runserver for many years and this is the first feature request for https. Folks are solving this elsewhere, as Greg suggests.
