### ISSUE TITLE
Allow updating modules with new service dependencies

### ISSUE THREAD

**Issue by claudiu-cristea** [drush-ops/drush#3193]
See https://www.drupal.org/project/drupal/issues/2863986 for a description of the problem.

If I'm applying the patch from https://www.drupal.org/project/drupal/issues/2863986#comment-12361105, the problem is fixed with `update.php`, but not with Drush.

So, somehow we need to alter in the same way and remove the services. But I'm totally lost with Drush architecture. I have no idea how to hook into `\Drush\Runtime\Runtime` or `\Drush\Runtime\DependencyInjection::initContainer` based on the command (we have to check if the `updatedb` command is about to be run).

Potentially related to #2611

**Comment by pfrenssen** [comment]
I am looking into this. We need to be able to use the `UpdateKernel` instead of the standard `DrupalKernel` when running `updatedb`.

Ideally we should be able to put information about which kernel to use in the annotation of the command and pass this on. The annotation data is available up to `BootstrapHook::initialize()` which then strips out the bootstrap phase from the annotation data and only passes this on to `BootstrapManager::bootstrapToPhase()`. I think it would make sense to pass on the kernel to use as an additional option to `::bootstrapToPhase()`.

At this time I haven't put much thought into the compatibility between the different Drupal versions. Drupal 7 and older don't need it but Drupal 9 and later will probably still have it in one form or another. I want to avoid hardcoding the full FQN `\Drush\Drupal\UpdateKernel` in the annotation of the command, since this is the responsibility of the core version to resolve (in our case this will be handled by `DrupalBoot8::bootstrapDrupalConfiguration()`.

 Our immediate use case is to be able to bootstrap the `UpdateKernel` so I am thinking of supporting two constants right now: `const KERNEL_DRUPAL = 'drupal'` and `const KERNEL_UPDATE = 'update'` so we can have an annotation like this:

```
@kernel: update
```

**Comment by weitzman** [comment]
I looked into this a little bit but don't have much guidance. Perhaps @greg-1-anderson could chime in.

I will say that this is a very infrequent need so if we end up special casing updatedb thats fine for now. Drupal doesn't have an abundance of kernels.

**Comment by pfrenssen** [comment]
OK thanks that's good to know. I'll have a go at this.

**Comment by weitzman** [comment]
A couple ideas:

1. Build a new UpdateKernel() at start of updatedb and then overwrite the DrupalKernal by making a new \Drush\Boot\DrupalBoot8::setKernel method.
1. Change updatedb to `@bootstrap none`. This means that the command gains control far earlier in the process. You can then bootstrap further with \Drush\Boot\BootstrapManager::bootstrapToPhase(FULL)

**Comment by greg-1-anderson** [comment]
I haven't really looked into this. I am sort of inclined to say that we should pass along all of the command annotation data to the bootstrap manager so that the UpdateKernel can be selected as needed, as it is the responsibility of the bootstrap manager to set up the Kernel.

However, updatedb is the only command that needs to do this, ever. Perhaps giving too much flexibility to Kernel creation in the bootstrap manager would be an unnecessary complication, since the updatedb command can bootstrap on its own. However, `\Drush\Boot\BootstrapManager::bootstrapToPhase(FULL)` isn't a good way to go, as this will use the DrupalKernel as usual.

Maybe the best compromise would be to provide a public method of the BootstrapManager to bootstrap with the UpdateKernel, and have the updatedb command call that directly.

**Comment by pfrenssen** [comment]
I posted a PR with an initial attempt, which is implementing my first idea, which is quite close to the first remark of @greg-1-anderson to pass along the annotation data to the bootstrap manager.

I have to stop for today but I will try again tomorrow by providing alternative methods on the `BootstrapManager` to bootstrap with the `UpdateKernel`.

However even with that approach I will be hitting the same problem that I am now. The update command works fine up to the point that it initiates the batch process. For a reason I don't understand yet the batch-process command is not found by Symfony Console.

`\Symfony\Component\Console\Application::find()` throws a `CommandNotFoundException` with message `Command "batch-process" is not defined.`. This is caught in `\Drush\Application::bootstrapAndFind()` which will then proceed to raise the bootstrap level to maximum, but this will boot the wrong kernel.

I will need to find a way to run the batch process with the `UpdateKernel`.

**Comment by weitzman** [comment]
Commands that are located in src/Drupal/Commands/core (as opposed to src/Commands) like batch-process are only recognized after a full bootstrap (similar to commands located within modules), as thats when they get added to the $application. So batch-process may need some special casing like updatedb. This is getting a bit messy.

**Comment by greg-1-anderson** [comment]
Yeah, it's sounding like letting the bootstrap manager know about UpdateKernel might be the easier road.

Alternately, make a service class that we can use via a simple `new ClassName()`, and utilize that from both the updatedb command and the batch process command. That's probably the most straightforward way.

**Comment by pfrenssen** [comment]
Thanks for the tips! So my current battle plan is as follows:

1. Remove the `$kernel` arguments that I introduced out of the call stack leading up to `BootstrapManager`.
1. Provide a public `setKernel(string $kernel)` method on the `BootstrapManager`, this will take either `Kernels::DRUPAL` or `Kernels::UPDATE` and will default to `Kernels::DRUPAL`.
1. Set `@bootstrap none` in the annotations for the various update related commands and instead manually bootstrap them with the right kernel.

I am not yet 100% clear on how I can get the `batch-process` initialized using the correct kernel. I don't fully understand how making a service class that can be used from both the `updatedb` and `batch-process` commands will help, since the error is already occurring during the initialization of the `batch-process` command, before it starts running.

I might provide a hidden command `batch-process-updates` inside `UpdateDBCommands` so that it can be found without needing to fully bootstrap the standard kernel. I see that `drush_backend_batch_process()` takes a `$command` argument which can be used for this purpose.

**Comment by weitzman** [comment]
For help, feel free to ping Greg and I on Drupal Slack's drush channel https://drupal.slack.com/messages/C62H9CWQM

**Comment by pfrenssen** [comment]
Thanks for the offer! I will pop in there tomorrow. Today I am travelling and will be without reliable internet.

**Comment by pfrenssen** [comment]
At some point today I couldn't replicate this problem any more. It appears that the fix for #3167 suppresses the symptoms for this bug. I had pulled the latest master and suddenly I could no longer replicate the failure. The `--entity-updates` option needs to be passed in order to trigger the bug.

**Comment by pfrenssen** [comment]
OK so the reason why the `--entity-updates` option was causing the bug to be triggered is simply because it performs a `drush_drupal_cache_clear_all()` after applying the entity updates. This causes the dependency injection container to be emptied, so it will need to be rebuilt, triggering the bug.

This means the bug can occur at any point where a database update is done when the container is empty, for example if `drush cr` has been called prior to starting the deployment.

**Comment by pfrenssen** [comment]
Fixed in #3206.
