### ISSUE TITLE
Drush 9: The sql-sync doesn't use the sites.php to resolve the site's folder 

### ISSUE THREAD

**Issue by segi** [drush-ops/drush#3322]
Currently the sql-sync command cannot find the site's folder if I use hash in the source and target arguments and this isn't match one of folder's name under sites folder.
I know currently this is the expected behavior but in drush 8 the sql-sync tried to check the sites.php to figure out the folder's path. 
Our system currently is heavily build for sites.php so It would be useful to add this feature to drush 9 as well.

I started to check the codebase that how I can add this feature to the codebase. It looks like it won't be easy. 
I think we need to use the DrupalKerner::findSitePath method, but currently the drush tries to validate the arguments and it's too early where we didn't do any bootstrap and the method first param expect a request object. I tried to get the actual request through bootstrap manager but it doesn't exists. 
Can you suggest a way?

**Comment by grasmash** [comment]
You can't use `--uri` or `-l` with `sql-sync` in Drush 9: https://github.com/drush-ops/drush/pull/3261

Drush does parse sites.php: https://github.com/drush-ops/drush/blob/613a0c352b34e7b8e59eadabf5b2ff3203e1698b/src/Boot/DrupalBoot8.php#L79

I did some work that would allow sites.php to be parsed prior to bootstrap, but it is unmerged and I am not planning to continue work on it soon: https://github.com/drush-ops/drush/pull/3278

The suggested approach is to create one drush alias per multisite and define the uri in that alias, rather than passing `-l` in conjunction with the alias.

**Comment by weitzman** [comment]
Thanks @grasmash
