### ISSUE TITLE
Could you please also release a phar archive for drush 9?

### ISSUE THREAD

**Issue by mfechner** [drush-ops/drush#3331]
Could you please add to the stable drush9 releases also a .phar package, like it is done for drush8:
https://github.com/drush-ops/drush/releases/download/8.1.15/drush.phar

Thanks a lot!

**Comment by weitzman** [comment]
No phar is needed. The install process is different for Drush9. See docs.drush.org.

**Comment by chx** [comment]
It is *extremely* short sighted to

1. Break every drush command out there making upgrade very near impossible. Surely a BC layer wouldn't be that hard?

2. Making a dual install almost impossible because you can't even add a `/usr/local/bin/drush9` command because of composer madness.

I hoped the drush authors have more brains than to get drunk on this php reneassiance koolaid some core developers completely lost their minds to. Sad.

**Comment by andreasemer** [comment]
100% agree with @chx !

**Comment by greg-1-anderson** [comment]
I deleted a couple of comments on this thread because they were not made in the spirit of the [Drupal Code of Conduct](https://github.com/drush-ops/drush/issues/3331).

I want to add a couple of notes of explanation to what Moshe said above.

- It is not possible to have a BC layer for Drush 8 in Drush 9. Drush 8 commands can call every function that is available in Drush. They should not call any function that starts with an `_`, but that still leaves most of the functions in Drush available as part of the extension API. It therefore is not possible to have a BC layer for Drush 8 inside of Drush 9, as the primary motivator for the Drush 9 rewrite was to improve the maintainability of Drush. The state of the Drush 8 code base has advanced to the point where it is nearly impossible to make changes, because the API for the subsections was not defined clearly enough, and the internal dependencies made it easy to introduce bugs and incompatibilities whenever core changes were attempted. The upshot is that Drush 8 is the BC layer for the existing Drupal 7 extensions. Drupal 8 extensions should be converted to Drush 9.

- It would not be technically difficult to [create a phar for Drush 9](https://pantheon.io/blog/automate-phar-releases-github-travisci). However, this misses the fact that the intended installation method for Drush 9 is to include it as part of a Composer-managed Drupal site. The Drush maintainers recognize that the global Drush has been very convenient for folks for many years. However, the [realities of the design decisions made by Composer](https://pantheon.io/blog/trouble-two-autoloaders) -- decisions that are shared with most modern dependency managers -- means that the global install of Drush is by necessity fragile.

A good argument can be made that all modern package managers are flawed, and that no one should use them. However, that is not the decision that was made for Drupal 8, and the fact of the matter is that Drush has little choice to conform. Presently, the global Drush still happens to work for both Drush 8 and Drush 9, and Drush 8 still happens to work with the current versions of Drupal 8 (8.5.x and 8.6.x). This means that folks may continue to use the global installs for now (although the global Drush 9 is less useful in this configuration, since it is missing the `pm-*` commands). However, at some point it will become impossible for the Drush maintainers to continue to make this configuration work. that is why this configuration is labeled "happens to work" rather than "supported". One would do well to adopt the Composer workflow for Drupal 8 so that their sites will continue to work with Drush once this day arrives.

**Comment by chx** [comment]
Haha Drupal code of conduct, what are you going to do , ban me from drupal.org? :P

Anyways, unlike in June by now I am mostly fine with Drush 9, it's been quite a struggle to get both working at the same time but it mostly works... one question remains: would it similar not be possible to support the old style aliases? I know they are PHP and supposedly they could run code and break things but almost always they don't and right now I need to maintain two sets of aliases :/

**Comment by greg-1-anderson** [comment]
I am not partial to banning folks. Occasionally I delete posts, but the poster is welcome to come back and post again.

Yes, it would be possible to support both kinds of aliases. The code for Drush 9 aliases are in the [consolidation/site-alias](https://github.com/consolidation/site-alias) project. The alias manager would need to be enhanced to support multiple alias loaders. A PR to do this in the site-alias project would be welcome. A legacy Drush alias loader could be implemented and added to the site alias manager in the Drush repository.

**Comment by greg-1-anderson** [comment]
It might actually be preferable to make a Drush 9 alias loader for Drush 8.

**Comment by chx** [comment]
Yes... how hard would it be to make use of  consolidation/site-alias in drush 8?

**Comment by greg-1-anderson** [comment]
Adding consolidationsite-alias to Drush 8 would be easy, and calling its APIs would be easy. If you did it from [drush_sitealias_get_record](https://github.com/drush-ops/drush/blob/8.1.17/includes/sitealias.inc#L211) it might even work mostly right. However, the site alias code in Drush 8 is kind of dispersed and tangled, so it's difficult for me to say what the odds would be that you'd run into some sort of problem. Any bugs in behavior would probably be hard to fix.

**Comment by Fonata** [comment]
I think I really need a Drush 9/10 phar because [OpenDevShop](https://github.com/opendevshop/devshop/issues/466) is not yet compatible with Drush 9 or 10. So I built one and it works. You can find the steps I took here: https://github.com/box-project/box2/wiki/Drush
