### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in /home/ec2-user/.composer/vendor/webmozart/path-util/src/Path.php:257

### ISSUE THREAD

**Issue by Rakeshsivagouni** [drush-ops/drush#3338]
I am trying to download Drupal8 using drush but I am getting runtime exceptions while installing Drupal.

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in /home/ec2-user/.composer/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 /home/ec2-user/.composer/vendor/drush/drush/drush.php(57): Webmozart\PathUtil\Path::getHomeDirectory()
#1 /home/ec2-user/.composer/vendor/drush/drush/drush(4): require('/home/ec2-user/...')
#2 {main}
  thrown in /home/ec2-user/.composer/vendor/webmozart/path-util/src/Path.php on line 257
I have downloaded drush directly and Drupal copied  from S3.

**Comment by weitzman** [comment]
Sounds like a question for the Path package. 

Support questions like this belong in Drupal Answers. Thanks.

**Comment by hkirsman** [comment]
Did you get answer?

We had the same error lately and I see you're also using AWS Elastic Beanstalk (or at least something from Amazon).

We where pulling Drush with this command:
COMPOSER_HOME=/usr/lib/composer /usr/bin/composer.phar global require drush/drush:8.x-dev

But it seems that it was pulling Drush 9 and it's not working with Drupal 7. You're using Drupal 8 so that's weird. Error is the same though. We fixed it by deploying lock file. Would still like to know why 8.x-dev would download version 9.
