### ISSUE TITLE
drush config-pull @remote --target-dir=foo

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#3423]
Use case: As a site developer, i want to config-sync from a (fully installed) remote site to my local copy of the git repository. (Even if locally there is no bootstrapped drupal)

Something like:
`drush config-pull @remote --target-dir=foo`

**Comment by weitzman** [comment]
http://docs.drush.org/en/master/commands/#global-drush-commands

**Comment by axel-rutz** [comment]
This looks like a misunderstanding to me.

It's a feature request for the config-pull command to not require a bootstrapped drupal.

**Comment by weitzman** [comment]
Oops that comment was meant for another issue.

config-pull already doesn't fully bootstrap the destination. It does need to bootstrap the destination to the CONFIGURATION phase in order to read settings.php and determine the location of config dir on the target. Are you not able to have a configured settings.php? If not, you might have call write a script or command which calls `config-export` on the source and then call `rsync` with a specific destination.

This wouldn't be a difficult feature request but I'm not sure its generally useful enough. Perhaps you can elaborate on your use case.

**Comment by axel-rutz** [comment]
We have very good experiences with a setup like this:
* Sitebuilding happens on a containerized cloud server (with one installation per feature branch)
* Git-fu happens on a local repo clone with better visual git tool support (and push-auto-deployment to the sitebuilding server)

This way we have no hassle with local dev environment. Forthermore - which is a relevant issue to me - the LAMP stack does not drain my laptop battery (of course i always need internet connection and its power consumption but that's not an issue).

This feature would allow us to
a) do all commits on local git, unifying the process
b) even work with code-write-protected installations, unifying the installation

I don't know how many people do this, and of course YMMV. For us it really makes a ton of sense!

**Comment by weitzman** [comment]
That way of building makes good sense to me. See #3436. There is a Usage doc ther. I went with a rsync style declaration of the target path, not a --target-dir option.
