### ISSUE TITLE
how can i RUN drush commands during a docker image build?

### ISSUE THREAD

**Issue by laurencefass** [drush-ops/drush#3616]
how can i RUN drush commands during a docker image build?

i have installed drush at /root/.composer/vendor/bin/drush

dockerfile...

```
# install drush
RUN composer global require drush/drush
ENV PATH="~/.composer/vendor/bin:${PATH}"
RUN drush --version

```
docker build ...

```
Step 4/4 : RUN drush --version
 ---> Running in 893026ebe6d6

> /bin/sh: drush: not found


```

**Comment by greg-1-anderson** [comment]
1. You need to set your PATH to include your vendor/bin directory. `~` is a construct of bash, it's not understood by the filesystem. Since you know the user is `root`, you could hardcode it. Alternately, just use `$HOME` instead of `~`.

2. If you are installing Drush via `composer global require`, please see [Fixing the Composer Global Command](https://pantheon.io/blog/fixing-composer-global-command)

**Comment by laurencefass** [comment]
great! many thanks.
