### ISSUE TITLE
Drush debian 9 ( stretch ) package

### ISSUE THREAD

**Issue by guiu-rocafort** [drush-ops/drush#3626]
Hi,

is there any reason why there is not a debian stretch package for drush ?
I could give a hand if needed.

**Comment by greg-1-anderson** [comment]
@anarcat maintained debian packages with Drush for a while.

**Comment by anarcat** [comment]
yeah, a while ago... Drush was removed from Debian in 2016:

https://tracker.debian.org/pkg/drush

Some of the justification for the removal is here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823767

A copy of the debian/ directory should still be visible here:

https://salsa.debian.org/debian/drush

but i suspect packaging would need to be redone from scratch. I believe drush might have changed frameworks once or maybe twice since the 5.10 version that was packaged back then. ;)

**Comment by weitzman** [comment]
Drush is now installed as part of a composer project so distro packing is not needed nor desired.
