### ISSUE TITLE
Replace "config-export" alias with different string

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#3645]
The alias of the "config-export" command, "cex", is inappropriate given systemic sexisim in most contemporary societies, another alias should be provided as an alternative.

**Comment by greg-1-anderson** [comment]
`cxp`?
`ce`?

**Comment by damienmckenna** [comment]
`ce` would work.

**Comment by TessaBakker** [comment]
Don't forget `cim`, it would be really strange to have two different types of aliases.

**Comment by weitzman** [comment]
I disagree with the premise of this issue. I find am not seeing the logical proof that starts at cex and ends at "promotes sexism". If anyone cares to connect those dots, please write a blog post and link to it from here.

**Comment by damienmckenna** [comment]
Try this: next time you're in a crowded room call out some drush commands and aliases, see which one of them makes people feel awkward.

**Comment by damienmckenna** [comment]
I guess it comes down to wanting to remove problematic word / phrase usage, in this case removing a sexualized word from somewhere that it has no reason to exist.

Would you be comfortable saying the phrase "drush cex" in a keynote speech at DrupalCon, a large group of folks at your client's office, or a classroom of teenagers learning web development for the first time, or a small group learning to take care of a college department's website? What message would it send? How would the male members of the audience feel hearing it? How would the non-male members of the audience feel hearing it? Would it make people feel awkward? Would some folk start joking around that they're "sexing" their Drupal site? Would it make some people wonder why working with Drupal has to involve running "sex" commands every day? How would that feel to a woman just learning Drupal for the first time, maybe questioning whether she should even in IT given how much there is to learn and how much she has to fight and/or ignore structural sexism?

**Comment by greg-1-anderson** [comment]
I am adding more comments because I feel that we could have been more constructive here, and that's bothering me.

First, I want to address the premise of the issue, which I skipped over last time.

Yes, I would be entirely comfortable talking about "drush cex" at the DrupalCon keynote speech, or any other venue. I am comfortable with this because I pronounce this shortcut as "drush sea ee ex". I talk about Drush a lot, and so far I have never had anyone think I was talking about "drush sex" or "drush es ee ex" when I said "drush sea ee ex".  I haven't ever had any confusion or difficulty in understanding with "drush cex", because the Drush config-export command is very commonly used, and most people have existing experience with it. When I hear other people talking about the config-export command, I predominantly hear "config-export" or "sea ee ex".

On one occasion, in the context of a small-to-mid-sized user group meeting, I did say "Just use drush sexy for that." When I said this, it did cause some confusion; a few people _looked_ confused, and one person asked what "drush sexy" was. The explanation I provided at the time was that "drush config-export dash why ("-y") is pronounced 'drush sexy'." At the time, no one seemed to take offense at this joke; however, since that time, the Drupal community has had to work through some issues with community member behavior, and how we as a group are going to better police ourselves in order to create a more welcoming and inclusive environment. Now that I know that there are community members who are concerned about the use of "drush sex" for "drush cex", I am going to stop using "drush sexy", because I know that the bar for what makes me uncomfortable is not necessarily the same as it would be for someone with a different background or experiences. I would not be comfortable using "drush sex", and I recognize that using "sexy" socializes the more overt term. I didn't use "sexy" very often, but I now regret using it at all.

Moving forward, what should we do with the `cex` shortcut?

- On a technical level, removing a shortcut would be extremely disruptive.
- There is a preferred pronunciation for `cex` which is not sexualized.

It is therefore my opinion that we should socialize the preferred pronunciation for this command. Utilize the [Drupal Code of Conduct](https://www.drupal.org/dcoc) in situations where someone is using a pronunciation that makes other people uncomfortable.

I am still +1 on adding more shortcuts such as the previously-suggested `ce` and `ci` to accommodate those who find "sea ee ex" difficult to pronounce, or want a shorter alternative. However, I feel that the primary solution here should be non-technical, so I am leaving this issue closed.

**Comment by greggles** [comment]
I'm now working on my first Drupal 8 site and found myself running the command `cex` and wishing it had a different name.

I think @greg-1-anderson has provided a decent explanation as has @damienmckenna of the risks and problems associated with the alias.

I believe the best outcome would be to move somewhat quickly to change the alias in a way that maintains backwards compatibility. If drush ever gets hidden aliases or deprecated aliases then `cex` and `cim` could be further hidden/removed. @weitzman I'd be happy to discuss this further e.g. via call/video/slack if you want.

Are there technical objections to #3647 ?

**Comment by greg-1-anderson** [comment]
I am 👍 on #3647

**Comment by damienmckenna** [comment]
Some feedback from people who wished to remain anonymous:

> It was a joke today at my job that when doing config exports we get to do drush sex (drush cex)

> When the drush config management stuff got released, Alex made me a t-shirt that said “Configuration Management Makes Drush cex -y”

> that in fact at companies, when talking outloud people do say drush “sex” and then giggle and laugh, clearly making the listeners suddenly think of sex while in a work setting involving drupal and drush.

**Comment by heyrocker** [comment]
Actually that t-shirt comment came from me, and I don't mind claiming it. I used it to point out that this pronunciation has been known, highlighted, and joked about from the very beginning. That was three years before Drupal 8 even got released. 

I am in favor of changing the aliases.

**Comment by alexdmccabe** [comment]
I agree, the aliases should be changed.

**Comment by Chi-teck** [comment]
-1
Besides `drush cim` this would also require changing `drush cst` which is not possible.

**Comment by Chi-teck** [comment]
The relevant issue for Config split module.
https://www.drupal.org/project/config_split/issues/3013423
