### ISSUE TITLE
Clarify drush 9 global installation.

### ISSUE THREAD

**Issue by glennpratt** [drush-ops/drush#3699]
**Existing document**
https://docs.drush.org/en/master/install/

**What are you attempting to do**
Trying to clarify best practices and understand how cloud providers should manage Drush 9.

**In what way is the existing documentation unclear or incomplete**
The current documentation says there is only one supported install method:

> ... Drupal 8 site be built with Composer and Drush be listed as a dependency...

However Drush 9 clearly works globally, and this seems required while Drush launcher lacks alias support. Furthermore, @greg-1-anderson at Pantheon recommends globally installing Drush 9 *AND* recommends removing it from site composer in this blog post: [https://pantheon.io/blog/drush-940-release-available-pantheon](https://pantheon.io/blog/drush-940-release-available-pantheon).

**What should the documentation say instead?**
I couldn't say, but saying global install is not supported seems premature.

**Comment by greg-1-anderson** [comment]
The reason that I recommend removing the site-local Drush on Pantheon in that blog post is that Pantheon is still dependent on the Site Audit module, and that module's Drush command is only available for Drush 8 at the moment. If you installed a site-local Drush 9, then it would not be possible to run any Drush 8 extensions.

As you have noted, the global install of Drush 9 still works; however, only the site-local install is supported, which is why the documentation does not have any information on the global install. I'd be happy to chat with you in slack about any issues you might have with the global Drush 9. Either the #drush channel in the Drupal slack, or #power-users in the Pantheon slack would work. Just ping me.

**Comment by greg-1-anderson** [comment]
> ... and this seems required while Drush launcher lacks alias support

Just read that a second time. This is a good point. @weitzman ?

**Comment by weitzman** [comment]
> and this seems required while Drush launcher lacks alias support

Its only required if folks insist on using global launcher. Thats a separate project than Drush, strictly speaking. I'd rather make the aliases work with Launcher than try to support a global Drush. Thats a version mismatch waiting to happen. I've seen it too many times, even after Greg refactored Drush to use Drupal autoloader as early as possible. Pantheon appears willing to support this setup - because they have to for now. All this adds up to the current status - officially unsupported but happens to work. I don't think we can get more clarity/consensus unfortunately.

Greg and I plan to work on the aliases+launcher during Badcamp. Its a significant project, so we wont finish there.

So, back to the issue at hand. My recommendation for some time now is that sites check in their own site-local Drush and their own aliases. I think its plausible now for ISP's to publish aliases on their platform with [Greg's recent work](https://github.com/drush-ops/drush/blob/master/examples/example.site.yml#L181-L212) if you really need that. I dont recommend it but its possible with drush 9.4.

**Comment by weitzman** [comment]
I'm happy to get on the phone or a chat and try to address whatever need you are considering.

**Comment by greg-1-anderson** [comment]
Note also that it's possible to use Drush 8 to call a remote site that is using Drush 9 (either site-local or as a global install), although Pantheon sets things up so that Drush 8 calls the remote Drush version the user selected for their site (usually Drush 8), and Drush 9 calls the remote Drush 9.

The [code to generate Drush aliases for remote Pantheon sites](https://github.com/pantheon-systems/terminus-aliases-plugin) is open source under the MIT license.

**Comment by greg-1-anderson** [comment]
> Its only required if folks insist on using global launcher.

I think the point here is that the global launcher is necessary if all of your sites are remote.

**Comment by weitzman** [comment]
An end user can always have their codebase. So I think thats an ISP-specific situation. ISPs have the wherewithal to come up with a solution, and I'm happy to help. A concrete user story would be helpful.

**Comment by glennpratt** [comment]
Thanks for the feedback!

For context, we do already generate Drush 9 config, yml aliases and some commands for server side usage. On the developer / client side, our path forward is a little hazier. 

My understanding was drush-launcher + external tooling apart from Drush was probably the path forward, but I think that depends on alias support, including remote aliases.

The alternative of only supporting site-local drush means we require site-local code always being present and in good enough shape to run drush - even to perform tasks not related to the local checkout. This isn't impossible but it is more moving parts.

**Comment by weitzman** [comment]
> The alternative of only supporting site-local drush means we require site-local code always being present and in good enough shape to run drush - even to perform tasks not related to the local checkout. 

Yes, I think thats the least-effort way forward. If this rankles anyone, remember that I'm just the messenger. It was the PHP community who jumped all over dependencies+Composer, and Drupal jumped in bed with Symfony. I didn't think it was feasible to maintain Drush without using Symfony dependencies.

FYI, SiteAliases have been [refactored into own Composer project](https://github.com/consolidation/site-alias) so folks can more easily build tools upon it.

**Comment by greg-1-anderson** [comment]
The refactored site aliases project is only nominally useful until we also provide backend invoke, but as mentioned above, we hope to do that sometime around BADCamp (end of October).

**Comment by greg-1-anderson** [comment]
You could always do something simpler with the Symfony Process component, though. See:

https://github.com/pantheon-systems/terminus/blob/1.9.0/src/Commands/Remote/SSHBaseCommand.php#L52

and:

https://github.com/pantheon-systems/terminus/blob/1.9.0/src/Models/Environment.php#L730

Note that these methods currently do not work on Windows.
