### ISSUE TITLE
Provide an option to force import configuration when content exist.

### ISSUE THREAD

**Issue by vijaycs85** [drush-ops/drush#3703]
## Problem
When running config-import with a configuration entity that has existing content, the drush command throws `here were errors validating the config synchronization: Entities exist of type [type]. These entities need to be deleted before importing.` This could be an issue especially a) development environment b) working on multiple issues c) do not care about the test content.

Deleting content entities also not as simple as the first-class content entity like node. We have media entities and custom entities where there is no easy bulk delete option. 

## Solution
It would be great to have a flag or separate command that would allow deleting the content and import configuration in one step. 

**Current alternatives are:**
1. Edit Drupal\Core\Entity\Event\BundleConfigImportValidate to delete all the $entitiy_ids discovered
2. Create a script to delete them and run with `drush src`.

**Additional context**
https://twitter.com/vijaycs85/status/1044420647856885766

**Comment by weitzman** [comment]
That command was added in March https://github.com/drush-ops/drush/blob/3b1aba390773406c663ab883422418ec5a8fa678/src/Drupal/Commands/core/EntityCommands.php#L22-L43

**Comment by vijaycs85** [comment]
Thanks, @weitzman. Basically, we have to combine both commands for now.

**Comment by vijaycs85** [comment]
The command would be: `drush edel --bundle=article &&  drush cim -y`

**Comment by DLatty-NJT** [comment]
Why is deleting then recreating the option? How bout fix the issue - especially for existing sites where deleting/recreating content shouldn't be the option

**Comment by fabianfiorotto** [comment]
Can you add this new command to the import error as a suggestion? So we can copy and paste. That would save a lot of time.

**Comment by gorgabal** [comment]
I know this is a old issue. But there is another use case where the ability to force an import would save a lot of time. 

When I work with my local development, we often use the same docker container for work in multiple branches. (often the situation is that we work on bigger-picture stuff in a separate branch, but we also need to do hotfixes on the production branch). 

Once you checkout the production branch, you often need to import its config. But this often cannot be quickly done because the existing config(including content) from the newer branch still being in your container. Now I often have to, multiple times a day, hunt for the content and delete it manually. 

Hope this feature can be added someday.
