### ISSUE TITLE
Untangle logger and context.inc

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#3806]
Logger is the last big thing to use context system.

**Comment by greg-1-anderson** [comment]
Would it be worth it to make a simple log-collection class just for use in the deprecated backend invoke compatibility functions so that we can drop references to context.inc?

Not sure if we do or do not want to remove context.inc; it's possible that a Drush extension might be using it, although I suppose we can say that it's an internal module, and therefore not supported.

**Comment by weitzman** [comment]
Log collection implemented in #3811.
