### ISSUE TITLE
drush site-install doesn't recognize --db-url parameter

### ISSUE THREAD

**Issue by raphaeltraviss** [drush-ops/drush#381]
I'm trying to install Drupal 7 using drush.  However, drush is not recognizing the --db-url parameter I'm passing to it.  Is there a specific way that these parameters need to be supplied to drush?  Based on drush help si, the following command should work, but it does not:

```
drush site-install standard --account-name=myuser --account-pass=mypassword --db-url=mysql://dbuser:dbpassword@localhost/mydatabase
Could not determine database connection parameters. Pass --db-url option.
```

OS X with drush 6.20 installed via brew.

**Comment by techninja** [comment]
Just in case anyone else runs across this: I found on a newly setup server, I would get the `WD php: Exception: To start over, you must empty your existing database.` error on site-install because I was missing the MySQL PHP library! What a strange and silly thing. If using Ubuntu, just run
```
sudo apt-get install php5-mysql
```
Then slap your forehead. :stuck_out_tongue_winking_eye:

**Comment by spleshka** [comment]
Thanks @techninja, installing php5-mysql solved the issue! Love new installations :)

**Comment by palcu** [comment]
@techninja slapping my forehead now, thank you.

**Comment by ruby232** [comment]
I use drush 8 and php5-mysql is installed, but have the same error.

**Comment by mamesaye** [comment]
@techninja, thanks did not think of that.
