### ISSUE TITLE
Unable to import database with `drush sql:cli < foo.sql`

### ISSUE THREAD

**Issue by TMWagner** [drush-ops/drush#3859]
Updated dev environment to Drush 9.6.0-beta; Unable to load (import from dump file) database. 

> executed command drush sqlc < databasedump.sql

Expected database to load 

**Actual behavior**
command took me to MySQL command line

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0-beta
| Drupal version? | 8.6.5
| PHP version     | 7.2.13
| OS?             | Mac

**Additional information**

**Comment by weitzman** [comment]
Our betas as numbered. Which beta are you using?. Its reported in `drush status`

**Comment by weitzman** [comment]
OK, I can reproduce this on master branch. Will investigate.

**Comment by weitzman** [comment]
I looked at our other usages of commands reading from stdin and they all are unaffected by this problem, because they start reading based on an argument value of `-` (state:set, cache:set, config:set, ...). So we can fix this command to always behave as it has, or we can point people to `drush sql:connect < foo.sql` as a replacement. Thats been the documented way to do this for a long time.

**Comment by verbruggenalex** [comment]
I'm having the same issue on Drush Commandline Tool 9.7.1 in my Cloud9 (Amazon Linux AMI) environment.
`./vendor/bin/drush sqlc < dump.sql` is entering the mysql mode instead of piping the dump.sql into it.
This commit is working for me: https://github.com/drush-ops/drush/commit/9a03ed80412fd1c2113fd8392c50b1846bd5ef2e

**Comment by wah22** [comment]
So I am using drush 10.2.0 and `drush sqlc < test.sql ` doesn't work. It takes me into the mysql command prompt

**Comment by tomdearden** [comment]
> So I am using drush 10.2.0 and `drush sqlc < test.sql ` doesn't work. It takes me into the mysql command prompt

Same here on Drush 9.7.2 - this used to work on Drush 8, FWIW - as did piping from `gunzip -c` for compressed archives.  Both now dump out to a MySQL client command prompt.  Using the string output from `drush sql-connect` in place of the `drush sqlc` command works as a workaround but I miss the elegance of the old way of doing it :(

**Comment by rsanzante** [comment]
It seems the fix was never committed.

The two commits (https://github.com/drush-ops/drush/issues/3859#ref-commit-9a03ed8 and https://github.com/drush-ops/drush/issues/3859#ref-commit-b67442d) are not in the repository. If you check the commit's page (https://github.com/drush-ops/drush/commit/9a03ed80412fd1c2113fd8392c50b1846bd5ef2e and https://github.com/drush-ops/drush/commit/b67442debd237db888798f603609973ecd545365) you can see the following message:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Indeed, the git hashes are not in git:

```
$ git o 9a03ed8
error: pathspec '9a03ed8' did not match any file(s) known to git  
```
```
$ g o b67442d
error: pathspec 'b67442d' did not match any file(s) known to git     
```

Both commands were run against a fresh clone of git@github.com:drush-ops/drush.git.

Last, the merge referenced (https://github.com/drush-ops/drush/pull/3865) does not modify the `src/Commands/sql/SqlCommands.php` file.


I've tested the code proposed in the cli function in that file:

```
    public function cli(InputInterface $input, $options = ['extra' => self::REQ])
    {
        $sql = SqlBase::create($options);
        $process = $this->processManager()->shell($sql->connect(), null, $sql->getEnv());
        if (!Tty::isTtySupported()) {
            $process->setInput($this->stdin()->getStream());
        } else {
            $process->setTty($this->getConfig()->get('ssh.tty', $input->isInteractive()));
        }
        $process->mustRun($process->showRealtime());
    }

```

However, is not clear to me if we should use this code or the "new StdinAwareInterface" as it is said on the merge request above.


In my case, the problem arises using "CentOS Linux release 7.6.1810 (Core)".

**Comment by rsanzante** [comment]
@greg-1-anderson, you may be interested in my [previous comment](https://github.com/drush-ops/drush/issues/3859#issuecomment-736539002) as you were the author of the commit that was never committed  (or that's what it seems).

**Comment by bioshazard** [comment]
@rsanzante, I ran into a similar issue recently. I thought I had broken something in my container environment, but applying the diff you linked here, https://github.com/drush-ops/drush/commit/9a03ed80412fd1c2113fd8392c50b1846bd5ef2e?branch=9a03ed80412fd1c2113fd8392c50b1846bd5ef2e&diff=unified, I am able to utilize `sqlc` with STDIN as expected. I will search for an open issue and if not, maybe open a fresh one with this thread as a reference. Thanks for reporting your findings.

**Comment by bgnih** [comment]
Workaround: drush sqlq 'source dump.sql;'

**Comment by trathailoi** [comment]
> Workaround: drush sqlq 'source dump.sql;'

Thanks, this works for me.

**Comment by terryzwt** [comment]
I still have this problem.

#### on drupal 9
```
Drupal version   : 9.5.11
Site URI         : http://default
DB driver        : mysql
DB hostname      : mariadb
DB port          : 3306
DB username      : root
DB name          : dsf
Database         : Connected
Drupal bootstrap : Successful
Default theme    : dxpr_theme
Admin theme      : seven
PHP binary       : /usr/bin/php82
PHP config       : /etc/php82/php.ini
PHP OS           : Linux
PHP version      : 8.2.19
Drush script     : /var/www/html/vendor/bin/drush
Drush version    : 11.6.0
Drush temp       : /tmp
Drush configs    : /var/www/html/vendor/drush/drush/drush.yml
Install profile  : cloud_orchestrator
Drupal root      : /var/www/html/docroot
Site path        : sites/default
Files, Public    : sites/default/files
Files, Private   : sites/default/files/private
Files, Temp      : /tmp
```

on drush 10
```
Drupal version   : 10.2.5
Site URI         : http://default
DB driver        : mysql
DB hostname      : mariadb
DB port          : 3306
DB username      : root
DB name          : davyin_cms_11x
Database         : Connected
Drupal bootstrap : Successful
Default theme    : dyniva_ui
Admin theme      : claro
PHP binary       : /usr/bin/php82
PHP config       : /etc/php82/php.ini
PHP OS           : Linux
PHP version      : 8.2.19
Drush script     : /var/www/html/bin/drush
Drush version    : 12.5.1.0
Drush temp       : /tmp
Drush configs    : /var/www/html/vendor/drush/drush/drush.yml
Install profile  : dyniva
Drupal root      : /var/www/html/docroot
Site path        : sites/default
Files, Public    : sites/default/files
Files, Temp      : /tmp
```
