### ISSUE TITLE
Rsync message is misleading

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#3867]
Although 049d2a4b36338178c0c7cf89b8e7caf9769524c9 changed the message from "You will delete files in !target and replace with data from !source" to "Replace files in !target with !source?" it is still misleading: rsync doesn't replace files, even the comment "Prompt for confirmation. This is destructive." does not look correct, rsync is typically not destructive. The old message at least made me wonder whether drush deletes all files before running rsync.

**Comment by weitzman** [comment]
I think it replaces files. Changes in source get copied to target. As for destructive, it destroys the target's older copy.

I'm open to different wording.

**Comment by greg-1-anderson** [comment]
I think that the issue here is that rsync *might* be destructive. If you are syncing a folder "foo" and you know there is no "foo" in the destination, then it is definitely not destructive. If "foo" exists, then it certainly will overwrite whatever is there.

Since Drush cannot know in advance if there are any files that will be overwritten, it is safest to warn the user that something might be deleted. If we wanted to be really safe, we could add a flag to have Drush run rsync in dry-run mode first; I think that will report existing files. I typically haven't had a need for that.

I'm also open to different wording for the message.

**Comment by chx** [comment]
Copy new files and override existing files at $target?

**Comment by weitzman** [comment]
Thats really good. Ideally we mention $source as well.

**Comment by chx** [comment]
Copy new and override existing files at $target from $source?
