### ISSUE TITLE
Update @topics for config:pull command

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3897]
Currently `drush config:pull --help` returns the following error.
                                                           

> There are no commands defined in the ""docs" namespace.  
>                                                            
>   Did you mean one of these?                               
>       docs                                                 
>       docs:config  
>

**Comment by weitzman** [comment]
This looks like a bug in AnnotatedCommand. When the docblock is parsed, we store the value of @topics in otherAnnotations as a string (i.e. not an array). Nothing unusual there. The problem comes when we programmatically add a new topic (e.g. Output filters) we convert the existing value to an array without parsing the CSV in the first member. So we get:

**Comment by weitzman** [comment]
See https://github.com/consolidation/annotated-command/pull/183
