### ISSUE TITLE
Error: Use of undefined constant DRUSH_MAJOR_VERSION

### ISSUE THREAD

**Issue by rbraun75** [drush-ops/drush#3988]
**Describe the bug**
After upgrading from 8.1.18 to 8.2.0 I get php error notice on my /admin/modules page.

**To Reproduce**
Upgrade to 8.2.0 and open /admin/modules page in your Drupal 8.6.10 backend.

**Expected behavior**
No notice should appear.

**Actual behavior**
The notice appears.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.2.0
| PHP version     | 7.1
| OS?             | Linux

**Additional information**
`Notice: Use of undefined constant DRUSH_MAJOR_VERSION - assumed 'DRUSH_MAJOR_VERSION' in Drush\Drush::getMajorVersion() (line 68 of .../vendor/drush/drush/lib/Drush/Drush.php).`

It's a call from the webform contrib module:

`Drush\Drush::getMajorVersion() (Line: 1600)
Drupal\webform\WebformHelpManager->initHelp() (Line: 141)`

**Comment by greg-1-anderson** [comment]
Sounds like they are cheat'in a bit. Calling Drush methods directly from a module is not encouraged.

Still, we should support this use case. Fixed in #3990.

**Comment by greg-1-anderson** [comment]
Fixed in HEAD of the `8.x` branch. Could you please test and see if this fixed your use case?

**Comment by rbraun75** [comment]
Fixed.

Thank you very much!

**Comment by jrockowitz** [comment]
@greg-1-anderson Thanks for fixing this and tagging a new release.

Is there a better way for Webform to detect the installed version of Drush.

We are detecting the installed version of Drush so that we can display to correct Drush 8 or 9 command syntax.

![Webforms  Libraries configuration   Webform Demo Site](https://user-images.githubusercontent.com/3537824/54822185-cf59ca00-4c7a-11e9-8c75-5a2679d595dc.png)

**Comment by greg-1-anderson** [comment]
While we discourage modules from calling Drush, detecting the version of Drush to alter help contents is a reasonable reason for doing so. As I said above, we should support this use case, and we do again. `Drush:getMajorVersion()` has always been safe to call from a module, save for during this one version where it was broken accidentally. There should not be many installs of this version, as we did not advertise 8.2.0's release, and 8.2.1 came out shortly thereafter.

However, I would also encourage you to remove the reason for needing to detect the version of Drush. Note that Drush 8.2.1 now has command aliases for all of the `:`-form commands, so `pm:enable` et. al. now work in both Drush 9.x and in Drush 8.x.  You could similarly add the `:`-form commands to the Drush 8.x version of your Drush extension. If you did this, your help text could be invariant on the Drush version.

Finally, I would also like to mention that Drush 8.2.x / Drush 9.6.x introduces a stable extension API. Drush extensions that do not reach too deeply into Drush's internals, and limit themselves to calling just these methods will work in both Drush 8.2.x and Drush 9.6.x and later. Note that shortly, all Drush 8.x users are going to be forced to upgrade to Drush 8.2.x, as drupal.org is turning off the old git URLs, and the newer version of Drush 8 will be required in order to use `pm:download', 'pm:update', et. al.  Once you are comfortable requiring these versions of Drush in Webform, you may drop your `*.drush.inc` files and maintain only the annotated commandfile.

See the [example Drush extension](https://github.com/drush-ops/example-drush-extension) for more information. See PR #1 for simplification of the tests. This PR will require Drush 8.2.2 / Drush 9.6.1, but only during testing.

**Comment by jrockowitz** [comment]
Thanks for the information. I created a [ticket](https://www.drupal.org/project/webform/issues/3042403) in the Webform's issue to update Drush once 8.2.x is required.
