### ISSUE TITLE
Drush 9 pm:security does not report security updates for Drupal core

### ISSUE THREAD

**Issue by ucola** [drush-ops/drush#4007]
**Describe the bug**
We use the command drush pm:security to check if some security updates are available. Right now (last night) the Core was updated to 8.6.13. But my drush only shows 8.6.10.

**To Reproduce**
Execute drush pm:security

**Expected behavior**
I don't know how drush pm:security works. But if we als type directly "composer require drupal/core --with-dependencies" it also not works. If we execute "composer update drupal/core:8.6.13 --with-dependencies" then we became a message that we must also update twig/twig (Error message is - drupal/core 8.6.13 requires twig/twig ^1.38.2 -> satisfiable by twig/twig[1.x-dev, v1.38.2].).
We also test with drush 8, with this version it works! drush pm-updatecode --security-only 

**Actual behavior**
It only installs 8.6.10

**Workaround**
No workaround found yet

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0
| Drupal version? | 8.6.9
| PHP version     | 7.2
| OS?             | Linux

**Additional information**

**Comment by shaysmith** [comment]
In src/Commands/pm/SecurityUpdateCommands.php, you can see that pm:security is referencing a list of outstanding security updates here:
https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x-v2/composer.json

If that list is not updated you get incorrect Security Update information, which seems like an unnecessary security risk for the number of sites that depend on this functionality.

It would be nice if Drush9 hooked into the Update module to show the exact same thing that a site reports on admin/reports/updates. Sites would benefit from having consistent and timely information whether checking via Drush or the updates page.

**Comment by ucola** [comment]
the core update is not a good solution, because not all have installed it and if you install a module with composer, drupal don't know which version the module have... so this modules are not covered over the update module.

**Comment by weitzman** [comment]
If drupal.org starts publishing its update info in a convenient form like drupal-security-advisories does, we'll switch to that. Meanwhile drupal-security-advisories auto-updates via CircleCI so I don think there is much risk in relying on it. Its source of info is the same drupal.org update status XML that the Update module uses.

I can't tell if there is an actual bug here. What exactly is not being reported by pm:security? I do see <8.6.10 at https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x-v2/composer.json so we should be flagging that as insecure.

**Comment by weitzman** [comment]
working for me

```
