### ISSUE TITLE
Drush should warn when running entity-updates on Drupal 8.7.x and higher that it's not going to work

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4070]
**Describe the bug**

Drupal 8.7.x removes the entity update functionality. On this version of Drupal, the 'drush entup' command appears to work, as it gives no error output, but has no effect. 

**To Reproduce**

Upgraded my site to Drupal core 8.7.2. Ran 'drush entup -y'. Ran it again. Ran it again ...

**Expected behavior**

Drush should complain or crash -- basically, tell the user that this command isn't going to work as expect and direct the user to https://www.drupal.org/project/devel_entity_updates

**Actual behavior**

Nothing.

**Workaround**

Download https://www.drupal.org/project/devel_entity_updates

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2
| Drupal version? | 8.7.2
| PHP version     | 7.2
| OS?             | Mac/Linux/Windows

**Comment by weitzman** [comment]
Makes sense.

Also would be nice if someone ported the Drush command in https://git.drupalcode.org/project/devel_entity_updates/blob/8.x-1.x/drush/devel_entity_updates.drush8.inc to Drush9.

**Comment by joachim-n** [comment]
I think it has been. At least, once I installed that module, I was able to run entity updates. 

Looks like it's in https://git.drupalcode.org/project/devel_entity_updates/blob/8.x-1.x/src/Commands/DevelEntityUpdatesCommands.php

**Comment by bradjones1** [comment]
I'm not sure the command from devel belongs "back" in Drush, but it should prompt a failure.

**Comment by weitzman** [comment]
Implemented a check for entup command in #4101. updatedb is still outstanding.

**Comment by mikemccaffrey** [comment]
This doesn't seem like a problem with drush, but rather with drupal core. When the code in the applyUpdates() function was removed, the error that was added should probably have been fatal, rather than E_USER_DEPRECATED, which implies that the function will be removed in the future and so does not trigger a fatal error when it is called.

Even if future versions of drush account for this feature being removed, that doesn't help anyone still using drush 8.x wondering why entity updates are saying that they succeeded, but not actually doing anything.

I created this issue in the core queue: https://www.drupal.org/project/drupal/issues/3078790
