### ISSUE TITLE
How to suppress warnings and notices 

### ISSUE THREAD

**Issue by DanePete** [drush-ops/drush#4074]
**Describe the bug**
when I run a command such as pm:security 
It outputs warnings and notices

**To Reproduce**
run drush pm:security --fields=name --format=json

**Expected behavior**
Ideally i'd like to only get the json returned

**Actual behavior**
You get warnings and notices

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x
| Drupal version? | 8.x
| PHP version     | 7.1
| OS?             | Linux

**Additional information**

**Comment by greg-1-anderson** [comment]
Workaround:  `drush pm:security --fields=name --format=json 2>/dev/null`

This is an often-requested feature, but I know of no other commandline tools that have a flag to disable stderr output. Unsure if we'd ever do that in Drush.

**Comment by weitzman** [comment]
I was hoping that --quiet would suppress the log messages but not the json output. Alas it suppresses both.

**Comment by johnbburg** [comment]
Any guidance on this? our deploy scripts use `--format=json` to parse whether the site is connected to the database before executing more commands. If those warnings are in there, it breaks this step, and causes deploys to fail. 

It's odd, because my local environment does not display the notices, but the remote environment does. I'm not sure on the difference, since they both should have error reporting disabled for this context.

**Comment by weitzman** [comment]
You can test connection to the database with `$(drush sql:connect)` and check for an error exit code.
