### ISSUE TITLE
Something which is unclear with psy/psysh on composer.json

### ISSUE THREAD

**Issue by truls1502** [drush-ops/drush#4075]
**Describe the bug**
Something might be not clear for me regarding `psy/psysh` on the `composer.json` file says `"psy/psysh": "~0.6",`, but when I installed it from `master`-branch then the composer installed `psy/psysh` at version `v0.9.9`? 

But how did it happens? Let me know if I have missed something. 

**To Reproduce**
I have installed from git repo with and without `composer.lock`, you can see below, but both give the same result.
1.
```
Truls-MBP:drush truls1502$ git status | grep "Your branch is up"
Your branch is up to date with 'upstream/master'.
Truls-MBP:drush truls1502$ composer install
...[long list]...
Truls-MBP:drush truls1502$ composer show psy/psysh | grep "version"
versions : * v0.9.9
```
2. (continue)
_Note: `gitreset0` is my own script: `git reset --hard && git clean -ffdx`_
```
Truls-MBP:drush truls1502$ gitreset0 
HEAD is now at ad613152 More docs about dynamic users in site.yml files.
Removing .idea/
Removing sut/core/
Removing sut/modules/
Removing sut/themes/
Removing vendor/
Truls-MBP:drush truls1502$ rm composer.lock 
Truls-MBP:drush truls1502$ composer clearcache
Clearing cache (cache-vcs-dir): /Users/truls1502/.composer/cache/vcs
Clearing cache (cache-repo-dir): /Users/truls1502/.composer/cache/repo
Clearing cache (cache-files-dir): /Users/truls1502/.composer/cache/files
Clearing cache (cache-dir): /Users/truls1502/.composer/cache
All caches cleared.
Truls-MBP:drush truls1502$ composer install 
...[long list]...
Truls-MBP:drush truls1502$ composer show psy/psysh | grep "version"
versions : * v0.9.9
```

**Expected behavior**
I expected `psy/psysh` to have a version 0.6 until 0.6.1, not 0.9.9.

**Actual behavior**
`psy/psysh` showed the version at 0.9.9.

**Comment by greg-1-anderson** [comment]
I don't know what the **intended** purpose of using `~0.6` instead of `^0.6` is. My guess is that we probably copied it from another project. However, the observed behavior is correct. Some package managers behave in the way you describe, but Composer treats `~0.6` exactly the same as `^0.6`. To get the behavior that you  expected under Composer, we would have to use `~0.6.0`, as Composer only constrains the last stipulated version digit with the `~` operator.

My opinion is that the `~` operator should be use rarely-to-never. Version numbers in the "0" series (unstable) are the most useful place for them, because in some cases, unstable projects use minor version bumps to signal breaking changes. However, considering that unstable releases are allowed to make breaking changes in patch releases, and a change in the minor version conversely does not have to mean that there is a breaking change, I sort of think that if you're going to use an unstable package, you might as well just use `^` and take your lumps. The real solution here is that packages should not [fear the 1.0](https://pantheon.io/blog/dont-fear-1-0-rational-project-management-libraries-using-semver).

**Comment by truls1502** [comment]
Ok, but in other project, my psy/psysh has 0.6 because of drush/drush. I am not able to use for example mglaman/drupal-check because drush is using older version. It is the reason I troubleshoot and found it out.

**Comment by greg-1-anderson** [comment]
If `~0.6` is behaving like `~0.6.0` then I am totally in favor of changing it to `^0.6` or `^0.9`. However, by your analysis above, it seems that `~0.6` is behaving like `^0.6` already.

Is Composer

**Comment by greg-1-anderson** [comment]
[According to the documentation](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-), the tilde operator should not be constraining your version os psy/psysh in your project. Have you tried `composer why-not psy/psysh:^9` to see if it's really Drush that's holding back the version you are using?

I'm in favor of changing our version constraint if it's causing problems; I only closed this because I thought no change was necessary.

**Comment by truls1502** [comment]
Here is the result:
```
Truls-MBP:.composer truls1502$ composer why-not psy/psysh:^9
drush/drush                9.6.2  requires  psy/psysh (~0.6)  
pantheon-systems/terminus  2.0.1  requires  psy/psysh (^0.8)  
Truls-MBP:.composer truls1502$ composer show psy/psysh | grep "version"
versions : * v0.8.18
```

**Comment by greg-1-anderson** [comment]
@truls1502 That's very odd, because if Drush were constraining the version, you'd be on 0.6 something. It shouldn't be Terminus constraining it, because Terminus is using `^`.

Try removing your composer.lock file and your vendor directory, then run `composer update` and see if that lets you float up to the latest version.

**Comment by truls1502** [comment]
It worked now by using `cgr` solution, but what is the reason behind is still a bit unclear for my global composer. But in this case, I would suggest having `^` instead of `~` if starting with 0.  😊 

Thank you for the interesting article even when it is 3 years old: [fear 1.0](https://pantheon.io/blog/dont-fear-1-0-rational-project-management-libraries-using-semver)
