### ISSUE TITLE
Errors with STDERR and STDOUT

### ISSUE THREAD

**Issue by ryanlrobinson** [drush-ops/drush#4096]
**Describe the bug**
These error messages appear repeatedly to start an email message sent from CiviCRM on a Drupal site with Drush involved.

```
Warning: Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP) in /home/mcec/local/drush/lib/Drush/Log/Logger.php on line 144

Warning: fwrite() expects parameter 1 to be resource, string given in /home/mcec/local/drush/includes/output.inc on line 45
```

**To Reproduce**
From CiviCRM, Mailings -> New Mailing.
Prepare a mailing in the usual way. As far as I can tell, the content of the message is irrelevant to the problem.
Click Next and Submit the mailing to Send Immediately.
Wait for the next scheduled job to run, which relies on drush from a crontab.

It's quite possible these errors are happening in other drush scenarios but not as obvious as putting in the text of an email to hundreds of people.

**Expected behavior**
Same thing - the email sends - but with no errors.

**Actual behavior**
The emails did send, but with those errors before the email content. Several emails also bounced back, probably because the errors make spam filters reject them.

**Workaround**
Is there another way to do the desired action?

### System Configuration
Drush version 8.2.4.-dev
Drupal version 7.67
PHP version     7.2.19
CiviCRM version 5.14.0
Linux web server

###Fix
I fixed the first error relatively easily: went to the cited line in the code and changed STDERR to 'STDERR'.

I did not get very far in attempts to fix the second error.

**Comment by greg-1-anderson** [comment]
@ryanlrobinson The error message you are encountering indicates that you are running Drush with php-cgi instead of php-cli. This configuration is not supported. Please use php-cli.

**Comment by martinh-pw** [comment]
Greg's answer is to the point, but not really helpful to solve the problem for those who just want to get this working. To get cron to work in this situation, the documentation here provides an approach that has worked for me: http://docs.drush.org/en/master/cron/

Normally you can add something along these lines to your crontab to run a drush command (such as `drush cron`):
`*/15 * * * * /home/mysite/local/bin/drush -q -r /home/mysite/public_html cron`

However in the situation above (in our case caused by being in a cpanel environment), the docs above advise something like this (note that this is all one line):
`*/15 * * * * cd /home/mysite/public_html && /usr/bin/env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin COLUMNS=72 /home/mysite/local/bin/drush -q -r /home/mcec/public_html cron`
