### ISSUE TITLE
Does the --source argument affect how drush config-import works?

### ISSUE THREAD

**Issue by ChexWarrior** [drush-ops/drush#4159]
**Describe the bug**
I have a setup where any configuration items dealing with [webforms](https://www.drupal.org/project/webform) should be ignored.  To that end I've installed the [Config Ignore](https://www.drupal.org/project/config_ignore) module and added the pattern `webform.webforms.*` to ensure all webform config is ignored (beyond basic settings).  

When I run `drush config-import --source=$SYNC_DIR` I still see all webform configuration included in the list of files to be imported, however when I run `drush config-import` without the `--source` argument I see that all webform configuration is being ignored as expected. 

**Does including the `--source` argument modify how drush starts the import process which somehow doesn't respect the rules set by Config Ignore?**

I should note that the default sync directory defined in `settings.php` is the same as the value for `$SYNC_DIR` passed to the `--source` argument.

**To Reproduce**
Setup a site with Webforms and Config Ignore.  Include the pattern `webform.webforms.*` in the Config Ignore admin page.  Attempt to import some config that includes webform config using `drush-config import --source=$SYNC_DIR`.  You will see all the webform config in the list of files to be imported.  Try this again without the `--source` dir and ensure that the default sync directory is the same as `$SYNC_DIR`, this time the webform config is ignored.

**Expected behavior**
I expected webform config to be ignored regardless of the presence or absence of the `--source` argument.

**Actual behavior**
Including the `--source` argument causes the import process to not respect ignore rules created by Config Ignore.

**Workaround**
N/A

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.3.0
| Drupal version? | 8.6.17
| PHP version     | PHP 7.2
| OS?             | Alpine Linux (container) (Mac on host)

**Additional information**
N/A

**Comment by bircher** [comment]
To answer the question in the issue title: yes it does.
It is a known and expected behaviour.

Config Ignore uses the api provided by the contrib Config Filter module. The way that works is by massaging the config sync store data. Drush works with that because it uses the default sync storage service when no argument is passed to the commands. But when using another directory to load the config from config filter can not filter it and so config ignore can not ignore your webform config.

We will need #4061 and then Config Filter 2.x and then it will work. But that also predicates on work be done in CMI 2 in Drupal core.

Just don't use the `--source` argument, if you need to have it dynamic then set the config directory with a environment variable and set it for your drush command.

**Comment by ChexWarrior** [comment]
Thank you for clearing that up!
