### ISSUE TITLE
Is it possible to run different drush version while using Drush-launcher?

### ISSUE THREAD

**Issue by zomorod** [drush-ops/drush#4240]
Hi there,

I am trying to find a way to run a specific of Drush version on different Drupal sites. I know is not recommended and you recommended to install Drush via composer but I really need to.

I have set up some alias like `drush9` and `drush8`. For testing purposes, I need to run different version for drush. But I have the Drush-launcher that will run drush from vendor folder.

Is there any flag to use for Drush-launcher to say to NOT use the drush in the vendor folder, and use my alias like drush8 or drush9?

Or 

Can you recommend and alternative way to help me to use Drush-launcher as default but also have an option to run my preferred Drush version?

Thank you,

**Comment by Chi-teck** [comment]
You can replace Drush launcher with custom shell script.

**Comment by greg-1-anderson** [comment]
Another simple solution is to add `vendor/bin` to your `$PATH` as a relative path; then you can just make sure that your cwd is at your project root or Drupal root and run the site-local Drush directly.

```
export PATH="../vendor/bin:/vendor/bin:$PATH"
```

No launcher required.

**Comment by greg-1-anderson** [comment]
Oh, I actually see that the OP wants to run different versions of Drush on the same site. That won't work, because if you have a site-local Drush, then that's the only one you can use. You'd almost certainly get dependency conflicts if you tried to disable the things in Drush that prevent you from using a global Drush when there's a site-local Drush present.

In order to use a global Drush with a Drupal site, you need to remove the site-local Drush. It's not recommended to use a global Drush 9 or Drush 10, though, which makes it difficult to use multiple versions of Drush on the same site. Your best option is a slow option - remove the installed site-local Drush, and then re-install the version you want to switch to.
