### ISSUE TITLE
league/container v2 has deprecated dependency of container-interop/container-interop

### ISSUE THREAD

**Issue by back-2-95** [drush-ops/drush#4278]
**Describe the bug**
Composer commands will warn with `Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.` when Drush is required.

**To Reproduce**
Require drush in your composer.json

**Expected behavior**
No warnings. Yellow background messages.

**Actual behavior**
Getting a warning.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 8.x
| PHP version     | 7.x
| OS?             | Mac/Linux

**Comment by weitzman** [comment]
Please let league/container know. We cant change this.

**Comment by greg-1-anderson** [comment]
We can [upgrade to lague/container v3.x](https://github.com/thephpleague/container/blob/3.3.0/composer.json#L25).

This will need to happen in Robo et. al. first, though. Not sure if we can support league/container v2 and v3 at the same time.

**Comment by danepowell** [comment]
Additionally, league/container is [officially unsupported](https://container.thephpleague.com/) as of more than a year ago.

**Comment by Pasqualle** [comment]
The Robo issue is fixed now.
@greg-1-anderson  What I do not understand why are you considering to support two versions of league/container? Switching to version 3 would break some drush plugins?

**Comment by greg-1-anderson** [comment]
If we supported two versions of league/container, then we could have put league/container into Robo 2.x.  However, we instead went the route of supporting only league/container 3.x in Robo 3.x, and kept Robo 2.x and earlier on league/container 2x.

Drush will need a stable release of Robo 3 in order to upgrade to it. This upgrade should for the most part not affect Drush plugins / command files. It theoretically is a b/c break, as Drush commands could in theory use the league/container API to manipulate the DI container. I don't know that anyone does that, but to be rigorous, Drush should also bump its major version when upgrading to league/container 3.x.

If for some reason we wanted to ensure compatibility with old code, well, that might be possible with some sort of b/c shim. I don't know that we want to assume that technical debt; a number of methods changed name in 3.x.

**Comment by greg-1-anderson** [comment]
The other question is whether this is actually causing any active problems for anyone. I tend to think not, but if it were, it might speed the stable release of Robo 3. There's not a lot left to do there, but I don't have brain-share to work on it right now.

**Comment by markdorison** [comment]
> Drush will need a stable release of Robo 3 in order to upgrade to it. This upgrade should for the most part not affect Drush plugins / command files. It theoretically is a b/c break, as Drush commands could in theory use the league/container API to manipulate the DI container. I don't know that anyone does that, but to be rigorous, Drush should also bump its major version when upgrading to league/container 3.x.

> I tend to think not, but if it were, it might speed the stable release of Robo 3. There's not a lot left to do there, but I don't have brain-share to work on it right now.

It looks like since @greg-1-anderson's comments above, there are now [3.0.x releases for Robo](https://packagist.org/packages/consolidation/robo). Does that help unblock this?

**Comment by greg-1-anderson** [comment]
I think this was mentioned in another thread somewhere, but presently, Drush is using an old version of league/container 2.x which did not declare that it is incompatible with php8 (because it is too old for that). Drush happens to work on php8 because it does not use any of the features of league/container 2.x that break on that version.

So, I don't think we need league/container v3 for Drush 10. We are planning on upgrading to Robo 3 in Drush 11.

**Comment by claudiu-cristea** [comment]
Note: It seems that an League Container 4.x version is also coming. At least I see movement in the branch

**Comment by claudiu-cristea** [comment]
@greg-1-anderson BTW, I see the latest 3.x stable version (3.3.5) is PHP 8 compatible. I've also scanned Drush for League Container methods that were renamed between 2.x and 3.x and, on a first look, it seems that Drush don't use any of them.

**Comment by weitzman** [comment]
We are on League 3 now
