### ISSUE TITLE
Specify config directory on site install

### ISSUE THREAD

**Issue by chilaa** [drush-ops/drush#4326]
Am trying to install site from config, where settings.php does not exist, so I need to give config path in install command, on newer versions this parameter is no longer available, would be great if you could add or give default path like `config/sync` or something

**Comment by weitzman** [comment]
If the Drupal installer supports specifying this then I'll add an option to drush site:install. I'm not sure that it does.

**Comment by weitzman** [comment]
Please comment here if the Drupal installer ever starts supporting this.

**Comment by JorisVanEijden** [comment]
Drush 10.2.2 _does_ have the `--config-dir` option. You just cannot use it in combination with the `--existing-config` option because that tries to get the location from the non-existent settings to verify the directory exists.

I believe this is a bug that can be solved by checking for the specified `config-dir` if it is passed rather than the one from `drush_config_get_config_directory()`
Like in PR #4391
