### ISSUE TITLE
Drush should require the correct minimum version of Robo

### ISSUE THREAD

**Issue by flyke** [drush-ops/drush#4352]
**Describe the bug**
After updating drush from version 9 to version 10 I get this error on each drush command,
like: `drush cr` or `drush status`
`[preflight] Alias (parameterInjection) is not being managed by the container`

**To Reproduce**
working website with Drupal core 8.8.2
drush and all drush commands were working fine with Drush 9.0.0-beta7
updated drush to Drush 10 with: `composer require drush/drush --update-with-dependencies`
update went fine without any problems
after update I get the error on every drush command I try
Important information: I am using Lando. I updated my Lando config to use drush 10 also and used `lando rebuild` which did also update the drush version of the lando container.

**Expected behavior**
Updating drush from v9 to v10 would still keep drush workinf

**Actual behavior**
Updating drush from v9 to v10 causes all drush commands to error: "[preflight] Alias (parameterInjection) is not being managed by the container."

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 8.8.2
| PHP version     | 7.2.28
| OS?             | Windows

**Comment by greg-1-anderson** [comment]
`parameterInjection` is provided by consolidation/robo. Drush's version requirement for Robo should be constraining it to only allow a version that contains `parameterInjection` .

What does `composer info consolidation/robo` say the version of Robo is?

**Comment by flyke** [comment]
I was unable to fix this error on my project. Strange thing is I tried rebuilding lando, even restarting my pc, and I always got that error.
BUT, I had to work on a different project this afternoon, so I stopped working on this project as it was (still with the error), stopped my lando container, worked on my other project, and now that I'm finished with the other project, I resumed my project with the drush error, booted it up again (lando start) and strange enough, this time everything is working.

I cannot wrap my head around it but it always failed, I changed nothing and now its working.
My feeling is that it is some sort of Lando chache stuff that I do not know about.

At this moment, `composer info consolidation/robo` gives me:
`name     : consolidation/robo
descrip. : Modern task runner
keywords :
versions : * 1.3.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/consolidation/Robo.git 31f2d2562c4e1dcde70f2659eefd59aa9c7f5b2d
dist     : [zip] https://api.github.com/repos/consolidation/Robo/zipball/31f2d2562c4e1dcde70f2659eefd59aa9c7f5b2d 31f2d2562c4e1dcde70f2659eefd59aa9c7f5b2d
path     : C:\projects\maxus\vendor\consolidation\robo
names    : consolidation/robo, codegyre/robo

autoload
psr-4
Robo\ => src

requires
consolidation/annotated-command ^2.8.2
consolidation/config ^1.0.10
consolidation/log ~1
consolidation/output-formatters ^3.1.13
consolidation/self-update ^1
g1a/composer-test-scenarios ^2
grasmash/yaml-expander ^1.3
league/container ^2.2
php >=5.5.0
symfony/console ^2.8|^3|^4
symfony/event-dispatcher ^2.5|^3|^4
symfony/filesystem ^2.5|^3|^4
symfony/finder ^2.5|^3|^4
symfony/process ^2.5|^3|^4

requires (dev)
codeception/aspect-mock ^1|^2.1.1
codeception/base ^2.3.7
codeception/verify ^0.3.2
goaop/framework ~2.1.2
goaop/parser-reflection ^1.1.0
natxet/cssmin 3.0.4
nikic/php-parser ^3.1.5
patchwork/jsqueeze ~2
pear/archive_tar ^1.4.2
phpunit/php-code-coverage ~2|~4
satooshi/php-coveralls ^2
squizlabs/php_codesniffer ^2.8

suggests
henrikbjorn/lurker For monitoring filesystem changes in taskWatch
natxet/CssMin For minifying CSS files in taskMinify
patchwork/jsqueeze For minifying JS files in taskMinify
pear/archive_tar Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.

replaces
codegyre/robo < 1.0`

Sorry for the issue report, looking at this trange behavior I have a feeling that it must be Lando cache related, even though error remained after restarting my pc.

**Comment by markdorison** [comment]
@greg-1-anderson I am experiencing this same issue. Apologies for tagging you but I did not want to create a duplicate issue.

I currently have consolidation/robo version `1.4.9` installed. Restarting my environment did not solve the issue.

**Comment by greg-1-anderson** [comment]
Drush is just asking for Robo ^1 or ^2, which is insufficient. Maybe you updated Drush without using `--with-dependencies`?

Try `composer update consolidation/robo` and see if that fixes it.

**Comment by weitzman** [comment]
@greg-1-anderson What constraints would be sufficient?

**Comment by markdorison** [comment]
> Try composer update consolidation/robo and see if that fixes it.

That did not solve it, but building my development environment from scratch did. 

Just in case others experience this, I am running Lando in this instance. A `lando rebuild` was not sufficient. I had to run `lando destroy`.

**Comment by greg-1-anderson** [comment]
I'd just use the current 1.x and 2.x versions of Robo as the permitted minimums going forward.

**Comment by pfrenssen** [comment]
> I'd just use the current 1.x and 2.x versions of Robo as the permitted minimums going forward.

That is quite restrictive and could cause B/C problems, especially with changes to dependencies. I see that practically the entire dependency chain changes between Robo 1.0.0 and 1.4.12. Any of thosie changes could be hitting some constraints on certain environments, preventing the latest version of Drush from being installed.

Let's instead do an effort to put minimum values that work. Ideally we would set up a CI pipeline using `composer update --prefer-lowest` but this can be a lot of work. For now let's find it empirically :)

I did some testing using historic versions and there are indeed some problems with ancient versions of Robo.

*Robo 1.0.0-1.0.5*

Error: `Fatal error: Uncaught Error: Class 'Robo\Config\Config' not found in /home/pieter/v/contrib/cas_mock_server/vendor/drush/drush/src/Preflight/PreflightArgs.php:123`

This is due to the refactoring of `\Robo\Config` to `Robo\Config\Config` which was released in 1.0.6, ref https://github.com/consolidation/Robo/pull/552

*Robo 1.0.6-1.1.1*

Error: `Fatal error: Uncaught TypeError: Argument 3 passed to Robo\Robo::configureContainer() must be an instance of Robo\Config\Config, instance of Drush\Config\DrushConfig given, called in /home/pieter/v/contrib/cas_mock_server/vendor/drush/drush/src/Runtime/DependencyInjection.php on line 56 and defined in /home/pieter/v/contrib/cas_mock_server/vendor/consolidation/robo/src/Robo.php:177`

This is due to the introduction of the `ConfigInterface` which was released in 1.1.2, ref https://github.com/consolidation/Robo/pull/608

*Robo 1.1.2-1.1.3*

Error: `Fatal error: Could not check compatibility between Drush\Boot\BootstrapHook::initialize(Symfony\Component\Console\Input\InputInterface $input, Consolidation\AnnotatedCommand\AnnotationData $annotationData) and Consolidation\AnnotatedCommand\Hooks\InitializeHookInterface::initialize(Symfony\Component\Console\Input\InputInterface $input, Consolidation\AnnotatedCommand\Hooks\Annotation $annotationData), because class Consolidation\AnnotatedCommand\Hooks\Annotation is not available in /home/pieter/v/contrib/cas_mock_server/vendor/drush/drush/src/Boot/BootstrapHook.php on line 23`

This is due to a dependency on consolidation/annotated-command 2.2 which is not compatible. We don't directly depend on this package (maybe we should?) but it was fixed in Robo 1.1.4, ref https://github.com/consolidation/Robo/pull/636

*Robo 1.1.4-...*

These seem to be working fine.

*Robo 1.1.4-1.4.12*

Working fine.

*Annotated Command 2.2

**Comment by pfrenssen** [comment]
Hold on I am now seeing the `[preflight] Alias (parameterInjection) is not being managed by the container` warning on some versions I need to check some more versions.

**Comment by pfrenssen** [comment]
* Robo 1.1.4-1.3.4: `Warning: `[preflight] Alias (parameterInjection) is not being managed by the container`
* Robo 1.4.0-1.4.1: OK
* Robo 1.4.2-1.4.4: `[preflight] Alias (parameterInjection) is not being managed by the container`
* Robo 1.4.5: `Fatal error: Trait method getConfig has not been applied, because there are collisions with other trait methods on Drush\Config\ConfigAwareTrait`
* Robo 1.4.6-1.4.10: `[preflight] Alias (parameterInjection) is not being managed by the container`
* Robo 1.4.11-1.4.12: OK

**Comment by pfrenssen** [comment]
Updated the PR to require Robo 1.4.11 or higher.
