### ISSUE TITLE
Ability to use variables in .make files

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#456]
It would be good to use e.g. system variables in .make files, so make process could be more dynamic.
Or any other ways to pass some variables into .make files.

Example scenario:
I've got repo on drupal.org with mirror on GitHub and few other forks. Code in repos are not always in sync, so sometimes you've to use different repo urls (projects[foo][download][url]). You could use separate .make files for each one, but as the project become more complex, it'll require more and more separate .make files to meet the build criteria.

**Comment by ergonlogic** [comment]
How would you envision setting such variables, provide defaults and so forth? I think an easier and more maintainable solution might be to provide an option to load one or more include makefiles. This would allow you to override entries in the main makefile.

So this might look like:

    drush make example.make --includes=github.make,sandboxes.make,devel.make

While `example.make` might specify core and a bunch of contrib, including some of your own modules hosted on d.o. `github.make` could specify download urls for your projects, `sandboxes.make`could specify some sandboxes to use instead of the released projects, and `devel.make`could add devel and other projects that you might only want to run in dev environments.

**Comment by ergonlogic** [comment]
I believe the solution in #1790 would provide a mechanism to accomplish something along these lines. Feel free to open another feature request if there are requirements that wouldn't be satisfied by that solution.
