### ISSUE TITLE
Install over composer failed

### ISSUE THREAD

**Issue by HauRuck** [drush-ops/drush#457]
Greetings,

I'm trying to install drush on a ubuntu 12.04 vagrant from puphpet.com, it already has composer installed.

---

$ composer global require drush/drush:6.*
Changed current directory to /home/vagrant/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Removing drush/drush (6.1.0)
- Installing drush/drush (6.2.0)
  Downloading: 100%  

Writing lock file
Generating autoload files

---

so far so good but when trying to run drush ubuntu thinks that drush in not installed:

---

$ drush dl drupal
The program 'drush' is currently not installed.  You can install it by typing:
sudo apt-get install drush

---

I did "Make sure Composer's global bin directory is on the system PATH (recommended):" before installing, what else could I be missing?

thanx

**Comment by skyred** [comment]
My fix was:

````
nano ~/.bashrc
# Add composer bin to the path, I installed one composer for all projects
export PATH=~/.composer/vendor/bin:$PATH
# Save& Exit
source ~/.bashrc
````

**Comment by webdobe** [comment]
I noticed when running on Ubuntu 16.04:
`composer global require drush/drush`
It says: Changed current directory to /home/myusername/.config/composer
This is something to make sure because you have to put that path in your .bashrc...
`export PATH=~/.config/composer/vendor/bin:$PATH` otherwise when running drush it will goto wrong vendor directory.

**Comment by eworwa** [comment]
This solve my problem on Ubuntu 16.04.
