### ISSUE TITLE
Remove support for Drush as a global project

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#4674]
Folks can use [Drush Launcher](https://github.com/drush-ops/drush-launcher) or any of the alternatives described there.

**Comment by weitzman** [comment]
Remove RedispatchToSiteLocal class and its call in \Drush\Preflight\Preflight::preflight

**Comment by greg-1-anderson** [comment]
@weitzman Drush launcher doesn't support aliases, and it seems that adding alias support there isn't gaining traction.

Instead of removing redispatchToSiteLocal, maybe instead we should only simplify the bootstrap logic, so that Drush can only bootstrap a Drupal site that it shares a `vendor` directory with.

This would allow us to retain the global Drush as an alias-aware launcher, and would also give us a place to put `archive:restore`.

**Comment by weitzman** [comment]
That makes sense, I think.

**Comment by weitzman** [comment]
See #5521. drush can still be used as a global drush (unsupported) but a site-local version is still required.
