### ISSUE TITLE
migrate import --limit and --idlist do not work

### ISSUE THREAD

**Issue by quietone1** [drush-ops/drush#4679]
**Describe the bug**
The --limit option and the --idlist option are ignored.

**To Reproduce**

Install drush
```
 (9.2.x)$ ddev composer require drush/drush
```

Set the database key to point to the Drupal 7 test fixture. Use the --limit option and the --idlist option with the d7_node_type migration. With --limit and --idlist I tried to import one row but in all cases all 7 rows are imported.

I also tried the commands from the console, after a `ddev ssh`. Also tried putting the option at the end of the command `drush mim d7_node --limit=1` and got the same results.
```
$ ddev drush mim --limit=1 d7_node_type
 7/7 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Processed 7 items (7 created, 0 updated, 0 failed, 0 ignored) in 1.4 seconds (300.3/min) - done with 'd7_node_type'
$ ddev drush mr d7_node_type
 7/7 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Rolled back 7 items - done with 'd7_node_type'
$ ddev drush mim --idlist='et' d7_node_type
 7/7 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Processed 7 items (7 created, 0 updated, 0 failed, 0 ignored) in 1.4 seconds (297.5/min) - done with 'd7_node_type'
$ ddev drush mr d7_node_type
 7/7 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Rolled back 7 items - done with 'd7_node_type'
$ ddev drush mim --idlist=et d7_node_type
 7/7 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Processed 7 items (7 created, 0 updated, 0 failed, 0 ignored) in 1.5 seconds (288.4/min) - done with 'd7_node_type'
```

**Expected behavior**
That with --limit=1 or one row would be imported and with --idlist=et one row would be imported.

**Actual behavior**
Every node_type was imported.

**Workaround**
I wish I knew. Every attempt at installing drush 9 or an earlier version of drush fails with various conflicts.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.0
| Drupal version? | 9.2.x
| PHP version     | PHP 7.3.25
| OS?             | Linux

**Additional information**

**Comment by quietone1** [comment]
Took a moment to run `drush mim --limit=1 d7_user` with the debugger. It looks like --limit works depends on the MigratePrepareRowEvent. That doesn't appear to happen, it never stops at the breakpoint in the first line of `public function onPrepareRow(MigratePrepareRowEvent $event): void`

That is all I can do now.

**Comment by gwulo** [comment]
I'm having the same problem. I'm starting work on migrating our D7 to D9, and ran the users migration. The migrate:import command ignores the values of --limit or --idlist and just imports all users. As we have thousands of users, nodes, etc, it will make testing the migration very slow.

**Workaround**
Would it be better to start again with a D7 to D8 migration? That would allow me to use the Migrate Tools module which hopefully would use the --limit / --idlist parameters. Then once the migration is finished, I'll update the site from D8 to D9.

Q | A
-- | --
Drush version? | 10.4.2
Drupal version? | 9.1.5
PHP version | PHP 7.4.15
OS? | XAMPP 3.2.4 on Win10

**Comment by gwulo** [comment]
I confirm that when using migrate:import to run a migration, the onPrepareRow() function in MigrateExecutable.php is never called, so the bug looks to be that event MigrateRunnerEvents::DRUSH_MIGRATE_PREPARE_ROW is never fired.

Until the bug is fixed, a kludgy workaround to get the --limit parameter working again is to paste this into onPostRowSave():
`$this->counter++;		
if ($this->limit && $this->counter >= $this->limit) {
  $event->getMigration()->interruptMigration(MigrationInterface::RESULT_COMPLETED);
}`

onPostRowSave() does get called, so after 'limit' saves that will terminate the migration.

**Comment by gaelg** [comment]
`onPrepareRow()` should be triggered by `system_migrate_prepare_row()` in migrate_runner.inc

But this hook implementation is never called, despite `$result_hook = $this->getModuleHandler()->invokeAll('migrate_prepare_row', [$row, $this, $this->migration]);` is called, in `SourcePluginBase::prepareRow()`

The hook seems undetected, probably because it's not in a module, or because the file is not included at the time hooks are detected.

**Comment by Berdir** [comment]
Stumbled over this as well. Workaround is to copy that hook implementation into your module.

**Comment by thafner** [comment]
@Berdir can you provide an example of what you're talking about?  What hook implementation

**Comment by Berdir** [comment]
the one mentioned in the comment above: system_migrate_prepare_row(), it's somewhere in the drush folder.

**Comment by claudiu-cristea** [comment]
@Berdir, is interesting that we have test coverage for dispatching that event and the test passes https://github.com/drush-ops/drush/blob/10.x/tests/functional/MigrateRunnerTest.php#L162. Debugging the test, I was also able to hit a break-point inside `system_migrate_prepare_row()`. Most likely the source of this bug is that, on CLI, the hook implementation is bypassed because the implementations are read from cache. But why it behaves different in tests?

**Comment by Berdir** [comment]
I assume that the test somehow results in loading that file, and at regular runtime that doesn't happen in the same way. I see that the file is loaded in https://github.com/drush-ops/drush/blob/92a5742961b80d7cd39531510b037b4d3911d550/src/Drupal/Commands/core/MigrateRunnerCommands.php, in the import command. If there are any other commands that might trigger this hook then it would be cached without knowledge that it exists.

Maybe just put that file into composer autoload so that every request loads it? Or just put it in the Migrate runner class file?

**Comment by claudiu-cristea** [comment]
I've managed to replicate the error in tests. See #4833

**Comment by claudiu-cristea** [comment]
OK, #4833 is green. Could anyone test also manually, @thafner, @gaelg?

**Comment by thafner** [comment]
#4833 works for me.  Thanks for implementing this fix!
