### ISSUE TITLE
drush updb -y --quiet does not work in newest version

### ISSUE THREAD

**Issue by hannsen** [drush-ops/drush#4805]
**Describe the bug**
`drush updb -y --quiet ` does not run update hooks in the newest drush version 10.5.1

**To Reproduce**

1. Have update hooks that need to be run
3. Run `drush updb -y --quiet `
5. Then run `drush updbst` and see that no update hook was executed

**Expected behavior**
Run the update hooks

**Actual behavior**
Does not run the update hooks
**Workaround**
Do not use the --quiet flag

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.5.1 (newest as of now)
| Drupal version? | 8.9.18
| PHP version     | 7.4
| OS?             | Linux

**Additional information**
-

**Comment by weitzman** [comment]
Is it that no updates are found or something else? Is there an error?

**Comment by weitzman** [comment]
I think that updateb:status is not printing anything when --quiet is passed along to it, so there are never any updates to perform. This started happenning due to #4755. Maybe redispatchOptions() should not pass along --quiet? Or maybe updatedb and site:install (and others?) should unconditionally remove --quiet when calling sub-commands? ping @greg-1-anderson

**Comment by hannsen** [comment]
`drush updb -y --quiet ` does not produce any output or errors.

Well in any case --quiet should not be passed to `updatedb:status` because then there is no output and drush updb thinks there is nothing to do.

**Comment by hannsen** [comment]
@weitzman I created a PR
