### ISSUE TITLE
[ERROR] Value "all" is invalid 

### ISSUE THREAD

**Issue by maniac-0s** [drush-ops/drush#4852]
when using drush cc I get the following error that does not seem to make sense to me
```

drush cc

 Choose a cache to clear [all]:
  [0] Cancel
  [1] drush
  [2] theme-registry
  [3] router
  [4] css-js
  [5] render
  [6] plugin
  [7] bin
  [8] views
  [9] token
 > all

                                                                                                                        
 [ERROR] Value "all" is invalid                                                                                         

drush v
 Drush version : 9.7.3 

```

**Comment by bradjones1** [comment]
For those of us who have been in Drupal for a hot minute still have muscle memory running `drush cc all` over and over in Drupal 7. In Drupal 8+ it's more... nuanced?

`drush cc` is, basically, a curated list of well-known cache bins/types. I found this issue when I was nostalgically missing `drush cc all` while trying to clear a custom cache bin. Turns out, you can do so by running [`drush cc bin [name]`](https://github.com/drush-ops/drush/pull/3726), though it's not super obvious. See no. 7 on your list. I just learned that... just now.

I think the answer to your question is, `drush cr` is the replacement for `cc all`. If you actually do intend to clear just one bin, use `drush cc`.
