### ISSUE TITLE
drush deploy disregards php's memory_limit parameter

### ISSUE THREAD

**Issue by jcnventura** [drush-ops/drush#4899]
**Describe the bug**
Deploying a site using `drush deploy` is showing me out-of-memory errors even though I'm running it with the following command line:
`php -d memory_limit=-1 vendor/bin/drush deploy`.

**To Reproduce**
Execute `php -d memory_limit=-1 vendor/bin/drush deploy`.

**Expected behavior**
Drush would not run out of memory, and finish deploying the site.

**Actual behavior**
Drush ran out of memory at PHP's configured memory limit.

**Workaround**
Instead of running `drush deploy`, run the following set of commands in sequence:
```
php -d memory_limit=-1 vendor/bin/drush updatedb --no-cache-clear
php -d memory_limit=-1 vendor/bin/drush cache:rebuild
php -d memory_limit=-1 vendor/bin/drush config:import
php -d memory_limit=-1 vendor/bin/drush cache:rebuild
php -d memory_limit=-1 vendor/bin/drush deploy:hook
```

However, this defeats the purpose of having the deploy command. Also it transfers the burden of what exactly the deploy command does back to my CI deploy script.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 9.2.7
| PHP version     | 7.4.25
| OS?             | Linux

**Additional information**
I believe the problem here is that even though the drush deploy command is indeed running in an unlimited memory environment, drush is starting new scripts that do not inherit the memory_limit setting from the deploy command.

**Comment by weitzman** [comment]
Correct. Thats by design. Drush no longer tries to manage your php environment (nor your $PATH). You have to do that before you call drush. The approach that we suggest is at https://github.com/drush-ops/drush/issues/3294#issuecomment-618962852. If you are running `deploy` on a remote machine, you can configure env variables like `PHPRC` and `PATH` in your alias. See `#env-vars` key at https://www.drush.org/latest/site-aliases/#additional-site-alias-options

Also, you should consider a real value for memory_limit instead of disabling it. See https://github.com/drush-ops/drush/issues/1947
