### ISSUE TITLE
Drush does odd things with $_ENV

### ISSUE THREAD

**Issue by frob** [drush-ops/drush#4920]
**Describe the bug**
We recently moved all our credentials out of `settings.php` and now load them dynamically with Environment variables. For Local, Dev, and Stage we set them with a `.env` file and load the content with vlucal/dotenv in a custom  settings include. Everything worked fine in the browser and it wasn't until I went to test the deployment that I found `drush updb` would fail stating that it couldn't connect to the database. 

After much work tracking down the problem I realized that somewhere along the line `$_ENV` was getting emptied. Dotenv was loading once with the `settings.php` file. At some point in the drush bootstrap `$_ENV` would get emptied and then when the `settings.php` file was loaded again dotenv knew that it had already loaded the Environment Variables and not set them again. 

My workaround is to use dotenv's overload functionality to load the Environment Variables even if they where already loaded.

**To Reproduce**
Ran `drush updb` with Environment Variables loaded with vlucal/dotenv

**Expected behavior**
Drush updates would run.

**Actual behavior**
No Dice. Big red box saying that it was unable to connect to the db. Checking `drush st` showed a bootstrapped site with a succsessful connection to the Database.

**Workaround**
My workaround is to use dotenv's overload functionality to load the Environment Variables even if they where already loaded.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10
| Drupal version? | 9.x
| PHP version     | 7.4
| OS?             | CentOS

**Comment by weitzman** [comment]
Drush is not emptying env. Its either dotenv or this php.ini setting

> ; This directive determines which super global arrays are registered when PHP
; starts up. If the register_globals directive is enabled, it also determines
; what order variables are populated into the global space. G,P,C,E & S are
; abbreviations for the following respective super globals: GET, POST, COOKIE,
; ENV and SERVER. There is a performance penalty paid for the registration of
; these arrays and because ENV is not as commonly used as the others, ENV is
; is not recommended on productions servers. You can still get access to
; the environment variables through getenv() should you need to.
; Default Value: "EGPCS"
; Development Value: "GPCS"
; Production Value: "GPCS";
; http://www.php.net/manual/en/ini.core.php#ini.variables-order
variables_order = "GPCS"

**Comment by axi** [comment]
Weird enought, I had the same symptoms and fixed it by using `getenv('')` instead of `$_ENV['']`. Maybe that will lead somebody in the right direction in the future :-)
