### ISSUE TITLE
Display installation warnings (especially for PHP requirements) when using drush si

### ISSUE THREAD

**Issue by xjm** [drush-ops/drush#5103]
**Is your feature request related to a problem? Please describe.**

Drupal has two constants for the minimum PHP version: `\Drupal::MINMUM_PHP` (below which Drupal cannot run at all), and `\Drupal::MINIMUM_SUPPORTED_PHP` (below which sites can be run and updated, but a warning is displayed on update and an error on the status report). This is used to allow sites to continue to receive security updates even if support for their PHP version is being phased out.

Prior to Drupal 9.4, Drupal displayed an error on installation when a site's host had a PHP version between `\Drupal::MINMUM_PHP` and `\Drupal::MINIMUM_SUPPORTED_PHP`, and Drush repeated this error to the user when `drush si` was used to install a site. However, in 9.4 core changes the installation error to a warning, and Drush does not appear to pass installation warnings on to the user.

**Describe the solution you'd like**

Display installation warnings to the user when using `drush si`.

This could be limited to PHP requirements warnings if desired, but honestly it seems like any installation warnings would be useful for the site owner, with a "Continue anyway?" prompt that replicates the UI installer interaction for them.

**Describe alternatives you've considered**
N/A

**Additional context**
[Drupal.org change record for the above change](https://www.drupal.org/node/3267954)

**Comment by bartlangelaan** [comment]
Stumbled upon this Github issue, and may have something to add.

The idea that `install_drupal()` is a one-off function does work great for most usecases, but indeed misses opportunities with altering or splitting up the Drupal install. It is also inconsistent - I have noticed that an install through Drush can produce different results compared to an 'interactive' installation through the browser.
Adding to that, because everything happens in one run, memory issues can appear if you use a custom profile.

Currently, the `install_drupal()` function can be run in two ways: interactive and non-interactive. This however also implies another thing - interactive runs are batched and non-interactive runs will run everything in one run.

If the `install_drupal()` is changed so it supports non-interactive but also batched installations, it is much easier to hook into the installation process by checking the installation state before continuing the next batch. It is also consistent with the 'normal' batch system that Drupal and Drush already have.

This way, the execution of the installation is still fully powered by Drupal - it just uses the batch system like all other Drupal processes already do.
