### ISSUE TITLE
command-event * hook is not invoked for all the commands

### ISSUE THREAD

**Issue by vbouchet31** [drush-ops/drush#5133]
**Describe the bug**
I created a method using `@hook command-event *` which is simply printing the executed command (for debugging purpose, using var_dump($command->getName());).

When I run `drush pm:list`(for example), I can see `string(7) "pm:list"` on top of the usual response so my hook is invoked. However, executing `drush pm:security` (for example) does not show the debug string. Same applies for some other commands (like drush status, drush cr, etc).

I realised the hook is properly invoked for commands in src/Drupal/Commands and contrib modules but not for commands in src/Commands.

**Expected behavior**
The hook should be invoked for all drush commands.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.2
| Drupal version? | 9.3.9
| PHP version     | 7.4.23
| OS?             | Linux

**Comment by weitzman** [comment]
The hook is firing - the issue is that your `@hook command-event *` is not a loaded commandfile yet so it isnt called. you are going to need to create a command that loads very early, during Preflight. It cant be owned by module. From https://www.drush.org/latest/commands/, a Site-side or Global command would fix this.

**Comment by vbouchet31** [comment]
Thanks for the feedback @weitzman. I will check the preflight thing and see if I can apply. Otherwise I will document the limitation with my command.
