### ISSUE TITLE
Minor issue with `drush generate service:custom`

### ISSUE THREAD

**Issue by ultimike** [drush-ops/drush#5267]
**Describe the bug**
A new custom service is placed in the `parameters` section of an existing module_name.services.yml file if the `parameters` section is placed after the `services` section.

**To Reproduce**
1. Create a custom service using `drush generate service:custom`  
2. Manually add a `parameters` section the new module_name.services.yml below the `services` section.
3. Create a second custom service using `drush generate service:custom`  

**Expected behavior**
The second service should be added to the `services` section of module_name.services.yml 

**Actual behavior**
The second service is added to the `parameters` section of module_name.services.yml 

**Workaround**
Either:

1. Be sure to manually add the `parameters` section above the `services` section of module_name.services.yml 
2. Manually move the definition of the second service created to the `services` section.

**Comment by weitzman** [comment]
Thanks for the report

1. This belongs to https://github.com/Chi-teck/drupal-code-generator. Alas I cant transfer it across orgs.
2. I dont think this is fixable because the generator doesnt load the file and parse it for meaning. It just appends. This is a known and accepted limitation AFAIK. @Chi-teck might know otherwise.

**Comment by ultimike** [comment]
Fair enough - I'll close this issue in lieu of a new issue in the proper repo :)

https://github.com/Chi-teck/drupal-code-generator/issues/91

thanks,
-mike
