### ISSUE TITLE
I cannot use Drush on a shared server with PHP 8.1

### ISSUE THREAD

**Issue by bendqh1** [drush-ops/drush#5351]
I have several Drupal 9 websites hosted on a shared server environment (which I can barely configure), on namecheap.com.

 `pdo` and `pdo_mysql` are both installed (as apparent from cPanel -- PHP Tweaks).

I have installed any of these Drupal websites this way:

```shell
cd WEB_APPLICATION_ROOT
composer create-project drupal/recommended-project WEB_APPLICATION_DIR_NAME
cd WEB_APPLICATION_DIR_NAME
composer require drush/drush
vendor/bin/drush site:install
```

After I have upgraded PHP from 7.4 to 8.1 I could no longer use Drush.

Any Drush command I ran on any of these websites, for example, `vendor/bin/drush status` or `vendor/bin/drush updatedb` or `vendor/bin/drush pml` etc, caused the following error:

> Error: Undefined constant PDO::MYSQL_ATTR_USE_BUFFERED_QUERY in Drupal\mysql\Driver\Database\mysql\Connection::open() (line 172 of /example.com/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php).

Strangely, `vendor/bin/drush cache:rebuild` output only "[warning] Drush command terminated abnormally." without the above error.

The only Drush command that worked was `vendor/bin/drush --version` and the output was "Drush Commandline Tool 11.3.2".

---

Since then, I have downgraded PHP back to 7.4 and then Drush came back to work as usual without any error.

`pdo` and `pdo_mysql` were enabled when the PHP version was 8.1 so it's not an issue of not having them enabled and probably a bug.

I am not a PHP programmer and cannot debug this.

**Comment by codeguy** [comment]
I also have this same issue.

**Comment by codeguy** [comment]
On my server, this was caused by php-cli being a different (and newer) version than what was used by php-fpm. I had php8.1-mysql package installed. Site was running via FPM on PHP 8.1.

Run this command to determine the php-fpm version:

```
ps aux | grep fpm | grep master
```

Or log into Drupal as admin and go to `/admin/reports/status` and find the PHP version there.

Next, as root on your server, update the active php-cli version with this command:

```
update-alternatives --config php
```

And set it to the same version as php-fpm.

That fixed this problem for me.

EDIT: To further clarify, I mean you likely have php8.1-* and php8.2-* packages installed, and Ubuntu's environment PATH likely prefers php 8.2 binary when your site is running on PHP FPM 8.1. This discrepancy is what caused this exact issue for me. Making sure Drush uses PHP 8.1 (or whatever version FPM uses) would likely solve the issue.

**Comment by bwtribble** [comment]
I don't know if this is related but I thought I'd throw it out there. In moving a composerized dev Drupal 9 site to live on Siteground hosting, I have encountered the following error when trying to use any drush cmd:

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.14". You are running 7.4.33. in /home/customer/www/xxx/public_html/vendor/composer/platform_check.php on line 24

The Drupal status page reports php 8.1.14. Running php -v reports php 8.1.14. The .htaccess includes: AddHandler application/x-httpd-php81 .php .php5 .php4 .php3

Using composer update works fine, but using any drush cmd throws the error.

Any help would be appreciated.

**Comment by bgnih** [comment]
I fixed this on my new Ubuntu install by installing the php-mysql package with:

`sudo apt install php-mysql; 
sudo service apache2 restart`

**Comment by weitzman** [comment]
Please use Drupal Answers for support
