### ISSUE TITLE
Port Drupal Console `site:mode dev` functionality to Drush.

### ISSUE THREAD

**Issue by trackleft** [drush-ops/drush#5618]
As a novice Drupal developer, I would like a way to quickly and easily put a site into theme development mode with one command.

**Describe the solution you'd like**
Something similar to the way Drupal console does this.
https://github.com/hechoendrupal/drupal-console/blob/7027117c82cd8b9d9f3fb89558a088e0575434d3/src/Command/Site/ModeCommand.php#L65

**Describe alternatives you've considered**
Write a custom script to introduce this functionality.
Manually put each site into development mode when I need it.
Use environment variables and services.local.php

**Additional context**
Drupal Console does not work in PHP version 8.1 and above, which is a requirement of Drupal 10.

Drupal console output for this command looks like this
<img width="866" alt="image" src="https://github.com/drush-ops/drush/assets/1023167/48ba2213-eb11-4048-81cc-c17e9809fb00">

**Comment by gitressa** [comment]
Drupal 10.1 will [Make it easier for theme builders to enable Twig debugging and disable render cache](https://www.drupal.org/project/drupal/issues/3278493) and I created [Enable Twig debugging and disable render cache via Drush and settings.php](https://www.drupal.org/project/drupal/issues/3363676).

There's also [Easy way to bypass all caching](https://www.drupal.org/project/drupal/issues/3342678) which I guess is what this issue is about? Maybe, as in the case of the Twig debug/caching solution, cache disabling for "everything else than theming layer" may need to get build in Drupal, and Drush integration added afterwards?

**Comment by weitzman** [comment]
#5109
