### ISSUE TITLE
Command ecosystem

### ISSUE THREAD

**Issue by xendk** [drush-ops/drush#572]
Having written a few Drush commands, I've repeatedly run into the problem of how/where to host/release them.

Github being the first obvious choice, it's quick, you can run tests on Travis, and seems natural as Drush itself is here.

However, Drupal.org does have the very nice advantage of supporting `drush dl <drush_command>`.

Basically, what I'd really like would be being able to tell people to `drush dl <something>` a Github hosted command. 

I guess that it's quite doable to make Drush understand `drush dl xendk/bandaid`, and do some Github magic, or implement a drush extend xendk/bandaid, but what's the Drush core teams thoughts?

**Comment by ergonlogic** [comment]
I echo @darthsteven's excitement for managing Drush extensions with Composer, as it should greatly simplify custom Aegir installations.

That said, I really like the idea of `drush dl user/project`, even if just for global drush commands. In https://github.com/drush-ops/drush/issues/572#issuecomment-66679665, @greg-1-anderson mentions:

> 4) The global Drush should also have a 'composer.json' file. Folks should install their global Drush extensions here via 'composer require'. Thanks to Packagist for Drupal Projects, it would be possible for 'drush dl foo' to become a wrapper for 'cd /drush/home && composer require drupal/foo'. The autoload file in Drush's global vendor directory is loaded iff the Drupal site that is bootstrapped does not have a composer.json, or if there is no site bootstrapped by this command.

Is that an approach the Drush maintainers would be open to? If so, I'd be happy to start working on a PR.

**Comment by weitzman** [comment]
@ergonlogic - I'm open to it, but can't guarantee a merge. Wrappers have to be thin and foolproof in order to be an improvement over `'cd /drush/home && composer require drupal/foo`. It would really help to have a PR, even an unpolished one.

**Comment by greg-1-anderson** [comment]
Copying here a discussion that happened outside this issue:

There is another alternative for finding the right Drush that I don't think is discussed here.  For folks who use the 'use' command, we could make a variant that alters the PATH such that the drush that goes with the site you selected via 'use' appears first.  The issue here, of course, is that you can't set one of the shell's environment variables from a subprocess, so this would only work if 'use' was a shell alias that first called 'drush use', and then set the PATH if it was necessary to do so.  This could work in conjunction with a global Drush, that would appear first in the PATH when not 'use'-ing a site, or when the 'use'd site is remote.

Also, regarding the idea of one Drush calling some other Drush, this is essentially what happens already when you run 'drush @remote cc all' -- except in this case, the local Drush uses ssh to call the remote Drush w/ a "cc all" command.  In the composer case (per-site, composer-managed Drush, that is), we'd do the same thing, but we'd just call Drush directly.

**Comment by greg-1-anderson** [comment]
As mentioned in #1132, I think we should standardize on using "drupal-drush" as our composer type, rather than "drush-extension".

**Comment by greg-1-anderson** [comment]
I made some progress in #1138.  With this PR, `drush @site foo` will re-launch the site-local copy of Drush associated with @site if it exists.  This was really easy to do--I just used the same mechanism already in place in Drush for doing the same thing when @site is remote.  The behavior of Drush does not change unless someone installs a site-local copy of Drush.

I also set the --local flag, which effectively "breaks" global Drush extensions, unless you copy them into each of your sites.  However, we do not need to stop here; there are other things we can do to make global Drush extension management easier -- maybe even automatic.

I can continue in the same PR, or commit this one and continue with separate PRs for each improvement.

**Comment by greg-1-anderson** [comment]
Okay, here is my new idea.  This replaces most of what I suggested in [1) - 4) above](https://github.com/drush-ops/drush/issues/572#issuecomment-66679665), while maintaining the original vision (a) - (c).

1. Folks can use either a global Drush, or a site-local Drush, per their preference (#1138).
2. When including Drush extensions with a site, you must use a custom autoloader that places them in ROOT/drush or ROOT/sites/all/drush. (Composer installers uses ROOT/drush, composer_generate uses David Barrat's installer and places extensions in ROOT/sites/all/drush.)  This means we do not need to change the logic for how commandfiles are handled just yet.
3. We will provide a function, `drush_autoload()`, that will load a Drush extension's autoload file for it.  Drush will figure out whether the extension was already autoloaded, and will turn drush_autoload() into a no-op if so. This will allow composer-using Drush extensions to work regardless of whether they are included in a site's composer.json file or left independent.
4. We will change the behavior of --local so that, instead of eliminating the global locations, it will instead look for config and commandfiles in ~/.drush/shared (and so on for the other locations).  Thus, whether or not you are using a site-local Drush, you can choose to install your extensions locally or globally.  Just put config or commandfiles in the "shared" directory if you want them to be used in both the site-local and the global environments, and put them anywhere else if you want them to be ignored when using a site-local Drush.
5. We'll need to make sure that we load the Drush commandfiles from the site-local locations BEFORE we look at the shared locations.

I think this should make everyone happy.  If you want to keep using your global Drush extensions the same way you always have, because the autoloader will "usually work" like this, then you can.  If you run into a situation where the autoloader does NOT work like this, then you can just add your global extension into the composer.json of your Drupal site, run composer install, and either Composer will grab the right version for you, or you'll get a useful set of error messages about the specific version incompatibilities that you are experiencing.  Should be just a little more code, and we'll be done.  I think I can wrap it up early next week.

**Comment by greg-1-anderson** [comment]
I realized that (4) and (5) are a mistake.  Rather than adding magic behavior to --local, we can just have folks add additional commandfile include locations in their site-local drushrc.php files.  This does not work today, because Drush only checks for commandfile / config includes once, and it is too late to modify these by the time the site-local config is sourced.  We could change this behavior, though; all we would need to do is remember which locations we already sourced, and test to see if any more were added every time we source another config file.

**Comment by greg-1-anderson** [comment]
Interesting side note.  If you use the composer packagist repository http://drupal-packagist.webflo.io/, it automatically inserts dependencies from Drupal modules to Drupal core, and from Drush extensions to Drush.  See:

See: https://github.com/drupal-composer/drupal-parse-composer/issues/3

Their model is, if you use composer to install a Drupal module, then it is also expected that you are using composer to install Drupal core, and these are part of the same composer project.  This also extends to Drush extensions and Drush--if you install your Drush extension from http://drupal-packagist.webflo.io/, the assumption is that you are using a site-local Drush.

Other packagist repositories do not have this assumption, but I thought it was interesting to mention this here.

**Comment by greg-1-anderson** [comment]
I was looking at https://github.com/wp-cli/wp-cli/wiki/Community-Packages, mentioned above.  The basic mechanism here is that WP-CLI extensions call a "register" function (WP_CLI::add_command) at the bottom of their class file.  They tell composer to include it by adding an entry to "autoload": "files" in their composer.json file.

We could do something similar in Drush; my idea was to add a function `drush_autoload()` that Drush extensions would call, that would automatically register the commandfile (if necessary) and load the autoload.php file (if necessary), so that Drush extensions could be found either the old way (by location) or by including them in a composer.json file reachable from the project's composer.json.

It's close, but there's a wrinkle.

* Drush loads its composer autoload.php file first thing, even before including its core include files, so that said includes have access to autoloaded classes, if they need them.

* If we were using a "register" function in Drush extensions to allow folks to put extensions in the 'vendor' directory (or just to reduce Drush's need to search for commandfiles), then our "register" function would be called at the point in time when Drush loads the autoload.php file.

* This means that anything that the "register" function needs to do could only be accomplished with composer-autoloaded classes, because includes/environment.inc, includes/command.inc & so on are not available yet.   Going the other way, and including some files before composer, would be too fragile, I think.

I've started to experiment with this technique, and have put some code in this branch:  https://github.com/greg-1-anderson/drush/tree/drush-autoload.  There's a big comment in there next to the drush_autoload() function

I'm going to try to make a simple class or two to handle the operation of _drush_add_commandfiles().  I split drush_add_commandfile() out from _drush_add_commandfiles(), which is an improvement in its own right.  If I can do this simply, without moving very much code into classes, then I think we'll be in business.

**Comment by greg-1-anderson** [comment]
More discussion on local-vs-global commandfile management in #1340.

**Comment by greg-1-anderson** [comment]
I recently had to resolve a difficult problem I was having with site-local Drush and Drupal 8.  When I used the d8 site with the global Drush, it worked fine, but the site-local Drush was crashing in the terminate() method.

It turned out that the problem was a `vendor` directory that I had created in my ~/.drush folder via `cd ~/.drush && composer require org/drushextension`.  The result of doing this was that my ~/.drush/vendor directory had a copy of Symfony in it, and the version of Symfony in ~/.drush/vendor was older than the one currently in Drupal 8.  One of the Drush extensions inside of ~/.drush/vendor was including the autoloader from here, which caused a conflict with the identical classes in Drupal 8, leading to mysterious and spectacular failures that were pretty hard to track down.

After this experience ([which other people have also experienced](https://www.drupal.org/node/2405789)), I now firmly and strongly believe that Drush extensions, Drupal modules, and any other manner of plugin should never include any autoload.php file.  Only top-level components (the front controller, Drupal, Drush, Behat, etc.) should include the autoloader.  Plugins should always live in the same autoloader as the app they plug in to.

So, how should a Drush extension insure that its autoloader is included?  The current answer is to call the function `drush_autoload(__FILE__)` from the init function in your Drush extension's commandfile.  This will go ahead and do the deprecated thing, and include your local autoloader if it is necessary; if it is not, the function does nothing.  This allows Drush extensions to work in legacy environments, where the user has installed their extensions in a global vendor directory, and still also work in a site-local Drush environment.  The current implementation of drush_autoload() is not quite right yet, but the point is that calling this function puts Drush in control, so changes to the autoload strategy can happen in one place, when needed.

I am working on strategies for managing Drush extensions from Composer in #1347, but this effort is still in progress.

**Comment by xendk** [comment]
I've been pondering this lately. I've done a few global Drush commands, and lately a few Symfony Console based ones.

I've actually considered re-doing a few of my global Drush commands as stand-alone Symfony Console commands, as their reliance on Drush could be handled as calling Drush as an external command (Symfony Process FTW).  

There's something to be said about installing Drush in the site code (as anyone that's tried drush sql-sync from a local, global, Drush 7 to a remote Drush 6 will know).

My viewpoint might be skewed, but from where I'm looking, global Drush commands is increasingly looking like a wart (a historically useful one, but none the less). I don't know what others have been using global Drush commands for, but in my own experience it's mostly been for commands that could just as well been standalone shell commands that called Drush for some "low-level" Drupal work. 

Back when Drush was still young, creating a command line PHP script was pretty involved, and Drush commands was a welcome shortcut. But with Symfony and Composer, it's become much easier.

I suspect that if you take the total sum of Drush commands, subtract those in modules, and those which is global due to the convenience of not installing it into every site, you'll end up with a small set of global commands that could just as well be done as standalone shell commands.

So I'll back up and suggest letting Drush do what it's named for, being a Drupal shell, not being a Drupal shell sometimes being a generic command runner. Drop global commands, and only have a global configuration file for configuration items that make global sense (overriding the ssh command line and that kind of stuff). 

It'll simplify the code, and some of Drush internals might be rolled out into separate packages that other commands might use (parsing alias files and ssh'ing to aliases to run command is a few I could find a use for). Someone might even create a composer template for shell commands relating to Drupal that'll include a lib for easy running of Drush in backend mode.

It might seem a bit like a step backwards, but I think it'll focus Drush more on it's core value, and I don't think the loss of the global context is that great in the long run.

**Comment by greg-1-anderson** [comment]
I think that it's a good idea to factor some useful libraries out of Drush, for use in other stand-alone cli applications.

**Comment by greg-1-anderson** [comment]
I made an attempt at making Drush detect and report "dependency hell" situations in #1520. Moshe and I just discussed this, and the end conclusion we reached was that this is a hard problem, and Composer was not really designed to solve it.

Moving forward, it looks like we are going to completely disable support for any sort of global Drush commandfile in Drush 8, maybe with some way to opt-in for this behavior, maybe not. 

This will formalize the [recommendation above](https://github.com/drush-ops/drush/issues/572#issuecomment-95159026) as actual Drush policy. Global commandfiles should not be Drush commands, but should instead be written with the Symfony Console component, or something similar, and 'exec' Drush when needed to operate on a Drupal site.

**Comment by ergonlogic** [comment]
So... this issue started off as a request to be able to 'drush dl' extensions directly from github. Now it appears to be deprecating global commandfiles entirely. Is this just limited to installation via Composer, as #1520 suggests? 

Maybe I'm mis-reading this issue (and https://github.com/drush-ops/drush/pull/1513#issuecomment-127406615), but wouldn't that make commands like `drush make` and `drush runserver` impossible to implement as non-core extensions? This seems to apply to 30+ other commands in core, if `'bootstrap' => DRUSH_BOOTSTRAP_NONE,` is anything to go by.

FWIW, I'm fine with limiting automatic search paths, so long as this is still valid in `~/.drush/drushrc.php`:

    $options['include'] = array (
      'example' => '/my/command/that/does/not/need/to/bootstrap/a/drupal/site/',
    ....

**Comment by greg-1-anderson** [comment]
We don't have a firm implementation in mind yet, although allowing opt-in of global locations, e.g. via `$options['include']` in a drushrc.php, will likely be allowed.  I wouldn't be surprised if this facility were also eventually removed, though (e.g. perhaps in Drush 9), if a better solution to these problems are not found by then.

You are correct that the general idea would be to deprecate the concept of providing commands such as `drush make` (which do not bootstrap a Drupal site) as non-core extensions.  However, the definition of "global command" is "not bundled with Drush Core" and "Not installed with a Drupal site".  (Aside: a command could be DRUSH_BOOTSTRAP_NONE, but still call DRUSH_BOOTSTRAP_MAX later, so simply looking at the bootstrap level is not necessarily a good metric for whether a command operates without a Drupal site or not.  Commands that users typically have installed as global commands, but which are used with a Drupal site, can be installed locally with each Drupal site.

The theory is:

1. Most Drush users are content using only the core commands provided by Drush.
2. Of those that use more than just Drush core, most of those only use Drush commands that are bundled with a module (devel, features, etc.)
3. This leaves us with only a fraction of users who need global commands, which Composer makes very hard to support in a way that does not lead to "dependency hell" when multiple copies of the same library, but with different incompatible versions are loaded by the autoloader.

Note that the Drupal Console project gets around this problem in a different way:  it requires that your version of the Drupal Console must match exactly with the version of Drupal that you are running it with.  If you have different versions of Drupal on the same system, then you'll need to install different versions of the Drupal Console in order to use them successfully with your different sites.  Drush needs to work with multiple versions of Drupal, so this is not an option for us.

If a command never needs to bootstrap or target a Drupal site, it is again our theory that such commands do not need to be Drush commands; they could be Symfony console commands.  Drush make could be a Symfony console command, but it is in Drush core, so it does not need to be ported.

**Comment by weitzman** [comment]
This issue has been about several interrelated issues. I think we need to close it and discuss elsewhere.

1. Dependency hell and global commandfiles - #1520 
2. [packages.drush.org](http://packages.drush.org) is a directory of Drush commands installable via Composer (thx @xendk)

**Comment by greg-1-anderson** [comment]
See also #2103.
