### ISSUE TITLE
Install with Composer failed, package pear/console_table:1.1.5 doesn't exists

### ISSUE THREAD

**Issue by blitux** [drush-ops/drush#575]
Hi there, 

When I tried to install drush using composer, it failed because package pear/console_table:1.1.5 doesn't exists in packagist repository. 

Should the version of pear/console_table need to be bumped to 1.2.0?

Thanks.

**Comment by lanoxx** [comment]
I found this issue because I tried to run `composer global require drush/drush:~8.1.17` as I wanted to upgrade from drush version 8.1.8 to 8.1.17.
Composer kept complaining the `pear/console_table` was locked at version 1.3.0 while 1.3.1 was required. 

Eventually I figured out that I had to run `composer global update` to update all installed modules to their latest version which also included an update for Drush. I am leaving this comment here in case anyone else stumbles across this problem.

I also found `composer global info` useful to see whats going on. I am leaving this comment here in case anyone has a similar problem like me and finds this issue.

**Comment by greg-1-anderson** [comment]
Please do not install Drush -- or any other PHP commandline tool -- using `composer global require`. Please use [cgr](https://github.com/consolidation/cgr) instead. See [Fixing the Composer Global command](https://pantheon.io/blog/fixing-composer-global-command).
