### ISSUE TITLE
`drush sql:query --file` doesn't seem to use Drupal's SQLite driver for the connection and fails on missing NOCASE_UTF8 collation

### ISSUE THREAD

**Issue by effulgentsia** [drush-ops/drush#5833]
**Describe the bug**
If I dump a SQLite db with `drush sql:dump` and then try to import it into a different Drupal db with `drush sql:query --file`, it errors out with:
```
no such collation sequence: NOCASE_UTF8  
```
and other errors.

I suspect that this is due to when `drush sql:query` runs that it's not using the Drupal SQLite driver, which [creates that collation](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/sqlite/src/Driver/Database/sqlite/Connection.php?ref_type=heads#L153).

Is this a known issue and is there a known workaround for it?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.2.x
| PHP version     | 8.2
| OS?             | Mac

**Additional information**

**Comment by mglaman** [comment]
I wonder if `\Drush\Sql\SqlSqlite` needs to override `\Drush\Sql\SqlBase::connect` or something to create the collation. It's not opening the connection the same way Drupal core does, because it's acting over the command line.

**Comment by weitzman** [comment]
[sql:dump has a --extra-dump option](https://www.drush.org/12.x/commands/sql_dump/) which can be used to add options to the sqlite3 call. perhaps that would help?

I'm under the impression that folks rarely use sql:dump on sqlite because the Db is already a file. We used to not even support sql:dump on sqlite.

**Comment by dgtlmoon** [comment]
I hit the same problem, basically it means the sqlite3 DB is tied to the machine it was generated on, so for example if you have a very large dump in your backups, you cannot process the sqlite3 DB outside the Drupal environment, and so if your Drupal environment is not working for some reason (like 1 of 6 trillion ways that a Drupal install can fail, dependencies broken in upgrading etc etc) you end up in an endless loop of trying to revive drupal and cleanup your sqlite3 but you cant because you cant use standard command line tools with your sqlite3 database!!!

```
$ ../bin/drush --uri="https://xxxxxxxx.io" sql:cli
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> vacuum;
Error: no such collation sequence: NOCASE_UTF8
```

Weird custom tooling on standard databases... 1 of billions of reasons I do not work with Drupal anymore
