### ISSUE TITLE
archive:dump can't handle filenames longer than 100 characters

### ISSUE THREAD

**Issue by clemorphy** [drush-ops/drush#6009]
**Describe the bug**
The Drush command `archive:dump` can't handle filenames longer than 100 characters

**To Reproduce**
My /config/sync/ folder contains files with names longer than 100 characters. Mainly migration files like :  migrate_plus.migration.upgrade_d7_metatag_field_instance_widget_settings_node_xxxxxxx_xxxxxxxxxxxxx.yml
When executing
`ddev drush archive:dump --code --db --destination=../backups/archive.tar.gz`
it fails, saying that some filenames are too long for the tar format.

**Expected behavior**
I excpect the `archive:dump` command to handle filenames longer than 100 characters.

**Actual behavior**
It fails creating the tar file, and outputs this : 

```
In ArchiveDumpCommands.php line 172:
                                                                                                                                        
  tar-based phar "/tmp/archive.tar" cannot be created, filename "code/config/sync/migrate_plus.migration.upgrade_d7_metatag_field_inst  
  ance_widget_settings_node_xxxxxxx_xxxxxxxxxxxxx.yml" is too long for tar file format                                                  
                                                                                                                                        
Failed to run drush archive:dump --code --db --destination=../backups/archive.tar.gz: exit status 1
```

The limitation seems to come from Php's PharData that drush is using to generate the tar : https://stackoverflow.com/questions/24800217/phardata-limitation-of-file-name-length

**Workaround**
Maybe archive:dump should allow to use an alternative to the tar/PharData solution. I don't know if generating directly a zip file is something doable.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 12.5.1
| Drupal version | 10.2.5
| PHP version     | 8.2.11
| OS?             | Windows, WSL2, DDEV

**Comment by greg-1-anderson** [comment]
This is a limitation of the tar format. The filename part can only be 100 characters long, and the entire path can only be 255 characters long. We would have to switch to a different archive format, as suggested, if we wanted to support this. To preserve backwards compatibility, this switch would have to be an option.

PRs welcome.

**Comment by clemorphy** [comment]
@greg-1-anderson Actually it seems that the limitation is not on the tar format itself. I succedeed in generating a tar directly from a Linux shell with filenames longer than 100 characters. The limitation seems to be on the PHP PharData side.

**Comment by weitzman** [comment]
I'm not inclined to add more code to archive commands for this. Please work on the upstream bug.

**Comment by tgoeg** [comment]
This won't ever get fixed upstream, as PHP regards POSIX ustar compatibility (100 chars) to be definitive:
https://bugs.php.net/bug.php?id=49020

As long as Drupal itself (and the FS below it) allow filenames longer than that, there should be a way to correctly `archive:dump` an installation that is otherwise compliant.

This won't work without using different approaches than PHAR, I guess.

Is cross-OS compatibility a thing (that only allows PHAR) or can we assume (or at least offer, as a switch, e.g. `--use-system-tar`) a GNU tar compliant version that supports as many characters as Drupal itself and the underlying OS support?

The current situation means `archive:dump` cannot be used reliably for any given installation, as this limit might get exceeded, causing automation etc. to break.

@weitzman: Does that change your position on whether code may be added to work around this? I think we should be able to provide a PR.

The following snippet for `src/Commands/core/ArchiveDumpCommands.php` seems to do the job for the dump case at least, no further testing, yet. The `true` would need to be some variable containing the `--use-system-tar` switch's boolean value.
```
if (true) {
    // Use system tar command
    $tarCommand = sprintf('tar -czpf %s -C %s .', escapeshellarg($archivePath . '.gz'), escapeshellarg($this->archiveDir));
    exec($tarCommand, $output, $returnVar);
    if ($returnVar !== 0) {
        throw new Exception(dt('Failed to create archive using system tar'));
    }
} else {
    // Use PHAR
    stream_wrapper_restore('phar');
    $archive = new PharData($archivePath);

    $archive->buildFromDirectory($this->archiveDir);

    $this->logger()->info(dt('Compressing archive...'));
    $this->filesystem->remove($archivePath . '.gz');
    $archive->compress(Phar::GZ);

    unset($archive);
    Phar::unlinkArchive($archivePath);
}
    $archivePath .= '.gz';
```

PS: Using system tar also fixes another issue we see: File permissions are not correctly saved as they are in the original `files/` dir.
