### ISSUE TITLE
Provide a way to not delete files or folders during pm-update drupal

### ISSUE THREAD

**Issue by kgaut** [drush-ops/drush#614]
When running 

```
  drush pm-update drupal 
```

All the files and folder within the rootpath are deleted, drupal's, but also, for example IDE's settings.

It would be nice to provide a way to not delete these files / folders, maybe by a drush.ignore file or by an argument to pm-update command.

What do you think about this idea? Do you have any suggestion ?

**Comment by superbiche** [comment]
This only applies to the .htaccess issue (that was one of the main topic of https://drupal.org/node/1018190): couldn't we write some of the directives we want to keep when upgrading core between .htaccess comment tags, something like #<start drush-keep> and #<end drush-keep>, and add a Drush behavior to catch this block and its contents, the rewrite it in the upgraded .htaccess?
This would make the upgrade process safer, avoid extra manipulation/hooks, and prevent not upgrading .htaccess, which isn't safe either.

Can try to make a PR for this.

**Comment by AdamPS** [comment]
@superbiche Your idea sounds fine, but it is not really part of this issue (maybe more the one you reference?).  This issue is talking about avoiding deleting files that weren't put there by Drupal in the first place.  Drupal does provide .htaccess.

Maybe best if you create a new issue for your idea, or use another one that is is more closely related to continue your discussion?

**Comment by superbiche** [comment]
In the issue I reference, @greg-1-anderson asked to move the debate about this potential feature here on Github. So I'll open a new one here.
Sorry for the inconvenience :)

**Comment by philsward** [comment]
Would it be worth having a .drushignore file within the root of Drupal and anything within that file is ignored (or copied out and copied back)

This would allow the .htaccess and robots.txt issue to be handled a bit better and if there are duplicates, the new one could be re-named.  I realize the existing Drupal files are on another issue, but they do all kind of come together.  Personally, I think one issue should cover all of the use cases until a clear understanding of how to approach each use case is determined, then they can be split off to separate issues.

Right now we have:
Drupal files vs Non-Drupal files
Is it possible for Drush to ignore files or would they have to be copied out of root and copied back?
If Drupal files, how do we deal with existing files?  Merge? Overwrite? Rename New, Rename Old?

I can see Drush asking the user what they want to do with each existing file.  Since Drush does a backup by default, if the user fat-fingers their choice, they can always retrieve out of the backup, right?

I've got some other thoughts on the existing Drupal files, so I'll go find that issue to post in.

**Comment by AdamPS** [comment]
Note that drush expert @greg-1-anderson has already proposed a solution that I think is extremely attractive: drush can **automatically** determine which files were part of drupal in the first place and only delete those same files.

As remarked earlier in the thread, a .drushignore file could be better than nothing for the user to manually set which files are ignored (which yes I expect means copied out and copied back).

In terms of this thread, the above defines a strategy which has a rough consensus and it mostly needs someone to code it.

@philsward Please I feel you are hijacking this issue which has a specific topic.  You can create your own issue to discuss editing Drupal files, or a meta-issue to link several topics if you like.  If you need advice, try Drupal Answers http://drupal.stackexchange.com/.

Note that editing core files is considered inadvisable by many.  I'm not sure there is likely to be a general solution because a merge is needed which likely requires manual intervention.  Many techniques exist already (but I'd rather not discuss them, further right here!):
* modules for a specific purpose such as https://www.drupal.org/project/robotstxt and https://www.drupal.org/project/htaccess.
* local scripts that wrap drush download and copy/patch files in some way
* use git to manage the website which simplifies merge and staging to live.

**Comment by greg-1-anderson** [comment]
We'd need a pm-update champion for this to move forward. I am putting my efforts towards updating via Composer; see https://github.com/drupal-composer/drupal-project/pull/77 and [drupal-composer/drupal-scaffold](https://github.com/drupal-composer/drupal-scaffold).  I personally would just as soon see Drush get out of the updating business, but I know it will be a long time before everyone is using Composer.

**Comment by AdamPS** [comment]
It looks like code to solve some of all of these problems is now in D8.  Maybe best just to close this one as fixed?

BTW I am a strong fan of drush updating - it works and I don't have to learn a new tool like composer.

**Comment by greg-1-anderson** [comment]
I don't disagree about the usefulness of the pm-* code; we just need someone to step forward and maintain it if it is going to be maintained.

**Comment by AdamPS** [comment]
@greg-1-anderson I will do what I can to help keep pm-* code alive, but I'm certainly not a drush expert.  In fact there's action right now on #1056 where I'm keen to help but it needs a drush expert involved for advice - if you can help or know someone who can, I would be grateful.

In the meantime, I think we should close this issue because it's fixed (or almost all) in Drush 8.  But I can't see a way for me to do it, so please could you?

**Comment by greg-1-anderson** [comment]
I haven't confirmed that these issues have been fixed in Drush 8. Are there unit tests covering this functionality in place?

**Comment by AdamPS** [comment]
Sorry, sure if you are still working on it then no problem.  No I haven't checked the unit tests, I'm afraid I don't even know where they live.

By real use experiment, I have found that 'unexpected' files in the top level directory and in the profiles directory are preserved when drupal core is upgraded.  This is achieved without the need for user configuration by finding any files that are missing present in the new drupal core and preserving them.  Non-writable files and recognised code management files are also preserved.

**Comment by greg-1-anderson** [comment]
@jhedstrom probably knows and can close if appropriate.

**Comment by AdamPS** [comment]
Update - I'm not sure this is fixed.  The new D8 code seems to preserve any 'unexpected' file in the root.  Unfortunately I think this would also preserve a file that was in Drupal core then got removed in a newer version.  Unlikely, but worse case potentially it could back out a security fix.  A second problem is that the fix appears to be only for VCS=backup.  I'll raise a new issue when I have a mo.

**Comment by AdamPS** [comment]
New issue raised.  First step would be useful if anyone could comment on whether it's a good idea.  

If so I could try to code it, but it's a lower priority than a bunch of real bugs I'm hitting now I'm on drush 8 - if anyone from the drush team gets a chance to look at those issues and the pull request I'd be grateful.

@greg-1-anderson the composer framework looks interesting and I might look into it when I move to D8, but that's probably not for a couple of years for me.

**Comment by AdamPS** [comment]
To summarise: this is fixed in the default scenario, which is

- --version-control=backup
- There is a backup (i.e. not --no-backup)

@weitzman stated in #2275 that he "doubt this will ever get fixed" to work with --no-backup (I did have a PR but it was not taken - significant changes to drush pm are not wanted any more as pm is deprecated.)

So I suggest it makes sense to close this issue as fixed - which is true for 99% of users.
