### ISSUE TITLE
Regression: site:set no longer works due to additional process

### ISSUE THREAD

**Issue by deviantintegral** [drush-ops/drush#6141]
**Describe the bug**

`drush site:set` uses the parent process ID to identify which future commands the site has been set for:

https://github.com/drush-ops/drush/blob/13.x/src/Config/Environment.php#L380

https://github.com/drush-ops/drush/pull/6124 added a wrapper shell script to disable xdebug. Unfortunately, this means we now need to get the parent of the parent's PID.

**To Reproduce**

`drush site:set <alias> && drush status`.

**Workaround**

Users could call drush.php directly, but that's not an obvious fix.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.3.0
| Drupal version? | 10.x
| PHP version     | 8.3
| OS?             | Linux

**Additional information**

https://github.com/drush-ops/drush/issues/6137 is another regression related to this.

This also happened to break our automated tests that allow us to run Drush against a child test site. We can change this, this is very much us reaching into Drush internals! But, it makes me wonder if others out there are expecting `vendor/bin/drush` to remain a PHP script at least for this major version.

https://github.com/Lullabot/playwright-drupal/blob/6ebb053d43e7393f5274106f928a6c8d78791e34/bin/drush-playwright-internal#L45

**Comment by Chi-teck** [comment]
Another consequence is it's no longer possible to specify PHP binary when running drush.

Though you can run `vendor/drush/drush/drush.php` directly.

**Comment by webflo** [comment]
Sorry, for all the trouble. 

@Chi-teck In any case, it was not guaranteed that the same PHP binary was used in a subcommand (afaik). I had always adjusted the ```$PATH``` variable for this.

**Comment by weitzman** [comment]
Yes, we have not supported specifying a php binary in years. The documented way is to adjust your PATH. See Note at https://www.drush.org/13.x/install/

Back to the site:set - yes, it seems we broke this. Its a very seldom used feature, as measured by bugs and feature requests in this project. I'd like for this functionality to move out of Drush core. Take a look at https://github.com/g1a/fd. Otherwise, this it could be added to https://github.com/jonpugh/ash.

**Comment by webflo** [comment]
I never used ```site:site``` before. But could it be replaced by an environment variable in the shell process?

**Comment by deviantintegral** [comment]
It would be fine to drop this in Drush 14 for any of the above alternatives. But can we get it fixed for 13.x? I don't have any ideas beyond reverting the xdebug change though.

**Comment by greg-1-anderson** [comment]
Could we put `drush` back to being the php script, and make a secondary bash script, `drush-without-xdebug` or something that folks could use (e.g. with a bash alias) if they wanted?

**Comment by weitzman** [comment]
That wont achieve the goal of improving performance for most people. The point of the bash script is to help folks who are not knowing they are experiencing a slowdown. Most people will not use the alternate entry point.

IMO the workarounds mentioned here are adequate. Using site:set inside a script is a misuse IMO. Its meant as a convenience for interactive users (i.e. humans). When scripting, make drush calls with a site alias every time. Or call drush.php if you prefer site:set for some reason. IMO site:set isn't part of the semver contract because its an interactive tool. I know some will disagree - its a nuanced issue.

**Comment by greg-1-anderson** [comment]
I am not strongly opinionated about site:set, which I have not used for years. However, I am generally concerned about introducing a new process. I have an idea that I think will address all use cases; I'll try to make a PoC PR shortly.

**Comment by weitzman** [comment]
Use [latest composer](https://github.com/composer/composer/releases/tag/2.8.2) and Drush 13.3.1+

**Comment by deviantintegral** [comment]
Thanks folks! This is working well for us. Appreciate your efforts.
