### ISSUE TITLE
No such file or directory in drupal_is_denied()

### ISSUE THREAD

**Issue by Cogax** [drush-ops/drush#657]
Always when i want to clear my cache, drush sends me this error:

```
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in drupal_is_denied() (line 1916 of /Users/andy/Projects/drupal/xdist/includes/bootstrap.inc).</p><h2>Additional</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in system_list() (line 165 of /Users/andy/Projects/drupal/xdist/includes/module.inc).</p><hr />Drush command terminated abnormally due to an unrecoverable error.   [error]
```

This error is also show on drush info for example. The Drupal installation works finde, i searched in the web for this error but there arent any problems like this.

**Comment by jenlampton** [comment]
I'm also seeing this issue for the drush.phar for the 8.0.1 release. When I git clone drush 8 and run cc all it works as expected, but when I use the drush.phar it throws this error:
`
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in drupal_is_denied() (line 1917 of drupal/includes/bootstrap.inc).</p><h2>Additional</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in _registry_check_code() (line 3169 of drupal/includes/bootstrap.inc).</p><hr />Drush command terminated abnormally due to an unrecoverable error. 
`

Also, this is a bug report. Not sure how to indicate as much on this ticket :)

**Comment by weitzman** [comment]
Any chance you can archive-dump your Drupal site and send it to me? If not, I dont know how to reproduce this.

**Comment by jenlampton** [comment]
Running archive-dump with Drush 6. The archive is too big to attach to this issue, so I'm going to email instead.

**Comment by jenlampton** [comment]
This is still the case for Drush 8.0.5.
