### ISSUE TITLE
"drush @sites cron --quiet --yes" is not quiet

### ISSUE THREAD

**Issue by MrHaroldA** [drush-ops/drush#81]
I was expecting / hoping that drush @sites cron --quiet --yes would not generate output, but it does:

```
$ drush @sites cron --quiet --yes
You are about to execute 'cron' non-interactively (--yes forced) on all of the following targets:
  /var/www/site#one
  /var/www/site#two
Continue?  (y/n): y
Cron run successful.
```

It seems logical to me to suppress the interactive questions when --quiet and --yes are combined. I did find a couple of issues about the --quiet option but they're all fixed and closed. Is the behavior above correct and by design?

https://drupal.org/node/1830120

**Comment by drzraf** [comment]
was it really fixed, or "just fixed for the specific cron command" ?
Using drush 6.5.0:
$ drush @sites --yes --quiet pm-info
output "You are about to execute ... "

**Comment by greg-1-anderson** [comment]
This commit was only applied to the master branch.  I think it's a good time to upgrade to the 7.x branch; only critical (or at least important) issues are going to be backported to the 6.x branch.

**Comment by drzraf** [comment]
good to know
(but I currently stuck with an Ubuntu LTS (php 5.3.2) which keeps me from installing drush 7.x)

**Comment by greg-1-anderson** [comment]
It's easy to upgrade your php on Ubuntu 12.04:

http://phpave.com/upgrade-php-5-3-php-5-5-ubuntu-12-04-lts/

Also, there's a newer LTS release, 14.04, that ships with php 5.5.9.

It would be a really good idea to upgrade your php, since 5.3 isn't supported any longer; however, you don't have to, because Drush 7 works on 5.3.  See: http://docs.drush.org/en/master/install/

We're not going to require php 5.4 until Drush 8 -- by the time we get around to doing that, php 5.4 probably won't be supported any longer either!  But we usually support a few versions back, since a lot of folks are stuck on old distros.

**Comment by drzraf** [comment]
On Wed, Apr 01, 2015 at 08:12:31PM -0700, Greg Anderson wrote:
> It would be a really good idea to upgrade your php, since 5.3 isn't
> supported any longer; however, you don't have to, because Drush 7
> works on 5.3.  See: http://docs.drush.org/en/master/install/

$ composer global require drush/drush:dev-master
> Your requirements could not be resolved to an installable set of packages.
Because drush require symfony/yaml ~2.2
But all and every version of symfony/yaml >= v2.2.0 require php >=5.3.3


> We're not going to require php 5.4 until Drush 8 -- by the time we get
> around to doing that, php 5.4 probably won't be supported any longer
> either!  But we usually support a few versions back, since a lot of
> folks are stuck on old distros.

While I'd be happy if the above patch were to be backported to the 6.x
branch, I'm absolutely not arguing with my particular situation in mind.
I see a lot of good reasons for *not* supporting "old" PHP (with "old"
often being "newer" than what is currently considered by drush and
Drupal).

Counting on newer software stacks permits the removal of a bunch of old
cruft (... but not so much as it would if windows/non-posix OS support
were to be abandoned :)) but that's another story.

**Comment by greg-1-anderson** [comment]
That's a very good point!  Even though Drush itself only enforces php > 5.3.0, now that we use Composer, we inherit additional requirements from our dependencies.

It would be nice if Drush 7 could be installed on a stock Ubuntu 12.04.5, which is supported through April 2017.  I don't know if it would be practical for us to downgrade our yaml requirement.  If this was tenable, then a PR would be welcome.
